// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: chat.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class InteractiveItemConf
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "pbcmd.InteractiveItemConf.Item")]
        public global::System.Collections.Generic.List<Item> items { get; } = new global::System.Collections.Generic.List<Item>();

        [System.Serializable]
        [global::ProtoBuf.ProtoContract()]
        public partial class Item
        {
            [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
            public uint id { get; set; }

            [global::ProtoBuf.ProtoMember(2)]
            public uint cost
            {
                get { return __pbn__cost.GetValueOrDefault(); }
                set { __pbn__cost = value; }
            }
            public bool ShouldSerializecost() => __pbn__cost != null;
            public void Resetcost() => __pbn__cost = null;
            private uint? __pbn__cost;

            [global::ProtoBuf.ProtoMember(3)]
            public uint coinType
            {
                get { return __pbn__coinType.GetValueOrDefault(); }
                set { __pbn__coinType = value; }
            }
            public bool ShouldSerializecoinType() => __pbn__coinType != null;
            public void ResetcoinType() => __pbn__coinType = null;
            private uint? __pbn__coinType;

        }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterChannelReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RegisterChannelResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

        [global::ProtoBuf.ProtoMember(3)]
        public InteractiveItemConf itemConf { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnRegisterChannelReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnRegisterChannelResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SendChatReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint recv_uid
        {
            get { return __pbn__recv_uid.GetValueOrDefault(); }
            set { __pbn__recv_uid = value; }
        }
        public bool ShouldSerializerecv_uid() => __pbn__recv_uid != null;
        public void Resetrecv_uid() => __pbn__recv_uid = null;
        private uint? __pbn__recv_uid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(global::pbcmd.ChatType.ChatType_PC)]
        public ChatType chat_type
        {
            get { return __pbn__chat_type ?? global::pbcmd.ChatType.ChatType_PC; }
            set { __pbn__chat_type = value; }
        }
        public bool ShouldSerializechat_type() => __pbn__chat_type != null;
        public void Resetchat_type() => __pbn__chat_type = null;
        private ChatType? __pbn__chat_type;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(global::pbcmd.ContentType.ContentType_Text)]
        public ContentType content_type
        {
            get { return __pbn__content_type ?? global::pbcmd.ContentType.ContentType_Text; }
            set { __pbn__content_type = value; }
        }
        public bool ShouldSerializecontent_type() => __pbn__content_type != null;
        public void Resetcontent_type() => __pbn__content_type = null;
        private ContentType? __pbn__content_type;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content
        {
            get { return __pbn__content ?? ""; }
            set { __pbn__content = value; }
        }
        public bool ShouldSerializecontent() => __pbn__content != null;
        public void Resetcontent() => __pbn__content = null;
        private string __pbn__content;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SendChatResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SendChatPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint send_uid
        {
            get { return __pbn__send_uid.GetValueOrDefault(); }
            set { __pbn__send_uid = value; }
        }
        public bool ShouldSerializesend_uid() => __pbn__send_uid != null;
        public void Resetsend_uid() => __pbn__send_uid = null;
        private uint? __pbn__send_uid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(global::pbcmd.ContentType.ContentType_Text)]
        public ContentType content_type
        {
            get { return __pbn__content_type ?? global::pbcmd.ContentType.ContentType_Text; }
            set { __pbn__content_type = value; }
        }
        public bool ShouldSerializecontent_type() => __pbn__content_type != null;
        public void Resetcontent_type() => __pbn__content_type = null;
        private ContentType? __pbn__content_type;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content
        {
            get { return __pbn__content ?? ""; }
            set { __pbn__content = value; }
        }
        public bool ShouldSerializecontent() => __pbn__content != null;
        public void Resetcontent() => __pbn__content = null;
        private string __pbn__content;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SendInteractivePropReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint recv_uid
        {
            get { return __pbn__recv_uid.GetValueOrDefault(); }
            set { __pbn__recv_uid = value; }
        }
        public bool ShouldSerializerecv_uid() => __pbn__recv_uid != null;
        public void Resetrecv_uid() => __pbn__recv_uid = null;
        private uint? __pbn__recv_uid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

        [global::ProtoBuf.ProtoMember(3)]
        public uint prop_id
        {
            get { return __pbn__prop_id.GetValueOrDefault(); }
            set { __pbn__prop_id = value; }
        }
        public bool ShouldSerializeprop_id() => __pbn__prop_id != null;
        public void Resetprop_id() => __pbn__prop_id = null;
        private uint? __pbn__prop_id;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SendInteractivePropResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong leftMoney
        {
            get { return __pbn__leftMoney.GetValueOrDefault(); }
            set { __pbn__leftMoney = value; }
        }
        public bool ShouldSerializeleftMoney() => __pbn__leftMoney != null;
        public void ResetleftMoney() => __pbn__leftMoney = null;
        private ulong? __pbn__leftMoney;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SendInteractivePropPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint send_uid
        {
            get { return __pbn__send_uid.GetValueOrDefault(); }
            set { __pbn__send_uid = value; }
        }
        public bool ShouldSerializesend_uid() => __pbn__send_uid != null;
        public void Resetsend_uid() => __pbn__send_uid = null;
        private uint? __pbn__send_uid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint recv_uid
        {
            get { return __pbn__recv_uid.GetValueOrDefault(); }
            set { __pbn__recv_uid = value; }
        }
        public bool ShouldSerializerecv_uid() => __pbn__recv_uid != null;
        public void Resetrecv_uid() => __pbn__recv_uid = null;
        private uint? __pbn__recv_uid;

        [global::ProtoBuf.ProtoMember(3)]
        public uint channel_id
        {
            get { return __pbn__channel_id.GetValueOrDefault(); }
            set { __pbn__channel_id = value; }
        }
        public bool ShouldSerializechannel_id() => __pbn__channel_id != null;
        public void Resetchannel_id() => __pbn__channel_id = null;
        private uint? __pbn__channel_id;

        [global::ProtoBuf.ProtoMember(4)]
        public uint prop_id
        {
            get { return __pbn__prop_id.GetValueOrDefault(); }
            set { __pbn__prop_id = value; }
        }
        public bool ShouldSerializeprop_id() => __pbn__prop_id != null;
        public void Resetprop_id() => __pbn__prop_id = null;
        private uint? __pbn__prop_id;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum ChatType
    {
        ChatType_PC = 0,
        ChatType_GC = 1,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum ContentType
    {
        ContentType_Text = 0,
        ContentType_Voice = 1,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
