// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: clubNew.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CreateClubReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string icon
        {
            get { return __pbn__icon ?? ""; }
            set { __pbn__icon = value; }
        }
        public bool ShouldSerializeicon() => __pbn__icon != null;
        public void Reseticon() => __pbn__icon = null;
        private string __pbn__icon;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CreateClubResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class JoinClubReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class JoinClubResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int editType
        {
            get { return __pbn__editType.GetValueOrDefault(); }
            set { __pbn__editType = value; }
        }
        public bool ShouldSerializeeditType() => __pbn__editType != null;
        public void ReseteditType() => __pbn__editType = null;
        private int? __pbn__editType;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string icon
        {
            get { return __pbn__icon ?? ""; }
            set { __pbn__icon = value; }
        }
        public bool ShouldSerializeicon() => __pbn__icon != null;
        public void Reseticon() => __pbn__icon = null;
        private string __pbn__icon;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public ClubInfo info { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveClubBalanceReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveClubBalanceResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(4)]
        public long clubBalance
        {
            get { return __pbn__clubBalance.GetValueOrDefault(); }
            set { __pbn__clubBalance = value; }
        }
        public bool ShouldSerializeclubBalance() => __pbn__clubBalance != null;
        public void ResetclubBalance() => __pbn__clubBalance = null;
        private long? __pbn__clubBalance;

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class WithdrawClubBalanceReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class WithdrawClubBalanceResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(4)]
        public long clubBalance
        {
            get { return __pbn__clubBalance.GetValueOrDefault(); }
            set { __pbn__clubBalance = value; }
        }
        public bool ShouldSerializeclubBalance() => __pbn__clubBalance != null;
        public void ResetclubBalance() => __pbn__clubBalance = null;
        private long? __pbn__clubBalance;

        [global::ProtoBuf.ProtoMember(5)]
        public long balanceLimit
        {
            get { return __pbn__balanceLimit.GetValueOrDefault(); }
            set { __pbn__balanceLimit = value; }
        }
        public bool ShouldSerializebalanceLimit() => __pbn__balanceLimit != null;
        public void ResetbalanceLimit() => __pbn__balanceLimit = null;
        private long? __pbn__balanceLimit;

        [global::ProtoBuf.ProtoMember(6)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubInsurancePayMethodReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int payMethod
        {
            get { return __pbn__payMethod.GetValueOrDefault(); }
            set { __pbn__payMethod = value; }
        }
        public bool ShouldSerializepayMethod() => __pbn__payMethod != null;
        public void ResetpayMethod() => __pbn__payMethod = null;
        private int? __pbn__payMethod;

        [global::ProtoBuf.ProtoMember(3)]
        public long payLimit
        {
            get { return __pbn__payLimit.GetValueOrDefault(); }
            set { __pbn__payLimit = value; }
        }
        public bool ShouldSerializepayLimit() => __pbn__payLimit != null;
        public void ResetpayLimit() => __pbn__payLimit = null;
        private long? __pbn__payLimit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubInsurancePayMethodResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int payMethod
        {
            get { return __pbn__payMethod.GetValueOrDefault(); }
            set { __pbn__payMethod = value; }
        }
        public bool ShouldSerializepayMethod() => __pbn__payMethod != null;
        public void ResetpayMethod() => __pbn__payMethod = null;
        private int? __pbn__payMethod;

        [global::ProtoBuf.ProtoMember(4)]
        public long payLimit
        {
            get { return __pbn__payLimit.GetValueOrDefault(); }
            set { __pbn__payLimit = value; }
        }
        public bool ShouldSerializepayLimit() => __pbn__payLimit != null;
        public void ResetpayLimit() => __pbn__payLimit = null;
        private long? __pbn__payLimit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubUserRemarkReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string remark
        {
            get { return __pbn__remark ?? ""; }
            set { __pbn__remark = value; }
        }
        public bool ShouldSerializeremark() => __pbn__remark != null;
        public void Resetremark() => __pbn__remark = null;
        private string __pbn__remark;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubUserRemarkResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string remark
        {
            get { return __pbn__remark ?? ""; }
            set { __pbn__remark = value; }
        }
        public bool ShouldSerializeremark() => __pbn__remark != null;
        public void Resetremark() => __pbn__remark = null;
        private string __pbn__remark;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveClubUserReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int[] userIds { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveClubUserResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int[] userIds { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubUserLevelReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.ClubUserLevel")]
        public global::System.Collections.Generic.List<ClubUserLevel> levels { get; } = new global::System.Collections.Generic.List<ClubUserLevel>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubUserLevelResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.ClubUserInfo")]
        public global::System.Collections.Generic.List<ClubUserInfo> userInfos { get; } = new global::System.Collections.Generic.List<ClubUserInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubUserLevelPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public ClubUserLevel level { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubRebateRatioReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int roomFee
        {
            get { return __pbn__roomFee.GetValueOrDefault(); }
            set { __pbn__roomFee = value; }
        }
        public bool ShouldSerializeroomFee() => __pbn__roomFee != null;
        public void ResetroomFee() => __pbn__roomFee = null;
        private int? __pbn__roomFee;

        [global::ProtoBuf.ProtoMember(3)]
        public int insurance
        {
            get { return __pbn__insurance.GetValueOrDefault(); }
            set { __pbn__insurance = value; }
        }
        public bool ShouldSerializeinsurance() => __pbn__insurance != null;
        public void Resetinsurance() => __pbn__insurance = null;
        private int? __pbn__insurance;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubRebateRatioResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int roomFee
        {
            get { return __pbn__roomFee.GetValueOrDefault(); }
            set { __pbn__roomFee = value; }
        }
        public bool ShouldSerializeroomFee() => __pbn__roomFee != null;
        public void ResetroomFee() => __pbn__roomFee = null;
        private int? __pbn__roomFee;

        [global::ProtoBuf.ProtoMember(4)]
        public int insurance
        {
            get { return __pbn__insurance.GetValueOrDefault(); }
            set { __pbn__insurance = value; }
        }
        public bool ShouldSerializeinsurance() => __pbn__insurance != null;
        public void Resetinsurance() => __pbn__insurance = null;
        private int? __pbn__insurance;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubSettingReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int setting
        {
            get { return __pbn__setting.GetValueOrDefault(); }
            set { __pbn__setting = value; }
        }
        public bool ShouldSerializesetting() => __pbn__setting != null;
        public void Resetsetting() => __pbn__setting = null;
        private int? __pbn__setting;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SetClubSettingResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int setting
        {
            get { return __pbn__setting.GetValueOrDefault(); }
            set { __pbn__setting = value; }
        }
        public bool ShouldSerializesetting() => __pbn__setting != null;
        public void Resetsetting() => __pbn__setting = null;
        private int? __pbn__setting;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class DismissClubReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class DismissClubResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class QuitClubReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class QuitClubResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public ClubInfo info { get; set; }

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.ClubUserInfo")]
        public global::System.Collections.Generic.List<ClubUserInfo> userInfos { get; } = new global::System.Collections.Generic.List<ClubUserInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubListReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubListResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.ClubInfo")]
        public global::System.Collections.Generic.List<ClubInfo> infos { get; } = new global::System.Collections.Generic.List<ClubInfo>();

        [global::ProtoBuf.ProtoMember(3)]
        public int createNum
        {
            get { return __pbn__createNum.GetValueOrDefault(); }
            set { __pbn__createNum = value; }
        }
        public bool ShouldSerializecreateNum() => __pbn__createNum != null;
        public void ResetcreateNum() => __pbn__createNum = null;
        private int? __pbn__createNum;

        [global::ProtoBuf.ProtoMember(4)]
        public int maxCreateNum
        {
            get { return __pbn__maxCreateNum.GetValueOrDefault(); }
            set { __pbn__maxCreateNum = value; }
        }
        public bool ShouldSerializemaxCreateNum() => __pbn__maxCreateNum != null;
        public void ResetmaxCreateNum() => __pbn__maxCreateNum = null;
        private int? __pbn__maxCreateNum;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubUsersReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private int? __pbn__page;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubUsersResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int total
        {
            get { return __pbn__total.GetValueOrDefault(); }
            set { __pbn__total = value; }
        }
        public bool ShouldSerializetotal() => __pbn__total != null;
        public void Resettotal() => __pbn__total = null;
        private int? __pbn__total;

        [global::ProtoBuf.ProtoMember(3)]
        public int page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private int? __pbn__page;

        [global::ProtoBuf.ProtoMember(4)]
        public int pagesize
        {
            get { return __pbn__pagesize.GetValueOrDefault(); }
            set { __pbn__pagesize = value; }
        }
        public bool ShouldSerializepagesize() => __pbn__pagesize != null;
        public void Resetpagesize() => __pbn__pagesize = null;
        private int? __pbn__pagesize;

        [global::ProtoBuf.ProtoMember(5, TypeName = "pbcmd.ClubUserInfo")]
        public global::System.Collections.Generic.List<ClubUserInfo> infos { get; } = new global::System.Collections.Generic.List<ClubUserInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessUserJoinReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(3)]
        public int option
        {
            get { return __pbn__option.GetValueOrDefault(); }
            set { __pbn__option = value; }
        }
        public bool ShouldSerializeoption() => __pbn__option != null;
        public void Resetoption() => __pbn__option = null;
        private int? __pbn__option;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessUserJoinResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionListReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionListResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.UnionInfo")]
        public global::System.Collections.Generic.List<UnionInfo> infos { get; } = new global::System.Collections.Generic.List<UnionInfo>();

        [global::ProtoBuf.ProtoMember(3)]
        public int maxUnionNum
        {
            get { return __pbn__maxUnionNum.GetValueOrDefault(); }
            set { __pbn__maxUnionNum = value; }
        }
        public bool ShouldSerializemaxUnionNum() => __pbn__maxUnionNum != null;
        public void ResetmaxUnionNum() => __pbn__maxUnionNum = null;
        private int? __pbn__maxUnionNum;

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.UnionInfo")]
        public global::System.Collections.Generic.List<UnionInfo> hasQuit { get; } = new global::System.Collections.Generic.List<UnionInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class JoinUnionReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class JoinUnionResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RecommendUnionListReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RecommendUnionListResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.UnionInfo")]
        public global::System.Collections.Generic.List<UnionInfo> infos { get; } = new global::System.Collections.Generic.List<UnionInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class JoinUnionMsg
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public long time
        {
            get { return __pbn__time.GetValueOrDefault(); }
            set { __pbn__time = value; }
        }
        public bool ShouldSerializetime() => __pbn__time != null;
        public void Resettime() => __pbn__time = null;
        private long? __pbn__time;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string msg
        {
            get { return __pbn__msg ?? ""; }
            set { __pbn__msg = value; }
        }
        public bool ShouldSerializemsg() => __pbn__msg != null;
        public void Resetmsg() => __pbn__msg = null;
        private string __pbn__msg;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class JoinUnionResult
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int option
        {
            get { return __pbn__option.GetValueOrDefault(); }
            set { __pbn__option = value; }
        }
        public bool ShouldSerializeoption() => __pbn__option != null;
        public void Resetoption() => __pbn__option = null;
        private int? __pbn__option;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string unionName
        {
            get { return __pbn__unionName ?? ""; }
            set { __pbn__unionName = value; }
        }
        public bool ShouldSerializeunionName() => __pbn__unionName != null;
        public void ResetunionName() => __pbn__unionName = null;
        private string __pbn__unionName;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string userName
        {
            get { return __pbn__userName ?? ""; }
            set { __pbn__userName = value; }
        }
        public bool ShouldSerializeuserName() => __pbn__userName != null;
        public void ResetuserName() => __pbn__userName = null;
        private string __pbn__userName;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ViewNotOfferedBillReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ViewNotOfferedBillResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public double totalNotOffered
        {
            get { return __pbn__totalNotOffered.GetValueOrDefault(); }
            set { __pbn__totalNotOffered = value; }
        }
        public bool ShouldSerializetotalNotOffered() => __pbn__totalNotOffered != null;
        public void ResettotalNotOffered() => __pbn__totalNotOffered = null;
        private double? __pbn__totalNotOffered;

        [global::ProtoBuf.ProtoMember(3)]
        public double totalNotRepaid
        {
            get { return __pbn__totalNotRepaid.GetValueOrDefault(); }
            set { __pbn__totalNotRepaid = value; }
        }
        public bool ShouldSerializetotalNotRepaid() => __pbn__totalNotRepaid != null;
        public void ResettotalNotRepaid() => __pbn__totalNotRepaid = null;
        private double? __pbn__totalNotRepaid;

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.BillInfo")]
        public global::System.Collections.Generic.List<BillInfo> infos { get; } = new global::System.Collections.Generic.List<BillInfo>();

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ViewNotRepaidBillReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ViewNotRepaidBillResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public double totalNotOffered
        {
            get { return __pbn__totalNotOffered.GetValueOrDefault(); }
            set { __pbn__totalNotOffered = value; }
        }
        public bool ShouldSerializetotalNotOffered() => __pbn__totalNotOffered != null;
        public void ResettotalNotOffered() => __pbn__totalNotOffered = null;
        private double? __pbn__totalNotOffered;

        [global::ProtoBuf.ProtoMember(3)]
        public double totalNotRepaid
        {
            get { return __pbn__totalNotRepaid.GetValueOrDefault(); }
            set { __pbn__totalNotRepaid = value; }
        }
        public bool ShouldSerializetotalNotRepaid() => __pbn__totalNotRepaid != null;
        public void ResettotalNotRepaid() => __pbn__totalNotRepaid = null;
        private double? __pbn__totalNotRepaid;

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.BillInfo")]
        public global::System.Collections.Generic.List<BillInfo> infos { get; } = new global::System.Collections.Generic.List<BillInfo>();

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RepayReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public int billId
        {
            get { return __pbn__billId.GetValueOrDefault(); }
            set { __pbn__billId = value; }
        }
        public bool ShouldSerializebillId() => __pbn__billId != null;
        public void ResetbillId() => __pbn__billId = null;
        private int? __pbn__billId;

        [global::ProtoBuf.ProtoMember(4)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RepayResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(4)]
        public int billId
        {
            get { return __pbn__billId.GetValueOrDefault(); }
            set { __pbn__billId = value; }
        }
        public bool ShouldSerializebillId() => __pbn__billId != null;
        public void ResetbillId() => __pbn__billId = null;
        private int? __pbn__billId;

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubGainInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private int? __pbn__page;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubGainInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int total
        {
            get { return __pbn__total.GetValueOrDefault(); }
            set { __pbn__total = value; }
        }
        public bool ShouldSerializetotal() => __pbn__total != null;
        public void Resettotal() => __pbn__total = null;
        private int? __pbn__total;

        [global::ProtoBuf.ProtoMember(4)]
        public int page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private int? __pbn__page;

        [global::ProtoBuf.ProtoMember(5)]
        public int pagesize
        {
            get { return __pbn__pagesize.GetValueOrDefault(); }
            set { __pbn__pagesize = value; }
        }
        public bool ShouldSerializepagesize() => __pbn__pagesize != null;
        public void Resetpagesize() => __pbn__pagesize = null;
        private int? __pbn__pagesize;

        [global::ProtoBuf.ProtoMember(6, TypeName = "pbcmd.ClubGainInfo")]
        public global::System.Collections.Generic.List<ClubGainInfo> infos { get; } = new global::System.Collections.Generic.List<ClubGainInfo>();

        [global::ProtoBuf.ProtoMember(7)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubGainInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int id
        {
            get { return __pbn__id.GetValueOrDefault(); }
            set { __pbn__id = value; }
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private int? __pbn__id;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public double amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private double? __pbn__amount;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string reason
        {
            get { return __pbn__reason ?? ""; }
            set { __pbn__reason = value; }
        }
        public bool ShouldSerializereason() => __pbn__reason != null;
        public void Resetreason() => __pbn__reason = null;
        private string __pbn__reason;

        [global::ProtoBuf.ProtoMember(5)]
        public long timestamp
        {
            get { return __pbn__timestamp.GetValueOrDefault(); }
            set { __pbn__timestamp = value; }
        }
        public bool ShouldSerializetimestamp() => __pbn__timestamp != null;
        public void Resettimestamp() => __pbn__timestamp = null;
        private long? __pbn__timestamp;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

        [global::ProtoBuf.ProtoMember(7)]
        public long mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private long? __pbn__mid;

        [global::ProtoBuf.ProtoMember(8)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum ClubNew
    {
        Cmd_CreateClubReq = 1,
        Cmd_CreateClubResp = 2,
        Cmd_JoinClubReq = 3,
        Cmd_JoinClubResp = 4,
        Cmd_SetClubInfoReq = 5,
        Cmd_SetClubInfoResp = 6,
        Cmd_SaveClubBalanceReq = 7,
        Cmd_SaveClubBalanceResp = 8,
        Cmd_WithdrawClubBalanceReq = 9,
        Cmd_WithdrawClubBalanceResp = 10,
        Cmd_SetClubInsurancePayMethodReq = 11,
        Cmd_SetClubInsurancePayMethodResp = 12,
        Cmd_SetClubUserRemarkReq = 13,
        Cmd_SetClubUserRemarkResp = 14,
        Cmd_RemoveClubUserReq = 15,
        Cmd_RemoveClubUserResp = 16,
        Cmd_SetClubUserLevelReq = 17,
        Cmd_SetClubUserLevelResp = 18,
        Cmd_SetClubRebateRatioReq = 19,
        Cmd_SetClubRebateRatioResp = 20,
        Cmd_SetClubSettingReq = 21,
        Cmd_SetClubSettingResp = 22,
        Cmd_DismissClubReq = 23,
        Cmd_DismissClubResp = 24,
        Cmd_QuitClubReq = 25,
        Cmd_QuitClubResp = 26,
        Cmd_ClubInfoReq = 27,
        Cmd_ClubInfoResp = 28,
        Cmd_ClubListReq = 29,
        Cmd_ClubListResp = 30,
        Cmd_ClubUsersReq = 31,
        Cmd_ClubUsersResp = 32,
        Cmd_ProcessUserJoinReq = 33,
        Cmd_ProcessUserJoinResp = 34,
        Cmd_FetchMsgReq = 35,
        Cmd_FetchMsgResp = 36,
        Cmd_UnionListReq = 37,
        Cmd_UnionListResp = 38,
        Cmd_JoinUnionReq = 39,
        Cmd_JoinUnionResp = 40,
        Cmd_RecommendUnionListReq = 41,
        Cmd_RecommendUnionListResp = 42,
        Cmd_ViewNotOfferedBillReq = 43,
        Cmd_ViewNotOfferedBillResp = 44,
        Cmd_ViewNotRepaidBillReq = 45,
        Cmd_ViewNotRepaidBillResp = 46,
        Cmd_RepayReq = 47,
        Cmd_RepayResp = 48,
        Cmd_ClubGainInfoReq = 49,
        Cmd_ClubGainInfoResp = 50,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum insurancePayMethod
    {
        system = 1,
        unlimited = 2,
        limited = 4,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum clubSetting
    {
        allOff = 0,
        adminStartMatch = 1,
        clubSearchable = 2,
        adminStartMatch_clubSearchable = 3,
        autoJoin = 4,
        adminStartMatch_autoJoin = 5,
        clubSearchable_autoJoin = 6,
        adminStartMatch_clubSearchable_autoJoin = 7,
        autoJoin_autoJoinReview = 12,
        adminStartMatch_autoJoin_autoJoinReview = 13,
        clubSearchable_autoJoin_autoJoinReview = 14,
        allOn = 15,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
