// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: common.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBPlayer
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string country
        {
            get { return __pbn__country ?? ""; }
            set { __pbn__country = value; }
        }
        public bool ShouldSerializecountry() => __pbn__country != null;
        public void Resetcountry() => __pbn__country = null;
        private string __pbn__country;

        [global::ProtoBuf.ProtoMember(4)]
        public int gender
        {
            get { return __pbn__gender.GetValueOrDefault(); }
            set { __pbn__gender = value; }
        }
        public bool ShouldSerializegender() => __pbn__gender != null;
        public void Resetgender() => __pbn__gender = null;
        private int? __pbn__gender;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string nick
        {
            get { return __pbn__nick ?? ""; }
            set { __pbn__nick = value; }
        }
        public bool ShouldSerializenick() => __pbn__nick != null;
        public void Resetnick() => __pbn__nick = null;
        private string __pbn__nick;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string icon
        {
            get { return __pbn__icon ?? ""; }
            set { __pbn__icon = value; }
        }
        public bool ShouldSerializeicon() => __pbn__icon != null;
        public void Reseticon() => __pbn__icon = null;
        private string __pbn__icon;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string bigicon
        {
            get { return __pbn__bigicon ?? ""; }
            set { __pbn__bigicon = value; }
        }
        public bool ShouldSerializebigicon() => __pbn__bigicon != null;
        public void Resetbigicon() => __pbn__bigicon = null;
        private string __pbn__bigicon;

        [global::ProtoBuf.ProtoMember(8)]
        public ulong money
        {
            get { return __pbn__money.GetValueOrDefault(); }
            set { __pbn__money = value; }
        }
        public bool ShouldSerializemoney() => __pbn__money != null;
        public void Resetmoney() => __pbn__money = null;
        private ulong? __pbn__money;

        [global::ProtoBuf.ProtoMember(9)]
        public bool isOffline
        {
            get { return __pbn__isOffline.GetValueOrDefault(); }
            set { __pbn__isOffline = value; }
        }
        public bool ShouldSerializeisOffline() => __pbn__isOffline != null;
        public void ResetisOffline() => __pbn__isOffline = null;
        private bool? __pbn__isOffline;

        [global::ProtoBuf.ProtoMember(10)]
        public uint vip
        {
            get { return __pbn__vip.GetValueOrDefault(); }
            set { __pbn__vip = value; }
        }
        public bool ShouldSerializevip() => __pbn__vip != null;
        public void Resetvip() => __pbn__vip = null;
        private uint? __pbn__vip;

        [global::ProtoBuf.ProtoMember(11)]
        public ulong diamond
        {
            get { return __pbn__diamond.GetValueOrDefault(); }
            set { __pbn__diamond = value; }
        }
        public bool ShouldSerializediamond() => __pbn__diamond != null;
        public void Resetdiamond() => __pbn__diamond = null;
        private ulong? __pbn__diamond;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBMatchPrize
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint rank { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong chips
        {
            get { return __pbn__chips.GetValueOrDefault(); }
            set { __pbn__chips = value; }
        }
        public bool ShouldSerializechips() => __pbn__chips != null;
        public void Resetchips() => __pbn__chips = null;
        private ulong? __pbn__chips;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong point
        {
            get { return __pbn__point.GetValueOrDefault(); }
            set { __pbn__point = value; }
        }
        public bool ShouldSerializepoint() => __pbn__point != null;
        public void Resetpoint() => __pbn__point = null;
        private ulong? __pbn__point;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBChatMsg
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string faceid
        {
            get { return __pbn__faceid ?? ""; }
            set { __pbn__faceid = value; }
        }
        public bool ShouldSerializefaceid() => __pbn__faceid != null;
        public void Resetfaceid() => __pbn__faceid = null;
        private string __pbn__faceid;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string text
        {
            get { return __pbn__text ?? ""; }
            set { __pbn__text = value; }
        }
        public bool ShouldSerializetext() => __pbn__text != null;
        public void Resettext() => __pbn__text = null;
        private string __pbn__text;

        [global::ProtoBuf.ProtoMember(3)]
        public byte[] voice
        {
            get { return __pbn__voice; }
            set { __pbn__voice = value; }
        }
        public bool ShouldSerializevoice() => __pbn__voice != null;
        public void Resetvoice() => __pbn__voice = null;
        private byte[] __pbn__voice;

        [global::ProtoBuf.ProtoMember(4)]
        public uint voiceTotal
        {
            get { return __pbn__voiceTotal.GetValueOrDefault(); }
            set { __pbn__voiceTotal = value; }
        }
        public bool ShouldSerializevoiceTotal() => __pbn__voiceTotal != null;
        public void ResetvoiceTotal() => __pbn__voiceTotal = null;
        private uint? __pbn__voiceTotal;

        [global::ProtoBuf.ProtoMember(5)]
        public uint voiceIndex
        {
            get { return __pbn__voiceIndex.GetValueOrDefault(); }
            set { __pbn__voiceIndex = value; }
        }
        public bool ShouldSerializevoiceIndex() => __pbn__voiceIndex != null;
        public void ResetvoiceIndex() => __pbn__voiceIndex = null;
        private uint? __pbn__voiceIndex;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string voiceId
        {
            get { return __pbn__voiceId ?? ""; }
            set { __pbn__voiceId = value; }
        }
        public bool ShouldSerializevoiceId() => __pbn__voiceId != null;
        public void ResetvoiceId() => __pbn__voiceId = null;
        private string __pbn__voiceId;

        [global::ProtoBuf.ProtoMember(7)]
        public uint voiceLength
        {
            get { return __pbn__voiceLength.GetValueOrDefault(); }
            set { __pbn__voiceLength = value; }
        }
        public bool ShouldSerializevoiceLength() => __pbn__voiceLength != null;
        public void ResetvoiceLength() => __pbn__voiceLength = null;
        private uint? __pbn__voiceLength;

        [global::ProtoBuf.ProtoMember(8)]
        public uint voiceSecond
        {
            get { return __pbn__voiceSecond.GetValueOrDefault(); }
            set { __pbn__voiceSecond = value; }
        }
        public bool ShouldSerializevoiceSecond() => __pbn__voiceSecond != null;
        public void ResetvoiceSecond() => __pbn__voiceSecond = null;
        private uint? __pbn__voiceSecond;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class Msg
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(global::pbcmd.MSGTYPE.HEARTBEAT)]
        public MSGTYPE msgType
        {
            get { return __pbn__msgType ?? global::pbcmd.MSGTYPE.HEARTBEAT; }
            set { __pbn__msgType = value; }
        }
        public bool ShouldSerializemsgType() => __pbn__msgType != null;
        public void ResetmsgType() => __pbn__msgType = null;
        private MSGTYPE? __pbn__msgType;

        [global::ProtoBuf.ProtoMember(2)]
        public int status
        {
            get { return __pbn__status.GetValueOrDefault(); }
            set { __pbn__status = value; }
        }
        public bool ShouldSerializestatus() => __pbn__status != null;
        public void Resetstatus() => __pbn__status = null;
        private int? __pbn__status;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string service
        {
            get { return __pbn__service ?? ""; }
            set { __pbn__service = value; }
        }
        public bool ShouldSerializeservice() => __pbn__service != null;
        public void Resetservice() => __pbn__service = null;
        private string __pbn__service;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string method
        {
            get { return __pbn__method ?? ""; }
            set { __pbn__method = value; }
        }
        public bool ShouldSerializemethod() => __pbn__method != null;
        public void Resetmethod() => __pbn__method = null;
        private string __pbn__method;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string metadata
        {
            get { return __pbn__metadata ?? ""; }
            set { __pbn__metadata = value; }
        }
        public bool ShouldSerializemetadata() => __pbn__metadata != null;
        public void Resetmetadata() => __pbn__metadata = null;
        private string __pbn__metadata;

        [global::ProtoBuf.ProtoMember(6)]
        public byte[] payload
        {
            get { return __pbn__payload; }
            set { __pbn__payload = value; }
        }
        public bool ShouldSerializepayload() => __pbn__payload != null;
        public void Resetpayload() => __pbn__payload = null;
        private byte[] __pbn__payload;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UserInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string icon
        {
            get { return __pbn__icon ?? ""; }
            set { __pbn__icon = value; }
        }
        public bool ShouldSerializeicon() => __pbn__icon != null;
        public void Reseticon() => __pbn__icon = null;
        private string __pbn__icon;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string icon
        {
            get { return __pbn__icon ?? ""; }
            set { __pbn__icon = value; }
        }
        public bool ShouldSerializeicon() => __pbn__icon != null;
        public void Reseticon() => __pbn__icon = null;
        private string __pbn__icon;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

        [global::ProtoBuf.ProtoMember(5)]
        public int maxUserNum
        {
            get { return __pbn__maxUserNum.GetValueOrDefault(); }
            set { __pbn__maxUserNum = value; }
        }
        public bool ShouldSerializemaxUserNum() => __pbn__maxUserNum != null;
        public void ResetmaxUserNum() => __pbn__maxUserNum = null;
        private int? __pbn__maxUserNum;

        [global::ProtoBuf.ProtoMember(6)]
        public int userNum
        {
            get { return __pbn__userNum.GetValueOrDefault(); }
            set { __pbn__userNum = value; }
        }
        public bool ShouldSerializeuserNum() => __pbn__userNum != null;
        public void ResetuserNum() => __pbn__userNum = null;
        private int? __pbn__userNum;

        [global::ProtoBuf.ProtoMember(7)]
        public UserInfo ownerInfo { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public long createdAt
        {
            get { return __pbn__createdAt.GetValueOrDefault(); }
            set { __pbn__createdAt = value; }
        }
        public bool ShouldSerializecreatedAt() => __pbn__createdAt != null;
        public void ResetcreatedAt() => __pbn__createdAt = null;
        private long? __pbn__createdAt;

        [global::ProtoBuf.ProtoMember(9)]
        public int setting
        {
            get { return __pbn__setting.GetValueOrDefault(); }
            set { __pbn__setting = value; }
        }
        public bool ShouldSerializesetting() => __pbn__setting != null;
        public void Resetsetting() => __pbn__setting = null;
        private int? __pbn__setting;

        [global::ProtoBuf.ProtoMember(10)]
        public int matchNum
        {
            get { return __pbn__matchNum.GetValueOrDefault(); }
            set { __pbn__matchNum = value; }
        }
        public bool ShouldSerializematchNum() => __pbn__matchNum != null;
        public void ResetmatchNum() => __pbn__matchNum = null;
        private int? __pbn__matchNum;

        [global::ProtoBuf.ProtoMember(11)]
        public int maxAdminNum
        {
            get { return __pbn__maxAdminNum.GetValueOrDefault(); }
            set { __pbn__maxAdminNum = value; }
        }
        public bool ShouldSerializemaxAdminNum() => __pbn__maxAdminNum != null;
        public void ResetmaxAdminNum() => __pbn__maxAdminNum = null;
        private int? __pbn__maxAdminNum;

        [global::ProtoBuf.ProtoMember(12)]
        public int insurancePayMethod
        {
            get { return __pbn__insurancePayMethod.GetValueOrDefault(); }
            set { __pbn__insurancePayMethod = value; }
        }
        public bool ShouldSerializeinsurancePayMethod() => __pbn__insurancePayMethod != null;
        public void ResetinsurancePayMethod() => __pbn__insurancePayMethod = null;
        private int? __pbn__insurancePayMethod;

        [global::ProtoBuf.ProtoMember(13)]
        public long insurancePayLimit
        {
            get { return __pbn__insurancePayLimit.GetValueOrDefault(); }
            set { __pbn__insurancePayLimit = value; }
        }
        public bool ShouldSerializeinsurancePayLimit() => __pbn__insurancePayLimit != null;
        public void ResetinsurancePayLimit() => __pbn__insurancePayLimit = null;
        private long? __pbn__insurancePayLimit;

        [global::ProtoBuf.ProtoMember(14)]
        public long clubBalance
        {
            get { return __pbn__clubBalance.GetValueOrDefault(); }
            set { __pbn__clubBalance = value; }
        }
        public bool ShouldSerializeclubBalance() => __pbn__clubBalance != null;
        public void ResetclubBalance() => __pbn__clubBalance = null;
        private long? __pbn__clubBalance;

        [global::ProtoBuf.ProtoMember(15)]
        public int myLevel
        {
            get { return __pbn__myLevel.GetValueOrDefault(); }
            set { __pbn__myLevel = value; }
        }
        public bool ShouldSerializemyLevel() => __pbn__myLevel != null;
        public void ResetmyLevel() => __pbn__myLevel = null;
        private int? __pbn__myLevel;

        [global::ProtoBuf.ProtoMember(16)]
        public long renameFee
        {
            get { return __pbn__renameFee.GetValueOrDefault(); }
            set { __pbn__renameFee = value; }
        }
        public bool ShouldSerializerenameFee() => __pbn__renameFee != null;
        public void ResetrenameFee() => __pbn__renameFee = null;
        private long? __pbn__renameFee;

        [global::ProtoBuf.ProtoMember(17)]
        public int roomFeeRebateRatio
        {
            get { return __pbn__roomFeeRebateRatio.GetValueOrDefault(); }
            set { __pbn__roomFeeRebateRatio = value; }
        }
        public bool ShouldSerializeroomFeeRebateRatio() => __pbn__roomFeeRebateRatio != null;
        public void ResetroomFeeRebateRatio() => __pbn__roomFeeRebateRatio = null;
        private int? __pbn__roomFeeRebateRatio;

        [global::ProtoBuf.ProtoMember(18)]
        public int insuranceRebateRatio
        {
            get { return __pbn__insuranceRebateRatio.GetValueOrDefault(); }
            set { __pbn__insuranceRebateRatio = value; }
        }
        public bool ShouldSerializeinsuranceRebateRatio() => __pbn__insuranceRebateRatio != null;
        public void ResetinsuranceRebateRatio() => __pbn__insuranceRebateRatio = null;
        private int? __pbn__insuranceRebateRatio;

        [global::ProtoBuf.ProtoMember(19)]
        public int minRoomFeeRebateRatio
        {
            get { return __pbn__minRoomFeeRebateRatio.GetValueOrDefault(); }
            set { __pbn__minRoomFeeRebateRatio = value; }
        }
        public bool ShouldSerializeminRoomFeeRebateRatio() => __pbn__minRoomFeeRebateRatio != null;
        public void ResetminRoomFeeRebateRatio() => __pbn__minRoomFeeRebateRatio = null;
        private int? __pbn__minRoomFeeRebateRatio;

        [global::ProtoBuf.ProtoMember(20)]
        public int maxRoomFeeRebateRatio
        {
            get { return __pbn__maxRoomFeeRebateRatio.GetValueOrDefault(); }
            set { __pbn__maxRoomFeeRebateRatio = value; }
        }
        public bool ShouldSerializemaxRoomFeeRebateRatio() => __pbn__maxRoomFeeRebateRatio != null;
        public void ResetmaxRoomFeeRebateRatio() => __pbn__maxRoomFeeRebateRatio = null;
        private int? __pbn__maxRoomFeeRebateRatio;

        [global::ProtoBuf.ProtoMember(21)]
        public int minInsuranceRebateRatio
        {
            get { return __pbn__minInsuranceRebateRatio.GetValueOrDefault(); }
            set { __pbn__minInsuranceRebateRatio = value; }
        }
        public bool ShouldSerializeminInsuranceRebateRatio() => __pbn__minInsuranceRebateRatio != null;
        public void ResetminInsuranceRebateRatio() => __pbn__minInsuranceRebateRatio = null;
        private int? __pbn__minInsuranceRebateRatio;

        [global::ProtoBuf.ProtoMember(22)]
        public int maxInsuranceRebateRatio
        {
            get { return __pbn__maxInsuranceRebateRatio.GetValueOrDefault(); }
            set { __pbn__maxInsuranceRebateRatio = value; }
        }
        public bool ShouldSerializemaxInsuranceRebateRatio() => __pbn__maxInsuranceRebateRatio != null;
        public void ResetmaxInsuranceRebateRatio() => __pbn__maxInsuranceRebateRatio = null;
        private int? __pbn__maxInsuranceRebateRatio;

        [global::ProtoBuf.ProtoMember(23)]
        public long joinAt
        {
            get { return __pbn__joinAt.GetValueOrDefault(); }
            set { __pbn__joinAt = value; }
        }
        public bool ShouldSerializejoinAt() => __pbn__joinAt != null;
        public void ResetjoinAt() => __pbn__joinAt = null;
        private long? __pbn__joinAt;

        [global::ProtoBuf.ProtoMember(24)]
        public long pkcBalance
        {
            get { return __pbn__pkcBalance.GetValueOrDefault(); }
            set { __pbn__pkcBalance = value; }
        }
        public bool ShouldSerializepkcBalance() => __pbn__pkcBalance != null;
        public void ResetpkcBalance() => __pbn__pkcBalance = null;
        private long? __pbn__pkcBalance;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubUserInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public UserInfo info { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(3)]
        public int sex
        {
            get { return __pbn__sex.GetValueOrDefault(); }
            set { __pbn__sex = value; }
        }
        public bool ShouldSerializesex() => __pbn__sex != null;
        public void Resetsex() => __pbn__sex = null;
        private int? __pbn__sex;

        [global::ProtoBuf.ProtoMember(4)]
        public long loginAt
        {
            get { return __pbn__loginAt.GetValueOrDefault(); }
            set { __pbn__loginAt = value; }
        }
        public bool ShouldSerializeloginAt() => __pbn__loginAt != null;
        public void ResetloginAt() => __pbn__loginAt = null;
        private long? __pbn__loginAt;

        [global::ProtoBuf.ProtoMember(5)]
        public long joinAt
        {
            get { return __pbn__joinAt.GetValueOrDefault(); }
            set { __pbn__joinAt = value; }
        }
        public bool ShouldSerializejoinAt() => __pbn__joinAt != null;
        public void ResetjoinAt() => __pbn__joinAt = null;
        private long? __pbn__joinAt;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string remark
        {
            get { return __pbn__remark ?? ""; }
            set { __pbn__remark = value; }
        }
        public bool ShouldSerializeremark() => __pbn__remark != null;
        public void Resetremark() => __pbn__remark = null;
        private string __pbn__remark;

        [global::ProtoBuf.ProtoMember(7)]
        public long currentCredit
        {
            get { return __pbn__currentCredit.GetValueOrDefault(); }
            set { __pbn__currentCredit = value; }
        }
        public bool ShouldSerializecurrentCredit() => __pbn__currentCredit != null;
        public void ResetcurrentCredit() => __pbn__currentCredit = null;
        private long? __pbn__currentCredit;

        [global::ProtoBuf.ProtoMember(8)]
        public long totalCredit
        {
            get { return __pbn__totalCredit.GetValueOrDefault(); }
            set { __pbn__totalCredit = value; }
        }
        public bool ShouldSerializetotalCredit() => __pbn__totalCredit != null;
        public void ResettotalCredit() => __pbn__totalCredit = null;
        private long? __pbn__totalCredit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionUserInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public UserInfo info { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(3)]
        public long addedAt
        {
            get { return __pbn__addedAt.GetValueOrDefault(); }
            set { __pbn__addedAt = value; }
        }
        public bool ShouldSerializeaddedAt() => __pbn__addedAt != null;
        public void ResetaddedAt() => __pbn__addedAt = null;
        private long? __pbn__addedAt;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ClubUserLevel
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(3)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionAdminLevel
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(3)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(4)]
        public int unionType
        {
            get { return __pbn__unionType.GetValueOrDefault(); }
            set { __pbn__unionType = value; }
        }
        public bool ShouldSerializeunionType() => __pbn__unionType != null;
        public void ResetunionType() => __pbn__unionType = null;
        private int? __pbn__unionType;

        [global::ProtoBuf.ProtoMember(5)]
        public bool createTable
        {
            get { return __pbn__createTable.GetValueOrDefault(); }
            set { __pbn__createTable = value; }
        }
        public bool ShouldSerializecreateTable() => __pbn__createTable != null;
        public void ResetcreateTable() => __pbn__createTable = null;
        private bool? __pbn__createTable;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionType
        {
            get { return __pbn__unionType.GetValueOrDefault(); }
            set { __pbn__unionType = value; }
        }
        public bool ShouldSerializeunionType() => __pbn__unionType != null;
        public void ResetunionType() => __pbn__unionType = null;
        private int? __pbn__unionType;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

        [global::ProtoBuf.ProtoMember(5)]
        public UserInfo ownerInfo { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public long unionBalance
        {
            get { return __pbn__unionBalance.GetValueOrDefault(); }
            set { __pbn__unionBalance = value; }
        }
        public bool ShouldSerializeunionBalance() => __pbn__unionBalance != null;
        public void ResetunionBalance() => __pbn__unionBalance = null;
        private long? __pbn__unionBalance;

        [global::ProtoBuf.ProtoMember(7)]
        public int clubNum
        {
            get { return __pbn__clubNum.GetValueOrDefault(); }
            set { __pbn__clubNum = value; }
        }
        public bool ShouldSerializeclubNum() => __pbn__clubNum != null;
        public void ResetclubNum() => __pbn__clubNum = null;
        private int? __pbn__clubNum;

        [global::ProtoBuf.ProtoMember(8)]
        public int maxAdminNum
        {
            get { return __pbn__maxAdminNum.GetValueOrDefault(); }
            set { __pbn__maxAdminNum = value; }
        }
        public bool ShouldSerializemaxAdminNum() => __pbn__maxAdminNum != null;
        public void ResetmaxAdminNum() => __pbn__maxAdminNum = null;
        private int? __pbn__maxAdminNum;

        [global::ProtoBuf.ProtoMember(9)]
        public int userNum
        {
            get { return __pbn__userNum.GetValueOrDefault(); }
            set { __pbn__userNum = value; }
        }
        public bool ShouldSerializeuserNum() => __pbn__userNum != null;
        public void ResetuserNum() => __pbn__userNum = null;
        private int? __pbn__userNum;

        [global::ProtoBuf.ProtoMember(10)]
        public double todayGain
        {
            get { return __pbn__todayGain.GetValueOrDefault(); }
            set { __pbn__todayGain = value; }
        }
        public bool ShouldSerializetodayGain() => __pbn__todayGain != null;
        public void ResettodayGain() => __pbn__todayGain = null;
        private double? __pbn__todayGain;

        [global::ProtoBuf.ProtoMember(11)]
        public double pastGain
        {
            get { return __pbn__pastGain.GetValueOrDefault(); }
            set { __pbn__pastGain = value; }
        }
        public bool ShouldSerializepastGain() => __pbn__pastGain != null;
        public void ResetpastGain() => __pbn__pastGain = null;
        private double? __pbn__pastGain;

        [global::ProtoBuf.ProtoMember(12)]
        public double notOffered
        {
            get { return __pbn__notOffered.GetValueOrDefault(); }
            set { __pbn__notOffered = value; }
        }
        public bool ShouldSerializenotOffered() => __pbn__notOffered != null;
        public void ResetnotOffered() => __pbn__notOffered = null;
        private double? __pbn__notOffered;

        [global::ProtoBuf.ProtoMember(13)]
        public double notRepaid
        {
            get { return __pbn__notRepaid.GetValueOrDefault(); }
            set { __pbn__notRepaid = value; }
        }
        public bool ShouldSerializenotRepaid() => __pbn__notRepaid != null;
        public void ResetnotRepaid() => __pbn__notRepaid = null;
        private double? __pbn__notRepaid;

        [global::ProtoBuf.ProtoMember(14)]
        public int clubInsuranceProp
        {
            get { return __pbn__clubInsuranceProp.GetValueOrDefault(); }
            set { __pbn__clubInsuranceProp = value; }
        }
        public bool ShouldSerializeclubInsuranceProp() => __pbn__clubInsuranceProp != null;
        public void ResetclubInsuranceProp() => __pbn__clubInsuranceProp = null;
        private int? __pbn__clubInsuranceProp;

        [global::ProtoBuf.ProtoMember(15)]
        public int clubRoomFeeProp
        {
            get { return __pbn__clubRoomFeeProp.GetValueOrDefault(); }
            set { __pbn__clubRoomFeeProp = value; }
        }
        public bool ShouldSerializeclubRoomFeeProp() => __pbn__clubRoomFeeProp != null;
        public void ResetclubRoomFeeProp() => __pbn__clubRoomFeeProp = null;
        private int? __pbn__clubRoomFeeProp;

        [global::ProtoBuf.ProtoMember(16)]
        public int positiveProfitProp
        {
            get { return __pbn__positiveProfitProp.GetValueOrDefault(); }
            set { __pbn__positiveProfitProp = value; }
        }
        public bool ShouldSerializepositiveProfitProp() => __pbn__positiveProfitProp != null;
        public void ResetpositiveProfitProp() => __pbn__positiveProfitProp = null;
        private int? __pbn__positiveProfitProp;

        [global::ProtoBuf.ProtoMember(17)]
        public int negativeProfitProp
        {
            get { return __pbn__negativeProfitProp.GetValueOrDefault(); }
            set { __pbn__negativeProfitProp = value; }
        }
        public bool ShouldSerializenegativeProfitProp() => __pbn__negativeProfitProp != null;
        public void ResetnegativeProfitProp() => __pbn__negativeProfitProp = null;
        private int? __pbn__negativeProfitProp;

        [global::ProtoBuf.ProtoMember(18)]
        public int displayId
        {
            get { return __pbn__displayId.GetValueOrDefault(); }
            set { __pbn__displayId = value; }
        }
        public bool ShouldSerializedisplayId() => __pbn__displayId != null;
        public void ResetdisplayId() => __pbn__displayId = null;
        private int? __pbn__displayId;

        [global::ProtoBuf.ProtoMember(19)]
        public int contributionProp
        {
            get { return __pbn__contributionProp.GetValueOrDefault(); }
            set { __pbn__contributionProp = value; }
        }
        public bool ShouldSerializecontributionProp() => __pbn__contributionProp != null;
        public void ResetcontributionProp() => __pbn__contributionProp = null;
        private int? __pbn__contributionProp;

        [global::ProtoBuf.ProtoMember(20)]
        public long pkcBalance
        {
            get { return __pbn__pkcBalance.GetValueOrDefault(); }
            set { __pbn__pkcBalance = value; }
        }
        public bool ShouldSerializepkcBalance() => __pbn__pkcBalance != null;
        public void ResetpkcBalance() => __pbn__pkcBalance = null;
        private long? __pbn__pkcBalance;

        [global::ProtoBuf.ProtoMember(21)]
        public long pkcTodayGain
        {
            get { return __pbn__pkcTodayGain.GetValueOrDefault(); }
            set { __pbn__pkcTodayGain = value; }
        }
        public bool ShouldSerializepkcTodayGain() => __pbn__pkcTodayGain != null;
        public void ResetpkcTodayGain() => __pbn__pkcTodayGain = null;
        private long? __pbn__pkcTodayGain;

        [global::ProtoBuf.ProtoMember(22)]
        public long pkcPastGain
        {
            get { return __pbn__pkcPastGain.GetValueOrDefault(); }
            set { __pbn__pkcPastGain = value; }
        }
        public bool ShouldSerializepkcPastGain() => __pbn__pkcPastGain != null;
        public void ResetpkcPastGain() => __pbn__pkcPastGain = null;
        private long? __pbn__pkcPastGain;

        [global::ProtoBuf.ProtoMember(23)]
        public long pkcNotOffered
        {
            get { return __pbn__pkcNotOffered.GetValueOrDefault(); }
            set { __pbn__pkcNotOffered = value; }
        }
        public bool ShouldSerializepkcNotOffered() => __pbn__pkcNotOffered != null;
        public void ResetpkcNotOffered() => __pbn__pkcNotOffered = null;
        private long? __pbn__pkcNotOffered;

        [global::ProtoBuf.ProtoMember(24)]
        public long pkcNotRepaid
        {
            get { return __pbn__pkcNotRepaid.GetValueOrDefault(); }
            set { __pbn__pkcNotRepaid = value; }
        }
        public bool ShouldSerializepkcNotRepaid() => __pbn__pkcNotRepaid != null;
        public void ResetpkcNotRepaid() => __pbn__pkcNotRepaid = null;
        private long? __pbn__pkcNotRepaid;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class BillInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int id
        {
            get { return __pbn__id.GetValueOrDefault(); }
            set { __pbn__id = value; }
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private int? __pbn__id;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(4)]
        public long timestamp
        {
            get { return __pbn__timestamp.GetValueOrDefault(); }
            set { __pbn__timestamp = value; }
        }
        public bool ShouldSerializetimestamp() => __pbn__timestamp != null;
        public void Resettimestamp() => __pbn__timestamp = null;
        private long? __pbn__timestamp;

        [global::ProtoBuf.ProtoMember(5)]
        public double amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private double? __pbn__amount;

        [global::ProtoBuf.ProtoMember(6)]
        public double offered
        {
            get { return __pbn__offered.GetValueOrDefault(); }
            set { __pbn__offered = value; }
        }
        public bool ShouldSerializeoffered() => __pbn__offered != null;
        public void Resetoffered() => __pbn__offered = null;
        private double? __pbn__offered;

        [global::ProtoBuf.ProtoMember(7)]
        public double notOffered
        {
            get { return __pbn__notOffered.GetValueOrDefault(); }
            set { __pbn__notOffered = value; }
        }
        public bool ShouldSerializenotOffered() => __pbn__notOffered != null;
        public void ResetnotOffered() => __pbn__notOffered = null;
        private double? __pbn__notOffered;

        [global::ProtoBuf.ProtoMember(8)]
        public double offseted
        {
            get { return __pbn__offseted.GetValueOrDefault(); }
            set { __pbn__offseted = value; }
        }
        public bool ShouldSerializeoffseted() => __pbn__offseted != null;
        public void Resetoffseted() => __pbn__offseted = null;
        private double? __pbn__offseted;

        [global::ProtoBuf.ProtoMember(9)]
        public double repaid
        {
            get { return __pbn__repaid.GetValueOrDefault(); }
            set { __pbn__repaid = value; }
        }
        public bool ShouldSerializerepaid() => __pbn__repaid != null;
        public void Resetrepaid() => __pbn__repaid = null;
        private double? __pbn__repaid;

        [global::ProtoBuf.ProtoMember(10)]
        public double notRepaid
        {
            get { return __pbn__notRepaid.GetValueOrDefault(); }
            set { __pbn__notRepaid = value; }
        }
        public bool ShouldSerializenotRepaid() => __pbn__notRepaid != null;
        public void ResetnotRepaid() => __pbn__notRepaid = null;
        private double? __pbn__notRepaid;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchSummary
    {
        [global::ProtoBuf.ProtoMember(1)]
        public double buyinFeeGain
        {
            get { return __pbn__buyinFeeGain.GetValueOrDefault(); }
            set { __pbn__buyinFeeGain = value; }
        }
        public bool ShouldSerializebuyinFeeGain() => __pbn__buyinFeeGain != null;
        public void ResetbuyinFeeGain() => __pbn__buyinFeeGain = null;
        private double? __pbn__buyinFeeGain;

        [global::ProtoBuf.ProtoMember(2)]
        public double profitFeeGain
        {
            get { return __pbn__profitFeeGain.GetValueOrDefault(); }
            set { __pbn__profitFeeGain = value; }
        }
        public bool ShouldSerializeprofitFeeGain() => __pbn__profitFeeGain != null;
        public void ResetprofitFeeGain() => __pbn__profitFeeGain = null;
        private double? __pbn__profitFeeGain;

        [global::ProtoBuf.ProtoMember(3)]
        public double potFeeGain
        {
            get { return __pbn__potFeeGain.GetValueOrDefault(); }
            set { __pbn__potFeeGain = value; }
        }
        public bool ShouldSerializepotFeeGain() => __pbn__potFeeGain != null;
        public void ResetpotFeeGain() => __pbn__potFeeGain = null;
        private double? __pbn__potFeeGain;

        [global::ProtoBuf.ProtoMember(4)]
        public double insuranceGain
        {
            get { return __pbn__insuranceGain.GetValueOrDefault(); }
            set { __pbn__insuranceGain = value; }
        }
        public bool ShouldSerializeinsuranceGain() => __pbn__insuranceGain != null;
        public void ResetinsuranceGain() => __pbn__insuranceGain = null;
        private double? __pbn__insuranceGain;

        [global::ProtoBuf.ProtoMember(5)]
        public double luckycardGain
        {
            get { return __pbn__luckycardGain.GetValueOrDefault(); }
            set { __pbn__luckycardGain = value; }
        }
        public bool ShouldSerializeluckycardGain() => __pbn__luckycardGain != null;
        public void ResetluckycardGain() => __pbn__luckycardGain = null;
        private double? __pbn__luckycardGain;

        [global::ProtoBuf.ProtoMember(6)]
        public double fishGain
        {
            get { return __pbn__fishGain.GetValueOrDefault(); }
            set { __pbn__fishGain = value; }
        }
        public bool ShouldSerializefishGain() => __pbn__fishGain != null;
        public void ResetfishGain() => __pbn__fishGain = null;
        private double? __pbn__fishGain;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchProfit
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint totalPosProfit
        {
            get { return __pbn__totalPosProfit.GetValueOrDefault(); }
            set { __pbn__totalPosProfit = value; }
        }
        public bool ShouldSerializetotalPosProfit() => __pbn__totalPosProfit != null;
        public void ResettotalPosProfit() => __pbn__totalPosProfit = null;
        private uint? __pbn__totalPosProfit;

        [global::ProtoBuf.ProtoMember(2)]
        public uint totalNegProfit
        {
            get { return __pbn__totalNegProfit.GetValueOrDefault(); }
            set { __pbn__totalNegProfit = value; }
        }
        public bool ShouldSerializetotalNegProfit() => __pbn__totalNegProfit != null;
        public void ResettotalNegProfit() => __pbn__totalNegProfit = null;
        private uint? __pbn__totalNegProfit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class VpipConf
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint vpip
        {
            get { return __pbn__vpip.GetValueOrDefault(); }
            set { __pbn__vpip = value; }
        }
        public bool ShouldSerializevpip() => __pbn__vpip != null;
        public void Resetvpip() => __pbn__vpip = null;
        private uint? __pbn__vpip;

        [global::ProtoBuf.ProtoMember(2)]
        public uint penaltyRate
        {
            get { return __pbn__penaltyRate.GetValueOrDefault(); }
            set { __pbn__penaltyRate = value; }
        }
        public bool ShouldSerializepenaltyRate() => __pbn__penaltyRate != null;
        public void ResetpenaltyRate() => __pbn__penaltyRate = null;
        private uint? __pbn__penaltyRate;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum PBMatchType
    {
        MatchTypeOfficalCash = 1,
        MatchTypeUserCreateCash = 2,
        MatchTypeOfficalSNG = 3,
        MatchTypeUserCreateSNG = 4,
        MatchTypeHunTexas = 5,
        MatchTypeOfficialExercise = 101,
        MatchTypeUserCreateExercise = 102,
        MatchTypeUserCreatePoint = 202,
        MatchTypeUserCreatePKC = 302,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum MSGTYPE
    {
        HEARTBEAT = 0,
        REQUEST = 1,
        RESPONSE = 2,
        NOTIFY = 3,
        PUSH = 4,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum joinOption
    {
        agree = 1,
        refuse = 2,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum userLevel
    {
        owner = 100,
        admin = 10,
        member = 1,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum editInfoType
    {
        editIcon = 1,
        editName = 2,
        editDesc = 3,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum unionTypeDef
    {
        superUnion = 1,
        union = 2,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum UserGuideMark
    {
        texas = 1,
        fish = 2,
        list = 3,
        wallet = 4,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
