// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: faceRecognition.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetBizTokenReq
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private int? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string imgUrl
        {
            get { return __pbn__imgUrl ?? ""; }
            set { __pbn__imgUrl = value; }
        }
        public bool ShouldSerializeimgUrl() => __pbn__imgUrl != null;
        public void ResetimgUrl() => __pbn__imgUrl = null;
        private string __pbn__imgUrl;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetBizTokenRsp
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int httpCode { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string error
        {
            get { return __pbn__error ?? ""; }
            set { __pbn__error = value; }
        }
        public bool ShouldSerializeerror() => __pbn__error != null;
        public void Reseterror() => __pbn__error = null;
        private string __pbn__error;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string token
        {
            get { return __pbn__token ?? ""; }
            set { __pbn__token = value; }
        }
        public bool ShouldSerializetoken() => __pbn__token != null;
        public void Resettoken() => __pbn__token = null;
        private string __pbn__token;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class VerifyReq
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private int? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string data { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string token { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class VerifyRsp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int httpCode
        {
            get { return __pbn__httpCode.GetValueOrDefault(); }
            set { __pbn__httpCode = value; }
        }
        public bool ShouldSerializehttpCode() => __pbn__httpCode != null;
        public void ResethttpCode() => __pbn__httpCode = null;
        private int? __pbn__httpCode;

        [global::ProtoBuf.ProtoMember(2)]
        public int verifyCode
        {
            get { return __pbn__verifyCode.GetValueOrDefault(); }
            set { __pbn__verifyCode = value; }
        }
        public bool ShouldSerializeverifyCode() => __pbn__verifyCode != null;
        public void ResetverifyCode() => __pbn__verifyCode = null;
        private int? __pbn__verifyCode;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string message
        {
            get { return __pbn__message ?? ""; }
            set { __pbn__message = value; }
        }
        public bool ShouldSerializemessage() => __pbn__message != null;
        public void Resetmessage() => __pbn__message = null;
        private string __pbn__message;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string continuousFailLimit
        {
            get { return __pbn__continuousFailLimit ?? ""; }
            set { __pbn__continuousFailLimit = value; }
        }
        public bool ShouldSerializecontinuousFailLimit() => __pbn__continuousFailLimit != null;
        public void ResetcontinuousFailLimit() => __pbn__continuousFailLimit = null;
        private string __pbn__continuousFailLimit;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currentContinuousFailCount
        {
            get { return __pbn__currentContinuousFailCount ?? ""; }
            set { __pbn__currentContinuousFailCount = value; }
        }
        public bool ShouldSerializecurrentContinuousFailCount() => __pbn__currentContinuousFailCount != null;
        public void ResetcurrentContinuousFailCount() => __pbn__currentContinuousFailCount = null;
        private string __pbn__currentContinuousFailCount;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalFailLimit
        {
            get { return __pbn__totalFailLimit ?? ""; }
            set { __pbn__totalFailLimit = value; }
        }
        public bool ShouldSerializetotalFailLimit() => __pbn__totalFailLimit != null;
        public void ResettotalFailLimit() => __pbn__totalFailLimit = null;
        private string __pbn__totalFailLimit;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currentTotalFailCount
        {
            get { return __pbn__currentTotalFailCount ?? ""; }
            set { __pbn__currentTotalFailCount = value; }
        }
        public bool ShouldSerializecurrentTotalFailCount() => __pbn__currentTotalFailCount != null;
        public void ResetcurrentTotalFailCount() => __pbn__currentTotalFailCount = null;
        private string __pbn__currentTotalFailCount;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnbindReq
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int uid { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnbindRsp
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int status { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class VIPInfoReq
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int uid { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class VIPInfoRsp
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int state { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public bool isNeverBind { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string firstBindBounsHand { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public string firstBindBonusMoney { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public string vipMatchLuckyCardHitBounsRatio { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public string generalMatchVipPlayerLuckyCardHitBounsRatio { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public string unbindDeductionMoney { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public string dailyTransLimit { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class TimeLimitedWelfareRep
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int uid { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class TimeLimitedWelfareRsp
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public bool @switch { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string hands { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string bonus { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string befores
        {
            get { return __pbn__befores ?? ""; }
            set { __pbn__befores = value; }
        }
        public bool ShouldSerializebefores() => __pbn__befores != null;
        public void Resetbefores() => __pbn__befores = null;
        private string __pbn__befores;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CancelVerifyReq
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private int? __pbn__mid;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CancelVerifyRsp
    {
        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string continuousFailLimit
        {
            get { return __pbn__continuousFailLimit ?? ""; }
            set { __pbn__continuousFailLimit = value; }
        }
        public bool ShouldSerializecontinuousFailLimit() => __pbn__continuousFailLimit != null;
        public void ResetcontinuousFailLimit() => __pbn__continuousFailLimit = null;
        private string __pbn__continuousFailLimit;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currentContinuousFailCount
        {
            get { return __pbn__currentContinuousFailCount ?? ""; }
            set { __pbn__currentContinuousFailCount = value; }
        }
        public bool ShouldSerializecurrentContinuousFailCount() => __pbn__currentContinuousFailCount != null;
        public void ResetcurrentContinuousFailCount() => __pbn__currentContinuousFailCount = null;
        private string __pbn__currentContinuousFailCount;

        [global::ProtoBuf.ProtoMember(6)]
        [global::System.ComponentModel.DefaultValue("")]
        public string totalFailLimit
        {
            get { return __pbn__totalFailLimit ?? ""; }
            set { __pbn__totalFailLimit = value; }
        }
        public bool ShouldSerializetotalFailLimit() => __pbn__totalFailLimit != null;
        public void ResettotalFailLimit() => __pbn__totalFailLimit = null;
        private string __pbn__totalFailLimit;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string currentTotalFailCount
        {
            get { return __pbn__currentTotalFailCount ?? ""; }
            set { __pbn__currentTotalFailCount = value; }
        }
        public bool ShouldSerializecurrentTotalFailCount() => __pbn__currentTotalFailCount != null;
        public void ResetcurrentTotalFailCount() => __pbn__currentTotalFailCount = null;
        private string __pbn__currentTotalFailCount;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum FaceRecognition
    {
        getBizTokenReq = 1,
        getBizTokenRsp = 2,
        verifyReq = 3,
        verifyRsp = 4,
        unbindReq = 5,
        unbindRsp = 6,
        vipInfoReq = 7,
        vipInfoRsp = 8,
        timeLimitedWelfareRep = 9,
        timeLimitedWelfareRsp = 10,
        cancelVerifyReq = 11,
        cancelVerifyRsp = 12,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
