// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: matchMgr.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PotFeeConf
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint rate
        {
            get { return __pbn__rate.GetValueOrDefault(); }
            set { __pbn__rate = value; }
        }
        public bool ShouldSerializerate() => __pbn__rate != null;
        public void Resetrate() => __pbn__rate = null;
        private uint? __pbn__rate;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong handLimit
        {
            get { return __pbn__handLimit.GetValueOrDefault(); }
            set { __pbn__handLimit = value; }
        }
        public bool ShouldSerializehandLimit() => __pbn__handLimit != null;
        public void ResethandLimit() => __pbn__handLimit = null;
        private ulong? __pbn__handLimit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RoomFeeConf
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint buyInFeeRate
        {
            get { return __pbn__buyInFeeRate.GetValueOrDefault(); }
            set { __pbn__buyInFeeRate = value; }
        }
        public bool ShouldSerializebuyInFeeRate() => __pbn__buyInFeeRate != null;
        public void ResetbuyInFeeRate() => __pbn__buyInFeeRate = null;
        private uint? __pbn__buyInFeeRate;

        [global::ProtoBuf.ProtoMember(2)]
        public uint profitFeeRate
        {
            get { return __pbn__profitFeeRate.GetValueOrDefault(); }
            set { __pbn__profitFeeRate = value; }
        }
        public bool ShouldSerializeprofitFeeRate() => __pbn__profitFeeRate != null;
        public void ResetprofitFeeRate() => __pbn__profitFeeRate = null;
        private uint? __pbn__profitFeeRate;

        [global::ProtoBuf.ProtoMember(3)]
        public PotFeeConf potFeeConf { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RoomFeeNum
    {
        [global::ProtoBuf.ProtoMember(1)]
        public ulong buyInFeeNum
        {
            get { return __pbn__buyInFeeNum.GetValueOrDefault(); }
            set { __pbn__buyInFeeNum = value; }
        }
        public bool ShouldSerializebuyInFeeNum() => __pbn__buyInFeeNum != null;
        public void ResetbuyInFeeNum() => __pbn__buyInFeeNum = null;
        private ulong? __pbn__buyInFeeNum;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong profitFeeNum
        {
            get { return __pbn__profitFeeNum.GetValueOrDefault(); }
            set { __pbn__profitFeeNum = value; }
        }
        public bool ShouldSerializeprofitFeeNum() => __pbn__profitFeeNum != null;
        public void ResetprofitFeeNum() => __pbn__profitFeeNum = null;
        private ulong? __pbn__profitFeeNum;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong potFeeNum
        {
            get { return __pbn__potFeeNum.GetValueOrDefault(); }
            set { __pbn__potFeeNum = value; }
        }
        public bool ShouldSerializepotFeeNum() => __pbn__potFeeNum != null;
        public void ResetpotFeeNum() => __pbn__potFeeNum = null;
        private ulong? __pbn__potFeeNum;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchProp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int category
        {
            get { return __pbn__category.GetValueOrDefault(); }
            set { __pbn__category = value; }
        }
        public bool ShouldSerializecategory() => __pbn__category != null;
        public void Resetcategory() => __pbn__category = null;
        private int? __pbn__category;

        [global::ProtoBuf.ProtoMember(2)]
        public uint createUID
        {
            get { return __pbn__createUID.GetValueOrDefault(); }
            set { __pbn__createUID = value; }
        }
        public bool ShouldSerializecreateUID() => __pbn__createUID != null;
        public void ResetcreateUID() => __pbn__createUID = null;
        private uint? __pbn__createUID;

        [global::ProtoBuf.ProtoMember(3)]
        public uint clubID
        {
            get { return __pbn__clubID.GetValueOrDefault(); }
            set { __pbn__clubID = value; }
        }
        public bool ShouldSerializeclubID() => __pbn__clubID != null;
        public void ResetclubID() => __pbn__clubID = null;
        private uint? __pbn__clubID;

        [global::ProtoBuf.ProtoMember(4)]
        public uint unionID
        {
            get { return __pbn__unionID.GetValueOrDefault(); }
            set { __pbn__unionID = value; }
        }
        public bool ShouldSerializeunionID() => __pbn__unionID != null;
        public void ResetunionID() => __pbn__unionID = null;
        private uint? __pbn__unionID;

        [global::ProtoBuf.ProtoMember(5)]
        public uint roomID
        {
            get { return __pbn__roomID.GetValueOrDefault(); }
            set { __pbn__roomID = value; }
        }
        public bool ShouldSerializeroomID() => __pbn__roomID != null;
        public void ResetroomID() => __pbn__roomID = null;
        private uint? __pbn__roomID;

        [global::ProtoBuf.ProtoMember(6)]
        public uint matchLevel
        {
            get { return __pbn__matchLevel.GetValueOrDefault(); }
            set { __pbn__matchLevel = value; }
        }
        public bool ShouldSerializematchLevel() => __pbn__matchLevel != null;
        public void ResetmatchLevel() => __pbn__matchLevel = null;
        private uint? __pbn__matchLevel;

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clubName
        {
            get { return __pbn__clubName ?? ""; }
            set { __pbn__clubName = value; }
        }
        public bool ShouldSerializeclubName() => __pbn__clubName != null;
        public void ResetclubName() => __pbn__clubName = null;
        private string __pbn__clubName;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clubIcon
        {
            get { return __pbn__clubIcon ?? ""; }
            set { __pbn__clubIcon = value; }
        }
        public bool ShouldSerializeclubIcon() => __pbn__clubIcon != null;
        public void ResetclubIcon() => __pbn__clubIcon = null;
        private string __pbn__clubIcon;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string creatorIcon
        {
            get { return __pbn__creatorIcon ?? ""; }
            set { __pbn__creatorIcon = value; }
        }
        public bool ShouldSerializecreatorIcon() => __pbn__creatorIcon != null;
        public void ResetcreatorIcon() => __pbn__creatorIcon = null;
        private string __pbn__creatorIcon;

        [global::ProtoBuf.ProtoMember(10)]
        public bool entered
        {
            get { return __pbn__entered.GetValueOrDefault(); }
            set { __pbn__entered = value; }
        }
        public bool ShouldSerializeentered() => __pbn__entered != null;
        public void Resetentered() => __pbn__entered = null;
        private bool? __pbn__entered;

        [global::ProtoBuf.ProtoMember(11)]
        public bool settled
        {
            get { return __pbn__settled.GetValueOrDefault(); }
            set { __pbn__settled = value; }
        }
        public bool ShouldSerializesettled() => __pbn__settled != null;
        public void Resetsettled() => __pbn__settled = null;
        private bool? __pbn__settled;

        [global::ProtoBuf.ProtoMember(12)]
        public uint totalBuyIn
        {
            get { return __pbn__totalBuyIn.GetValueOrDefault(); }
            set { __pbn__totalBuyIn = value; }
        }
        public bool ShouldSerializetotalBuyIn() => __pbn__totalBuyIn != null;
        public void ResettotalBuyIn() => __pbn__totalBuyIn = null;
        private uint? __pbn__totalBuyIn;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ante
        {
            get { return __pbn__ante.GetValueOrDefault(); }
            set { __pbn__ante = value; }
        }
        public bool ShouldSerializeante() => __pbn__ante != null;
        public void Resetante() => __pbn__ante = null;
        private ulong? __pbn__ante;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong sb
        {
            get { return __pbn__sb.GetValueOrDefault(); }
            set { __pbn__sb = value; }
        }
        public bool ShouldSerializesb() => __pbn__sb != null;
        public void Resetsb() => __pbn__sb = null;
        private ulong? __pbn__sb;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong bb
        {
            get { return __pbn__bb.GetValueOrDefault(); }
            set { __pbn__bb = value; }
        }
        public bool ShouldSerializebb() => __pbn__bb != null;
        public void Resetbb() => __pbn__bb = null;
        private ulong? __pbn__bb;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong minCarry
        {
            get { return __pbn__minCarry.GetValueOrDefault(); }
            set { __pbn__minCarry = value; }
        }
        public bool ShouldSerializeminCarry() => __pbn__minCarry != null;
        public void ResetminCarry() => __pbn__minCarry = null;
        private ulong? __pbn__minCarry;

        [global::ProtoBuf.ProtoMember(6)]
        public ulong maxCarry
        {
            get { return __pbn__maxCarry.GetValueOrDefault(); }
            set { __pbn__maxCarry = value; }
        }
        public bool ShouldSerializemaxCarry() => __pbn__maxCarry != null;
        public void ResetmaxCarry() => __pbn__maxCarry = null;
        private ulong? __pbn__maxCarry;

        [global::ProtoBuf.ProtoMember(7)]
        public uint seatNum
        {
            get { return __pbn__seatNum.GetValueOrDefault(); }
            set { __pbn__seatNum = value; }
        }
        public bool ShouldSerializeseatNum() => __pbn__seatNum != null;
        public void ResetseatNum() => __pbn__seatNum = null;
        private uint? __pbn__seatNum;

        [global::ProtoBuf.ProtoMember(8)]
        public int actionTime
        {
            get { return __pbn__actionTime.GetValueOrDefault(); }
            set { __pbn__actionTime = value; }
        }
        public bool ShouldSerializeactionTime() => __pbn__actionTime != null;
        public void ResetactionTime() => __pbn__actionTime = null;
        private int? __pbn__actionTime;

        [global::ProtoBuf.ProtoMember(9)]
        public bool straddle
        {
            get { return __pbn__straddle.GetValueOrDefault(); }
            set { __pbn__straddle = value; }
        }
        public bool ShouldSerializestraddle() => __pbn__straddle != null;
        public void Resetstraddle() => __pbn__straddle = null;
        private bool? __pbn__straddle;

        [global::ProtoBuf.ProtoMember(10)]
        public bool gpsLimit
        {
            get { return __pbn__gpsLimit.GetValueOrDefault(); }
            set { __pbn__gpsLimit = value; }
        }
        public bool ShouldSerializegpsLimit() => __pbn__gpsLimit != null;
        public void ResetgpsLimit() => __pbn__gpsLimit = null;
        private bool? __pbn__gpsLimit;

        [global::ProtoBuf.ProtoMember(11)]
        public bool ipLimit
        {
            get { return __pbn__ipLimit.GetValueOrDefault(); }
            set { __pbn__ipLimit = value; }
        }
        public bool ShouldSerializeipLimit() => __pbn__ipLimit != null;
        public void ResetipLimit() => __pbn__ipLimit = null;
        private bool? __pbn__ipLimit;

        [global::ProtoBuf.ProtoMember(12)]
        public bool insurance
        {
            get { return __pbn__insurance.GetValueOrDefault(); }
            set { __pbn__insurance = value; }
        }
        public bool ShouldSerializeinsurance() => __pbn__insurance != null;
        public void Resetinsurance() => __pbn__insurance = null;
        private bool? __pbn__insurance;

        [global::ProtoBuf.ProtoMember(13)]
        public bool showAllHands
        {
            get { return __pbn__showAllHands.GetValueOrDefault(); }
            set { __pbn__showAllHands = value; }
        }
        public bool ShouldSerializeshowAllHands() => __pbn__showAllHands != null;
        public void ResetshowAllHands() => __pbn__showAllHands = null;
        private bool? __pbn__showAllHands;

        [global::ProtoBuf.ProtoMember(14)]
        public uint matchTime
        {
            get { return __pbn__matchTime.GetValueOrDefault(); }
            set { __pbn__matchTime = value; }
        }
        public bool ShouldSerializematchTime() => __pbn__matchTime != null;
        public void ResetmatchTime() => __pbn__matchTime = null;
        private uint? __pbn__matchTime;

        [global::ProtoBuf.ProtoMember(15)]
        public uint startTime
        {
            get { return __pbn__startTime.GetValueOrDefault(); }
            set { __pbn__startTime = value; }
        }
        public bool ShouldSerializestartTime() => __pbn__startTime != null;
        public void ResetstartTime() => __pbn__startTime = null;
        private uint? __pbn__startTime;

        [global::ProtoBuf.ProtoMember(16)]
        public uint remainTime
        {
            get { return __pbn__remainTime.GetValueOrDefault(); }
            set { __pbn__remainTime = value; }
        }
        public bool ShouldSerializeremainTime() => __pbn__remainTime != null;
        public void ResetremainTime() => __pbn__remainTime = null;
        private uint? __pbn__remainTime;

        [global::ProtoBuf.ProtoMember(17)]
        public uint pnum
        {
            get { return __pbn__pnum.GetValueOrDefault(); }
            set { __pbn__pnum = value; }
        }
        public bool ShouldSerializepnum() => __pbn__pnum != null;
        public void Resetpnum() => __pbn__pnum = null;
        private uint? __pbn__pnum;

        [global::ProtoBuf.ProtoMember(18)]
        public MatchProp prop { get; set; }

        [global::ProtoBuf.ProtoMember(19)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(20)]
        public bool friendLimit
        {
            get { return __pbn__friendLimit.GetValueOrDefault(); }
            set { __pbn__friendLimit = value; }
        }
        public bool ShouldSerializefriendLimit() => __pbn__friendLimit != null;
        public void ResetfriendLimit() => __pbn__friendLimit = null;
        private bool? __pbn__friendLimit;

        [global::ProtoBuf.ProtoMember(21)]
        public bool luckyCard
        {
            get { return __pbn__luckyCard.GetValueOrDefault(); }
            set { __pbn__luckyCard = value; }
        }
        public bool ShouldSerializeluckyCard() => __pbn__luckyCard != null;
        public void ResetluckyCard() => __pbn__luckyCard = null;
        private bool? __pbn__luckyCard;

        [global::ProtoBuf.ProtoMember(22)]
        public bool closeChat
        {
            get { return __pbn__closeChat.GetValueOrDefault(); }
            set { __pbn__closeChat = value; }
        }
        public bool ShouldSerializecloseChat() => __pbn__closeChat != null;
        public void ResetcloseChat() => __pbn__closeChat = null;
        private bool? __pbn__closeChat;

        [global::ProtoBuf.ProtoMember(23)]
        public VpipConf vpipConf { get; set; }

        [global::ProtoBuf.ProtoMember(24)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

        [global::ProtoBuf.ProtoMember(25)]
        public uint unloadTimes
        {
            get { return __pbn__unloadTimes.GetValueOrDefault(); }
            set { __pbn__unloadTimes = value; }
        }
        public bool ShouldSerializeunloadTimes() => __pbn__unloadTimes != null;
        public void ResetunloadTimes() => __pbn__unloadTimes = null;
        private uint? __pbn__unloadTimes;

        [global::ProtoBuf.ProtoMember(26)]
        public long createTime
        {
            get { return __pbn__createTime.GetValueOrDefault(); }
            set { __pbn__createTime = value; }
        }
        public bool ShouldSerializecreateTime() => __pbn__createTime != null;
        public void ResetcreateTime() => __pbn__createTime = null;
        private long? __pbn__createTime;

        [global::ProtoBuf.ProtoMember(27)]
        public int autoEndTime
        {
            get { return __pbn__autoEndTime.GetValueOrDefault(); }
            set { __pbn__autoEndTime = value; }
        }
        public bool ShouldSerializeautoEndTime() => __pbn__autoEndTime != null;
        public void ResetautoEndTime() => __pbn__autoEndTime = null;
        private int? __pbn__autoEndTime;

        [global::ProtoBuf.ProtoMember(28)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

        [global::ProtoBuf.ProtoMember(29)]
        public bool faceVip
        {
            get { return __pbn__faceVip.GetValueOrDefault(); }
            set { __pbn__faceVip = value; }
        }
        public bool ShouldSerializefaceVip() => __pbn__faceVip != null;
        public void ResetfaceVip() => __pbn__faceVip = null;
        private bool? __pbn__faceVip;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PlayerBalance
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint uid
        {
            get { return __pbn__uid.GetValueOrDefault(); }
            set { __pbn__uid = value; }
        }
        public bool ShouldSerializeuid() => __pbn__uid != null;
        public void Resetuid() => __pbn__uid = null;
        private uint? __pbn__uid;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong buyin
        {
            get { return __pbn__buyin.GetValueOrDefault(); }
            set { __pbn__buyin = value; }
        }
        public bool ShouldSerializebuyin() => __pbn__buyin != null;
        public void Resetbuyin() => __pbn__buyin = null;
        private ulong? __pbn__buyin;

        [global::ProtoBuf.ProtoMember(3)]
        public long balance
        {
            get { return __pbn__balance.GetValueOrDefault(); }
            set { __pbn__balance = value; }
        }
        public bool ShouldSerializebalance() => __pbn__balance != null;
        public void Resetbalance() => __pbn__balance = null;
        private long? __pbn__balance;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientDefine
        {
            get { return __pbn__clientDefine ?? ""; }
            set { __pbn__clientDefine = value; }
        }
        public bool ShouldSerializeclientDefine() => __pbn__clientDefine != null;
        public void ResetclientDefine() => __pbn__clientDefine = null;
        private string __pbn__clientDefine;

        [global::ProtoBuf.ProtoMember(5)]
        public bool isStanding
        {
            get { return __pbn__isStanding.GetValueOrDefault(); }
            set { __pbn__isStanding = value; }
        }
        public bool ShouldSerializeisStanding() => __pbn__isStanding != null;
        public void ResetisStanding() => __pbn__isStanding = null;
        private bool? __pbn__isStanding;

        [global::ProtoBuf.ProtoMember(6)]
        public bool settled
        {
            get { return __pbn__settled.GetValueOrDefault(); }
            set { __pbn__settled = value; }
        }
        public bool ShouldSerializesettled() => __pbn__settled != null;
        public void Resetsettled() => __pbn__settled = null;
        private bool? __pbn__settled;

        [global::ProtoBuf.ProtoMember(7)]
        public uint vpip
        {
            get { return __pbn__vpip.GetValueOrDefault(); }
            set { __pbn__vpip = value; }
        }
        public bool ShouldSerializevpip() => __pbn__vpip != null;
        public void Resetvpip() => __pbn__vpip = null;
        private uint? __pbn__vpip;

        [global::ProtoBuf.ProtoMember(8)]
        public uint handCount
        {
            get { return __pbn__handCount.GetValueOrDefault(); }
            set { __pbn__handCount = value; }
        }
        public bool ShouldSerializehandCount() => __pbn__handCount != null;
        public void ResethandCount() => __pbn__handCount = null;
        private uint? __pbn__handCount;

        [global::ProtoBuf.ProtoMember(9)]
        public long adjusted
        {
            get { return __pbn__adjusted.GetValueOrDefault(); }
            set { __pbn__adjusted = value; }
        }
        public bool ShouldSerializeadjusted() => __pbn__adjusted != null;
        public void Resetadjusted() => __pbn__adjusted = null;
        private long? __pbn__adjusted;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class Deposit
    {
        [global::ProtoBuf.ProtoMember(1)]
        public ulong buyin
        {
            get { return __pbn__buyin.GetValueOrDefault(); }
            set { __pbn__buyin = value; }
        }
        public bool ShouldSerializebuyin() => __pbn__buyin != null;
        public void Resetbuyin() => __pbn__buyin = null;
        private ulong? __pbn__buyin;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong num
        {
            get { return __pbn__num.GetValueOrDefault(); }
            set { __pbn__num = value; }
        }
        public bool ShouldSerializenum() => __pbn__num != null;
        public void Resetnum() => __pbn__num = null;
        private ulong? __pbn__num;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class InsuranceBalance
    {
        [global::ProtoBuf.ProtoMember(1)]
        public long total
        {
            get { return __pbn__total.GetValueOrDefault(); }
            set { __pbn__total = value; }
        }
        public bool ShouldSerializetotal() => __pbn__total != null;
        public void Resettotal() => __pbn__total = null;
        private long? __pbn__total;

        [global::ProtoBuf.ProtoMember(2)]
        public long sys
        {
            get { return __pbn__sys.GetValueOrDefault(); }
            set { __pbn__sys = value; }
        }
        public bool ShouldSerializesys() => __pbn__sys != null;
        public void Resetsys() => __pbn__sys = null;
        private long? __pbn__sys;

        [global::ProtoBuf.ProtoMember(3)]
        public long adqq
        {
            get { return __pbn__adqq.GetValueOrDefault(); }
            set { __pbn__adqq = value; }
        }
        public bool ShouldSerializeadqq() => __pbn__adqq != null;
        public void Resetadqq() => __pbn__adqq = null;
        private long? __pbn__adqq;

        [global::ProtoBuf.ProtoMember(4)]
        public Deposit deposit { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class Blinds
    {
        [global::ProtoBuf.ProtoMember(1)]
        public ulong sb
        {
            get { return __pbn__sb.GetValueOrDefault(); }
            set { __pbn__sb = value; }
        }
        public bool ShouldSerializesb() => __pbn__sb != null;
        public void Resetsb() => __pbn__sb = null;
        private ulong? __pbn__sb;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong bb
        {
            get { return __pbn__bb.GetValueOrDefault(); }
            set { __pbn__bb = value; }
        }
        public bool ShouldSerializebb() => __pbn__bb != null;
        public void Resetbb() => __pbn__bb = null;
        private ulong? __pbn__bb;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong[] antes { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class DefaultArgs
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint matchTime
        {
            get { return __pbn__matchTime.GetValueOrDefault(); }
            set { __pbn__matchTime = value; }
        }
        public bool ShouldSerializematchTime() => __pbn__matchTime != null;
        public void ResetmatchTime() => __pbn__matchTime = null;
        private uint? __pbn__matchTime;

        [global::ProtoBuf.ProtoMember(2)]
        public uint buyinMin
        {
            get { return __pbn__buyinMin.GetValueOrDefault(); }
            set { __pbn__buyinMin = value; }
        }
        public bool ShouldSerializebuyinMin() => __pbn__buyinMin != null;
        public void ResetbuyinMin() => __pbn__buyinMin = null;
        private uint? __pbn__buyinMin;

        [global::ProtoBuf.ProtoMember(3)]
        public uint buyinMax
        {
            get { return __pbn__buyinMax.GetValueOrDefault(); }
            set { __pbn__buyinMax = value; }
        }
        public bool ShouldSerializebuyinMax() => __pbn__buyinMax != null;
        public void ResetbuyinMax() => __pbn__buyinMax = null;
        private uint? __pbn__buyinMax;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong sb
        {
            get { return __pbn__sb.GetValueOrDefault(); }
            set { __pbn__sb = value; }
        }
        public bool ShouldSerializesb() => __pbn__sb != null;
        public void Resetsb() => __pbn__sb = null;
        private ulong? __pbn__sb;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong bb
        {
            get { return __pbn__bb.GetValueOrDefault(); }
            set { __pbn__bb = value; }
        }
        public bool ShouldSerializebb() => __pbn__bb != null;
        public void Resetbb() => __pbn__bb = null;
        private ulong? __pbn__bb;

        [global::ProtoBuf.ProtoMember(6)]
        public ulong ante
        {
            get { return __pbn__ante.GetValueOrDefault(); }
            set { __pbn__ante = value; }
        }
        public bool ShouldSerializeante() => __pbn__ante != null;
        public void Resetante() => __pbn__ante = null;
        private ulong? __pbn__ante;

        [global::ProtoBuf.ProtoMember(7)]
        public uint actionTime
        {
            get { return __pbn__actionTime.GetValueOrDefault(); }
            set { __pbn__actionTime = value; }
        }
        public bool ShouldSerializeactionTime() => __pbn__actionTime != null;
        public void ResetactionTime() => __pbn__actionTime = null;
        private uint? __pbn__actionTime;

        [global::ProtoBuf.ProtoMember(8)]
        public uint buyInFeeRate
        {
            get { return __pbn__buyInFeeRate.GetValueOrDefault(); }
            set { __pbn__buyInFeeRate = value; }
        }
        public bool ShouldSerializebuyInFeeRate() => __pbn__buyInFeeRate != null;
        public void ResetbuyInFeeRate() => __pbn__buyInFeeRate = null;
        private uint? __pbn__buyInFeeRate;

        [global::ProtoBuf.ProtoMember(9)]
        public uint profitFeeRate
        {
            get { return __pbn__profitFeeRate.GetValueOrDefault(); }
            set { __pbn__profitFeeRate = value; }
        }
        public bool ShouldSerializeprofitFeeRate() => __pbn__profitFeeRate != null;
        public void ResetprofitFeeRate() => __pbn__profitFeeRate = null;
        private uint? __pbn__profitFeeRate;

        [global::ProtoBuf.ProtoMember(10)]
        public uint potFeeRate
        {
            get { return __pbn__potFeeRate.GetValueOrDefault(); }
            set { __pbn__potFeeRate = value; }
        }
        public bool ShouldSerializepotFeeRate() => __pbn__potFeeRate != null;
        public void ResetpotFeeRate() => __pbn__potFeeRate = null;
        private uint? __pbn__potFeeRate;

        [global::ProtoBuf.ProtoMember(11)]
        public uint vpip
        {
            get { return __pbn__vpip.GetValueOrDefault(); }
            set { __pbn__vpip = value; }
        }
        public bool ShouldSerializevpip() => __pbn__vpip != null;
        public void Resetvpip() => __pbn__vpip = null;
        private uint? __pbn__vpip;

        [global::ProtoBuf.ProtoMember(12)]
        public uint penaltyRate
        {
            get { return __pbn__penaltyRate.GetValueOrDefault(); }
            set { __pbn__penaltyRate = value; }
        }
        public bool ShouldSerializepenaltyRate() => __pbn__penaltyRate != null;
        public void ResetpenaltyRate() => __pbn__penaltyRate = null;
        private uint? __pbn__penaltyRate;

        [global::ProtoBuf.ProtoMember(13)]
        public ulong shortAnte
        {
            get { return __pbn__shortAnte.GetValueOrDefault(); }
            set { __pbn__shortAnte = value; }
        }
        public bool ShouldSerializeshortAnte() => __pbn__shortAnte != null;
        public void ResetshortAnte() => __pbn__shortAnte = null;
        private ulong? __pbn__shortAnte;

        [global::ProtoBuf.ProtoMember(14)]
        public uint unloadTimes
        {
            get { return __pbn__unloadTimes.GetValueOrDefault(); }
            set { __pbn__unloadTimes = value; }
        }
        public bool ShouldSerializeunloadTimes() => __pbn__unloadTimes != null;
        public void ResetunloadTimes() => __pbn__unloadTimes = null;
        private uint? __pbn__unloadTimes;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchConfig
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint[] matchTimes { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint[] buyins { get; set; }

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.Blinds")]
        public global::System.Collections.Generic.List<Blinds> blinds { get; } = new global::System.Collections.Generic.List<Blinds>();

        [global::ProtoBuf.ProtoMember(4)]
        public uint[] actionTimes { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint[] buyInFeeRates { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint[] profitFeeRates { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public uint[] potFeeRates { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public uint[] potFeeHandLimitSbs { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public DefaultArgs @default { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public uint[] texasUserNums { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public uint[] shortUserNums { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public uint[] vpips { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public uint[] penaltyRates { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public uint[] potFeeHandLimitAntes { get; set; }

        [global::ProtoBuf.ProtoMember(15)]
        public ulong[] shortAntes { get; set; }

        [global::ProtoBuf.ProtoMember(16)]
        public uint[] unloadTimes { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetMatchConfigReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint ver
        {
            get { return __pbn__ver.GetValueOrDefault(); }
            set { __pbn__ver = value; }
        }
        public bool ShouldSerializever() => __pbn__ver != null;
        public void Resetver() => __pbn__ver = null;
        private uint? __pbn__ver;

        [global::ProtoBuf.ProtoMember(2)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetMatchConfigResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint ver
        {
            get { return __pbn__ver.GetValueOrDefault(); }
            set { __pbn__ver = value; }
        }
        public bool ShouldSerializever() => __pbn__ver != null;
        public void Resetver() => __pbn__ver = null;
        private uint? __pbn__ver;

        [global::ProtoBuf.ProtoMember(2)]
        public MatchConfig config { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

        [global::ProtoBuf.ProtoMember(4)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CreateMatchReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong ante
        {
            get { return __pbn__ante.GetValueOrDefault(); }
            set { __pbn__ante = value; }
        }
        public bool ShouldSerializeante() => __pbn__ante != null;
        public void Resetante() => __pbn__ante = null;
        private ulong? __pbn__ante;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong sb
        {
            get { return __pbn__sb.GetValueOrDefault(); }
            set { __pbn__sb = value; }
        }
        public bool ShouldSerializesb() => __pbn__sb != null;
        public void Resetsb() => __pbn__sb = null;
        private ulong? __pbn__sb;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong bb
        {
            get { return __pbn__bb.GetValueOrDefault(); }
            set { __pbn__bb = value; }
        }
        public bool ShouldSerializebb() => __pbn__bb != null;
        public void Resetbb() => __pbn__bb = null;
        private ulong? __pbn__bb;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong minCarry
        {
            get { return __pbn__minCarry.GetValueOrDefault(); }
            set { __pbn__minCarry = value; }
        }
        public bool ShouldSerializeminCarry() => __pbn__minCarry != null;
        public void ResetminCarry() => __pbn__minCarry = null;
        private ulong? __pbn__minCarry;

        [global::ProtoBuf.ProtoMember(6)]
        public ulong maxCarry
        {
            get { return __pbn__maxCarry.GetValueOrDefault(); }
            set { __pbn__maxCarry = value; }
        }
        public bool ShouldSerializemaxCarry() => __pbn__maxCarry != null;
        public void ResetmaxCarry() => __pbn__maxCarry = null;
        private ulong? __pbn__maxCarry;

        [global::ProtoBuf.ProtoMember(7)]
        public uint seatNum
        {
            get { return __pbn__seatNum.GetValueOrDefault(); }
            set { __pbn__seatNum = value; }
        }
        public bool ShouldSerializeseatNum() => __pbn__seatNum != null;
        public void ResetseatNum() => __pbn__seatNum = null;
        private uint? __pbn__seatNum;

        [global::ProtoBuf.ProtoMember(8)]
        public uint actionTime
        {
            get { return __pbn__actionTime.GetValueOrDefault(); }
            set { __pbn__actionTime = value; }
        }
        public bool ShouldSerializeactionTime() => __pbn__actionTime != null;
        public void ResetactionTime() => __pbn__actionTime = null;
        private uint? __pbn__actionTime;

        [global::ProtoBuf.ProtoMember(9)]
        public uint matchTime
        {
            get { return __pbn__matchTime.GetValueOrDefault(); }
            set { __pbn__matchTime = value; }
        }
        public bool ShouldSerializematchTime() => __pbn__matchTime != null;
        public void ResetmatchTime() => __pbn__matchTime = null;
        private uint? __pbn__matchTime;

        [global::ProtoBuf.ProtoMember(10)]
        public bool straddle
        {
            get { return __pbn__straddle.GetValueOrDefault(); }
            set { __pbn__straddle = value; }
        }
        public bool ShouldSerializestraddle() => __pbn__straddle != null;
        public void Resetstraddle() => __pbn__straddle = null;
        private bool? __pbn__straddle;

        [global::ProtoBuf.ProtoMember(11)]
        public bool gpsLimit
        {
            get { return __pbn__gpsLimit.GetValueOrDefault(); }
            set { __pbn__gpsLimit = value; }
        }
        public bool ShouldSerializegpsLimit() => __pbn__gpsLimit != null;
        public void ResetgpsLimit() => __pbn__gpsLimit = null;
        private bool? __pbn__gpsLimit;

        [global::ProtoBuf.ProtoMember(12)]
        public bool ipLimit
        {
            get { return __pbn__ipLimit.GetValueOrDefault(); }
            set { __pbn__ipLimit = value; }
        }
        public bool ShouldSerializeipLimit() => __pbn__ipLimit != null;
        public void ResetipLimit() => __pbn__ipLimit = null;
        private bool? __pbn__ipLimit;

        [global::ProtoBuf.ProtoMember(13)]
        public bool buyinAuth
        {
            get { return __pbn__buyinAuth.GetValueOrDefault(); }
            set { __pbn__buyinAuth = value; }
        }
        public bool ShouldSerializebuyinAuth() => __pbn__buyinAuth != null;
        public void ResetbuyinAuth() => __pbn__buyinAuth = null;
        private bool? __pbn__buyinAuth;

        [global::ProtoBuf.ProtoMember(14)]
        public bool insurance
        {
            get { return __pbn__insurance.GetValueOrDefault(); }
            set { __pbn__insurance = value; }
        }
        public bool ShouldSerializeinsurance() => __pbn__insurance != null;
        public void Resetinsurance() => __pbn__insurance = null;
        private bool? __pbn__insurance;

        [global::ProtoBuf.ProtoMember(15)]
        public bool showAllHands
        {
            get { return __pbn__showAllHands.GetValueOrDefault(); }
            set { __pbn__showAllHands = value; }
        }
        public bool ShouldSerializeshowAllHands() => __pbn__showAllHands != null;
        public void ResetshowAllHands() => __pbn__showAllHands = null;
        private bool? __pbn__showAllHands;

        [global::ProtoBuf.ProtoMember(16)]
        public RoomFeeConf roomFeeConf { get; set; }

        [global::ProtoBuf.ProtoMember(17)]
        public MatchProp prop { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public bool friendLimit
        {
            get { return __pbn__friendLimit.GetValueOrDefault(); }
            set { __pbn__friendLimit = value; }
        }
        public bool ShouldSerializefriendLimit() => __pbn__friendLimit != null;
        public void ResetfriendLimit() => __pbn__friendLimit = null;
        private bool? __pbn__friendLimit;

        [global::ProtoBuf.ProtoMember(19)]
        public uint autoStartUserNum
        {
            get { return __pbn__autoStartUserNum.GetValueOrDefault(); }
            set { __pbn__autoStartUserNum = value; }
        }
        public bool ShouldSerializeautoStartUserNum() => __pbn__autoStartUserNum != null;
        public void ResetautoStartUserNum() => __pbn__autoStartUserNum = null;
        private uint? __pbn__autoStartUserNum;

        [global::ProtoBuf.ProtoMember(20)]
        public bool autoCreateMatch
        {
            get { return __pbn__autoCreateMatch.GetValueOrDefault(); }
            set { __pbn__autoCreateMatch = value; }
        }
        public bool ShouldSerializeautoCreateMatch() => __pbn__autoCreateMatch != null;
        public void ResetautoCreateMatch() => __pbn__autoCreateMatch = null;
        private bool? __pbn__autoCreateMatch;

        [global::ProtoBuf.ProtoMember(21)]
        public bool closeChat
        {
            get { return __pbn__closeChat.GetValueOrDefault(); }
            set { __pbn__closeChat = value; }
        }
        public bool ShouldSerializecloseChat() => __pbn__closeChat != null;
        public void ResetcloseChat() => __pbn__closeChat = null;
        private bool? __pbn__closeChat;

        [global::ProtoBuf.ProtoMember(22)]
        public VpipConf vpipConf { get; set; }

        [global::ProtoBuf.ProtoMember(23)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

        [global::ProtoBuf.ProtoMember(24)]
        public uint unloadTimes
        {
            get { return __pbn__unloadTimes.GetValueOrDefault(); }
            set { __pbn__unloadTimes = value; }
        }
        public bool ShouldSerializeunloadTimes() => __pbn__unloadTimes != null;
        public void ResetunloadTimes() => __pbn__unloadTimes = null;
        private uint? __pbn__unloadTimes;

        [global::ProtoBuf.ProtoMember(25)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

        [global::ProtoBuf.ProtoMember(26)]
        public bool faceVip
        {
            get { return __pbn__faceVip.GetValueOrDefault(); }
            set { __pbn__faceVip = value; }
        }
        public bool ShouldSerializefaceVip() => __pbn__faceVip != null;
        public void ResetfaceVip() => __pbn__faceVip = null;
        private bool? __pbn__faceVip;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CreateMatchResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public MatchInfo match { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SearchMatchReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint roomid
        {
            get { return __pbn__roomid.GetValueOrDefault(); }
            set { __pbn__roomid = value; }
        }
        public bool ShouldSerializeroomid() => __pbn__roomid != null;
        public void Resetroomid() => __pbn__roomid = null;
        private uint? __pbn__roomid;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SearchMatchResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public MatchInfo match { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetMatchListReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint clubID
        {
            get { return __pbn__clubID.GetValueOrDefault(); }
            set { __pbn__clubID = value; }
        }
        public bool ShouldSerializeclubID() => __pbn__clubID != null;
        public void ResetclubID() => __pbn__clubID = null;
        private uint? __pbn__clubID;

        [global::ProtoBuf.ProtoMember(2)]
        public uint unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private uint? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public uint[] kinds { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetMatchListResp
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "pbcmd.MatchInfo")]
        public global::System.Collections.Generic.List<MatchInfo> list { get; } = new global::System.Collections.Generic.List<MatchInfo>();

        [global::ProtoBuf.ProtoMember(2)]
        public uint[] kinds { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchBalanceReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchBalanceResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.PlayerBalance")]
        public global::System.Collections.Generic.List<PlayerBalance> plist { get; } = new global::System.Collections.Generic.List<PlayerBalance>();

        [global::ProtoBuf.ProtoMember(4)]
        public InsuranceBalance insurance { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint leftTime
        {
            get { return __pbn__leftTime.GetValueOrDefault(); }
            set { __pbn__leftTime = value; }
        }
        public bool ShouldSerializeleftTime() => __pbn__leftTime != null;
        public void ResetleftTime() => __pbn__leftTime = null;
        private uint? __pbn__leftTime;

        [global::ProtoBuf.ProtoMember(6)]
        public uint totalTime
        {
            get { return __pbn__totalTime.GetValueOrDefault(); }
            set { __pbn__totalTime = value; }
        }
        public bool ShouldSerializetotalTime() => __pbn__totalTime != null;
        public void ResettotalTime() => __pbn__totalTime = null;
        private uint? __pbn__totalTime;

        [global::ProtoBuf.ProtoMember(7)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class MatchOverPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint totalHands
        {
            get { return __pbn__totalHands.GetValueOrDefault(); }
            set { __pbn__totalHands = value; }
        }
        public bool ShouldSerializetotalHands() => __pbn__totalHands != null;
        public void ResettotalHands() => __pbn__totalHands = null;
        private uint? __pbn__totalHands;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong totalBuyin
        {
            get { return __pbn__totalBuyin.GetValueOrDefault(); }
            set { __pbn__totalBuyin = value; }
        }
        public bool ShouldSerializetotalBuyin() => __pbn__totalBuyin != null;
        public void ResettotalBuyin() => __pbn__totalBuyin = null;
        private ulong? __pbn__totalBuyin;

        [global::ProtoBuf.ProtoMember(4)]
        public uint mvpuid
        {
            get { return __pbn__mvpuid.GetValueOrDefault(); }
            set { __pbn__mvpuid = value; }
        }
        public bool ShouldSerializemvpuid() => __pbn__mvpuid != null;
        public void Resetmvpuid() => __pbn__mvpuid = null;
        private uint? __pbn__mvpuid;

        [global::ProtoBuf.ProtoMember(5)]
        public uint fishuid
        {
            get { return __pbn__fishuid.GetValueOrDefault(); }
            set { __pbn__fishuid = value; }
        }
        public bool ShouldSerializefishuid() => __pbn__fishuid != null;
        public void Resetfishuid() => __pbn__fishuid = null;
        private uint? __pbn__fishuid;

        [global::ProtoBuf.ProtoMember(6)]
        public uint richuid
        {
            get { return __pbn__richuid.GetValueOrDefault(); }
            set { __pbn__richuid = value; }
        }
        public bool ShouldSerializerichuid() => __pbn__richuid != null;
        public void Resetrichuid() => __pbn__richuid = null;
        private uint? __pbn__richuid;

        [global::ProtoBuf.ProtoMember(7, TypeName = "pbcmd.PlayerBalance")]
        public global::System.Collections.Generic.List<PlayerBalance> plist { get; } = new global::System.Collections.Generic.List<PlayerBalance>();

        [global::ProtoBuf.ProtoMember(8)]
        public InsuranceBalance insurance { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public uint duration
        {
            get { return __pbn__duration.GetValueOrDefault(); }
            set { __pbn__duration = value; }
        }
        public bool ShouldSerializeduration() => __pbn__duration != null;
        public void Resetduration() => __pbn__duration = null;
        private uint? __pbn__duration;

        [global::ProtoBuf.ProtoMember(10)]
        public RoomFeeConf roomFeeConf { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public RoomFeeNum roomFeeNum { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public VpipConf vpipConf { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public uint unloadTimes
        {
            get { return __pbn__unloadTimes.GetValueOrDefault(); }
            set { __pbn__unloadTimes = value; }
        }
        public bool ShouldSerializeunloadTimes() => __pbn__unloadTimes != null;
        public void ResetunloadTimes() => __pbn__unloadTimes = null;
        private uint? __pbn__unloadTimes;

        [global::ProtoBuf.ProtoMember(15)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

        [global::ProtoBuf.ProtoMember(16)]
        public bool faceVip
        {
            get { return __pbn__faceVip.GetValueOrDefault(); }
            set { __pbn__faceVip = value; }
        }
        public bool ShouldSerializefaceVip() => __pbn__faceVip != null;
        public void ResetfaceVip() => __pbn__faceVip = null;
        private bool? __pbn__faceVip;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class BuyinReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong buyin
        {
            get { return __pbn__buyin.GetValueOrDefault(); }
            set { __pbn__buyin = value; }
        }
        public bool ShouldSerializebuyin() => __pbn__buyin != null;
        public void Resetbuyin() => __pbn__buyin = null;
        private ulong? __pbn__buyin;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class BuyinResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private int? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong costMoney
        {
            get { return __pbn__costMoney.GetValueOrDefault(); }
            set { __pbn__costMoney = value; }
        }
        public bool ShouldSerializecostMoney() => __pbn__costMoney != null;
        public void ResetcostMoney() => __pbn__costMoney = null;
        private ulong? __pbn__costMoney;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong leftMoney
        {
            get { return __pbn__leftMoney.GetValueOrDefault(); }
            set { __pbn__leftMoney = value; }
        }
        public bool ShouldSerializeleftMoney() => __pbn__leftMoney != null;
        public void ResetleftMoney() => __pbn__leftMoney = null;
        private ulong? __pbn__leftMoney;

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CloseMatchReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CloseMatchResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CloseMatchPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public int state
        {
            get { return __pbn__state.GetValueOrDefault(); }
            set { __pbn__state = value; }
        }
        public bool ShouldSerializestate() => __pbn__state != null;
        public void Resetstate() => __pbn__state = null;
        private int? __pbn__state;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CloseMatchRemindPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint remindSecond
        {
            get { return __pbn__remindSecond.GetValueOrDefault(); }
            set { __pbn__remindSecond = value; }
        }
        public bool ShouldSerializeremindSecond() => __pbn__remindSecond != null;
        public void ResetremindSecond() => __pbn__remindSecond = null;
        private uint? __pbn__remindSecond;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RealtimeData
    {
        [global::ProtoBuf.ProtoMember(1)]
        public MatchInfo match { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public RoomFeeConf roomFeeConf { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int buyInUserNum
        {
            get { return __pbn__buyInUserNum.GetValueOrDefault(); }
            set { __pbn__buyInUserNum = value; }
        }
        public bool ShouldSerializebuyInUserNum() => __pbn__buyInUserNum != null;
        public void ResetbuyInUserNum() => __pbn__buyInUserNum = null;
        private int? __pbn__buyInUserNum;

        [global::ProtoBuf.ProtoMember(4)]
        public int playingUserNum
        {
            get { return __pbn__playingUserNum.GetValueOrDefault(); }
            set { __pbn__playingUserNum = value; }
        }
        public bool ShouldSerializeplayingUserNum() => __pbn__playingUserNum != null;
        public void ResetplayingUserNum() => __pbn__playingUserNum = null;
        private int? __pbn__playingUserNum;

        [global::ProtoBuf.ProtoMember(5)]
        public long totalBuyIn
        {
            get { return __pbn__totalBuyIn.GetValueOrDefault(); }
            set { __pbn__totalBuyIn = value; }
        }
        public bool ShouldSerializetotalBuyIn() => __pbn__totalBuyIn != null;
        public void ResettotalBuyIn() => __pbn__totalBuyIn = null;
        private long? __pbn__totalBuyIn;

        [global::ProtoBuf.ProtoMember(6)]
        public long totalProfit
        {
            get { return __pbn__totalProfit.GetValueOrDefault(); }
            set { __pbn__totalProfit = value; }
        }
        public bool ShouldSerializetotalProfit() => __pbn__totalProfit != null;
        public void ResettotalProfit() => __pbn__totalProfit = null;
        private long? __pbn__totalProfit;

        [global::ProtoBuf.ProtoMember(7)]
        public long totalProfitPositive
        {
            get { return __pbn__totalProfitPositive.GetValueOrDefault(); }
            set { __pbn__totalProfitPositive = value; }
        }
        public bool ShouldSerializetotalProfitPositive() => __pbn__totalProfitPositive != null;
        public void ResettotalProfitPositive() => __pbn__totalProfitPositive = null;
        private long? __pbn__totalProfitPositive;

        [global::ProtoBuf.ProtoMember(8)]
        public long totalProfitNegative
        {
            get { return __pbn__totalProfitNegative.GetValueOrDefault(); }
            set { __pbn__totalProfitNegative = value; }
        }
        public bool ShouldSerializetotalProfitNegative() => __pbn__totalProfitNegative != null;
        public void ResettotalProfitNegative() => __pbn__totalProfitNegative = null;
        private long? __pbn__totalProfitNegative;

        [global::ProtoBuf.ProtoMember(9)]
        public long totalBuyInsurance
        {
            get { return __pbn__totalBuyInsurance.GetValueOrDefault(); }
            set { __pbn__totalBuyInsurance = value; }
        }
        public bool ShouldSerializetotalBuyInsurance() => __pbn__totalBuyInsurance != null;
        public void ResettotalBuyInsurance() => __pbn__totalBuyInsurance = null;
        private long? __pbn__totalBuyInsurance;

        [global::ProtoBuf.ProtoMember(10)]
        public long totalPayInsurance
        {
            get { return __pbn__totalPayInsurance.GetValueOrDefault(); }
            set { __pbn__totalPayInsurance = value; }
        }
        public bool ShouldSerializetotalPayInsurance() => __pbn__totalPayInsurance != null;
        public void ResettotalPayInsurance() => __pbn__totalPayInsurance = null;
        private long? __pbn__totalPayInsurance;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetRealtimeDataReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class GetRealtimeDataResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.RealtimeData")]
        public global::System.Collections.Generic.List<RealtimeData> list { get; } = new global::System.Collections.Generic.List<RealtimeData>();

        [global::ProtoBuf.ProtoMember(5)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class StartMatchReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class StartMatchResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class StartMatchPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SettlementDeTailReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SettlementDeTailResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong profit
        {
            get { return __pbn__profit.GetValueOrDefault(); }
            set { __pbn__profit = value; }
        }
        public bool ShouldSerializeprofit() => __pbn__profit != null;
        public void Resetprofit() => __pbn__profit = null;
        private ulong? __pbn__profit;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong checkout
        {
            get { return __pbn__checkout.GetValueOrDefault(); }
            set { __pbn__checkout = value; }
        }
        public bool ShouldSerializecheckout() => __pbn__checkout != null;
        public void Resetcheckout() => __pbn__checkout = null;
        private ulong? __pbn__checkout;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong penalty
        {
            get { return __pbn__penalty.GetValueOrDefault(); }
            set { __pbn__penalty = value; }
        }
        public bool ShouldSerializepenalty() => __pbn__penalty != null;
        public void Resetpenalty() => __pbn__penalty = null;
        private ulong? __pbn__penalty;

        [global::ProtoBuf.ProtoMember(6)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SettlementReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SettlementResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SettlementPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong checkout
        {
            get { return __pbn__checkout.GetValueOrDefault(); }
            set { __pbn__checkout = value; }
        }
        public bool ShouldSerializecheckout() => __pbn__checkout != null;
        public void Resetcheckout() => __pbn__checkout = null;
        private ulong? __pbn__checkout;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong leftMoney
        {
            get { return __pbn__leftMoney.GetValueOrDefault(); }
            set { __pbn__leftMoney = value; }
        }
        public bool ShouldSerializeleftMoney() => __pbn__leftMoney != null;
        public void ResetleftMoney() => __pbn__leftMoney = null;
        private ulong? __pbn__leftMoney;

        [global::ProtoBuf.ProtoMember(4)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CheckPenaltyReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class CheckPenaltyResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint mid
        {
            get { return __pbn__mid.GetValueOrDefault(); }
            set { __pbn__mid = value; }
        }
        public bool ShouldSerializemid() => __pbn__mid != null;
        public void Resetmid() => __pbn__mid = null;
        private uint? __pbn__mid;

        [global::ProtoBuf.ProtoMember(3)]
        public long penalty
        {
            get { return __pbn__penalty.GetValueOrDefault(); }
            set { __pbn__penalty = value; }
        }
        public bool ShouldSerializepenalty() => __pbn__penalty != null;
        public void Resetpenalty() => __pbn__penalty = null;
        private long? __pbn__penalty;

        [global::ProtoBuf.ProtoMember(4)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

}

#pragma warning restore CS1591, CS0612, CS3021
