// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: matchList.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqMatchList
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int matchType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint matchLevel
        {
            get { return __pbn__matchLevel.GetValueOrDefault(); }
            set { __pbn__matchLevel = value; }
        }
        public bool ShouldSerializematchLevel() => __pbn__matchLevel != null;
        public void ResetmatchLevel() => __pbn__matchLevel = null;
        private uint? __pbn__matchLevel;

        [global::ProtoBuf.ProtoMember(3)]
        public uint matchKind
        {
            get { return __pbn__matchKind.GetValueOrDefault(); }
            set { __pbn__matchKind = value; }
        }
        public bool ShouldSerializematchKind() => __pbn__matchKind != null;
        public void ResetmatchKind() => __pbn__matchKind = null;
        private uint? __pbn__matchKind;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBMatchInfo
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint maxSeats { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public ulong sb { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public ulong bb { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public bool hasAnte
        {
            get { return __pbn__hasAnte.GetValueOrDefault(); }
            set { __pbn__hasAnte = value; }
        }
        public bool ShouldSerializehasAnte() => __pbn__hasAnte != null;
        public void ResethasAnte() => __pbn__hasAnte = null;
        private bool? __pbn__hasAnte;

        [global::ProtoBuf.ProtoMember(8)]
        public ulong ante
        {
            get { return __pbn__ante.GetValueOrDefault(); }
            set { __pbn__ante = value; }
        }
        public bool ShouldSerializeante() => __pbn__ante != null;
        public void Resetante() => __pbn__ante = null;
        private ulong? __pbn__ante;

        [global::ProtoBuf.ProtoMember(9)]
        public ulong minBuyin
        {
            get { return __pbn__minBuyin.GetValueOrDefault(); }
            set { __pbn__minBuyin = value; }
        }
        public bool ShouldSerializeminBuyin() => __pbn__minBuyin != null;
        public void ResetminBuyin() => __pbn__minBuyin = null;
        private ulong? __pbn__minBuyin;

        [global::ProtoBuf.ProtoMember(10)]
        public ulong maxBuyin
        {
            get { return __pbn__maxBuyin.GetValueOrDefault(); }
            set { __pbn__maxBuyin = value; }
        }
        public bool ShouldSerializemaxBuyin() => __pbn__maxBuyin != null;
        public void ResetmaxBuyin() => __pbn__maxBuyin = null;
        private ulong? __pbn__maxBuyin;

        [global::ProtoBuf.ProtoMember(11)]
        public bool hasInsurance
        {
            get { return __pbn__hasInsurance.GetValueOrDefault(); }
            set { __pbn__hasInsurance = value; }
        }
        public bool ShouldSerializehasInsurance() => __pbn__hasInsurance != null;
        public void ResethasInsurance() => __pbn__hasInsurance = null;
        private bool? __pbn__hasInsurance;

        [global::ProtoBuf.ProtoMember(12)]
        public bool hasTimeLimit
        {
            get { return __pbn__hasTimeLimit.GetValueOrDefault(); }
            set { __pbn__hasTimeLimit = value; }
        }
        public bool ShouldSerializehasTimeLimit() => __pbn__hasTimeLimit != null;
        public void ResethasTimeLimit() => __pbn__hasTimeLimit = null;
        private bool? __pbn__hasTimeLimit;

        [global::ProtoBuf.ProtoMember(13)]
        public uint startTime
        {
            get { return __pbn__startTime.GetValueOrDefault(); }
            set { __pbn__startTime = value; }
        }
        public bool ShouldSerializestartTime() => __pbn__startTime != null;
        public void ResetstartTime() => __pbn__startTime = null;
        private uint? __pbn__startTime;

        [global::ProtoBuf.ProtoMember(14)]
        public uint totalLimitTime
        {
            get { return __pbn__totalLimitTime.GetValueOrDefault(); }
            set { __pbn__totalLimitTime = value; }
        }
        public bool ShouldSerializetotalLimitTime() => __pbn__totalLimitTime != null;
        public void ResettotalLimitTime() => __pbn__totalLimitTime = null;
        private uint? __pbn__totalLimitTime;

        [global::ProtoBuf.ProtoMember(15)]
        public uint remainLimitTime
        {
            get { return __pbn__remainLimitTime.GetValueOrDefault(); }
            set { __pbn__remainLimitTime = value; }
        }
        public bool ShouldSerializeremainLimitTime() => __pbn__remainLimitTime != null;
        public void ResetremainLimitTime() => __pbn__remainLimitTime = null;
        private uint? __pbn__remainLimitTime;

        [global::ProtoBuf.ProtoMember(16)]
        public bool needPassword
        {
            get { return __pbn__needPassword.GetValueOrDefault(); }
            set { __pbn__needPassword = value; }
        }
        public bool ShouldSerializeneedPassword() => __pbn__needPassword != null;
        public void ResetneedPassword() => __pbn__needPassword = null;
        private bool? __pbn__needPassword;

        [global::ProtoBuf.ProtoMember(17, IsRequired = true)]
        public uint inUseSeats { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public uint password
        {
            get { return __pbn__password.GetValueOrDefault(); }
            set { __pbn__password = value; }
        }
        public bool ShouldSerializepassword() => __pbn__password != null;
        public void Resetpassword() => __pbn__password = null;
        private uint? __pbn__password;

        [global::ProtoBuf.ProtoMember(19)]
        public uint icon
        {
            get { return __pbn__icon.GetValueOrDefault(); }
            set { __pbn__icon = value; }
        }
        public bool ShouldSerializeicon() => __pbn__icon != null;
        public void Reseticon() => __pbn__icon = null;
        private uint? __pbn__icon;

        [global::ProtoBuf.ProtoMember(20)]
        public uint matchLevel
        {
            get { return __pbn__matchLevel.GetValueOrDefault(); }
            set { __pbn__matchLevel = value; }
        }
        public bool ShouldSerializematchLevel() => __pbn__matchLevel != null;
        public void ResetmatchLevel() => __pbn__matchLevel = null;
        private uint? __pbn__matchLevel;

        [global::ProtoBuf.ProtoMember(21)]
        public uint creatorUID
        {
            get { return __pbn__creatorUID.GetValueOrDefault(); }
            set { __pbn__creatorUID = value; }
        }
        public bool ShouldSerializecreatorUID() => __pbn__creatorUID != null;
        public void ResetcreatorUID() => __pbn__creatorUID = null;
        private uint? __pbn__creatorUID;

        [global::ProtoBuf.ProtoMember(22)]
        public uint cid
        {
            get { return __pbn__cid.GetValueOrDefault(); }
            set { __pbn__cid = value; }
        }
        public bool ShouldSerializecid() => __pbn__cid != null;
        public void Resetcid() => __pbn__cid = null;
        private uint? __pbn__cid;

        [global::ProtoBuf.ProtoMember(23)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clubName
        {
            get { return __pbn__clubName ?? ""; }
            set { __pbn__clubName = value; }
        }
        public bool ShouldSerializeclubName() => __pbn__clubName != null;
        public void ResetclubName() => __pbn__clubName = null;
        private string __pbn__clubName;

        [global::ProtoBuf.ProtoMember(24)]
        [global::System.ComponentModel.DefaultValue("")]
        public string chatGroupID
        {
            get { return __pbn__chatGroupID ?? ""; }
            set { __pbn__chatGroupID = value; }
        }
        public bool ShouldSerializechatGroupID() => __pbn__chatGroupID != null;
        public void ResetchatGroupID() => __pbn__chatGroupID = null;
        private string __pbn__chatGroupID;

        [global::ProtoBuf.ProtoMember(25)]
        public uint thinkingTime
        {
            get { return __pbn__thinkingTime.GetValueOrDefault(); }
            set { __pbn__thinkingTime = value; }
        }
        public bool ShouldSerializethinkingTime() => __pbn__thinkingTime != null;
        public void ResetthinkingTime() => __pbn__thinkingTime = null;
        private uint? __pbn__thinkingTime;

        [global::ProtoBuf.ProtoMember(26)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

        [global::ProtoBuf.ProtoMember(27)]
        public bool dealerDouble
        {
            get { return __pbn__dealerDouble.GetValueOrDefault(); }
            set { __pbn__dealerDouble = value; }
        }
        public bool ShouldSerializedealerDouble() => __pbn__dealerDouble != null;
        public void ResetdealerDouble() => __pbn__dealerDouble = null;
        private bool? __pbn__dealerDouble;

        [global::ProtoBuf.ProtoMember(28)]
        public uint minRetain
        {
            get { return __pbn__minRetain.GetValueOrDefault(); }
            set { __pbn__minRetain = value; }
        }
        public bool ShouldSerializeminRetain() => __pbn__minRetain != null;
        public void ResetminRetain() => __pbn__minRetain = null;
        private uint? __pbn__minRetain;

        [global::ProtoBuf.ProtoMember(29)]
        public uint minCashOut
        {
            get { return __pbn__minCashOut.GetValueOrDefault(); }
            set { __pbn__minCashOut = value; }
        }
        public bool ShouldSerializeminCashOut() => __pbn__minCashOut != null;
        public void ResetminCashOut() => __pbn__minCashOut = null;
        private uint? __pbn__minCashOut;

        [global::ProtoBuf.ProtoMember(30)]
        public bool hasStraddle
        {
            get { return __pbn__hasStraddle.GetValueOrDefault(); }
            set { __pbn__hasStraddle = value; }
        }
        public bool ShouldSerializehasStraddle() => __pbn__hasStraddle != null;
        public void ResethasStraddle() => __pbn__hasStraddle = null;
        private bool? __pbn__hasStraddle;

        [global::ProtoBuf.ProtoMember(31)]
        public bool hasIPLimit
        {
            get { return __pbn__hasIPLimit.GetValueOrDefault(); }
            set { __pbn__hasIPLimit = value; }
        }
        public bool ShouldSerializehasIPLimit() => __pbn__hasIPLimit != null;
        public void ResethasIPLimit() => __pbn__hasIPLimit = null;
        private bool? __pbn__hasIPLimit;

        [global::ProtoBuf.ProtoMember(32)]
        public bool hasGPSLimit
        {
            get { return __pbn__hasGPSLimit.GetValueOrDefault(); }
            set { __pbn__hasGPSLimit = value; }
        }
        public bool ShouldSerializehasGPSLimit() => __pbn__hasGPSLimit != null;
        public void ResethasGPSLimit() => __pbn__hasGPSLimit = null;
        private bool? __pbn__hasGPSLimit;

        [global::ProtoBuf.ProtoMember(33)]
        public uint[] inSeatUIDs { get; set; }

        [global::ProtoBuf.ProtoMember(34)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clubIcon
        {
            get { return __pbn__clubIcon ?? ""; }
            set { __pbn__clubIcon = value; }
        }
        public bool ShouldSerializeclubIcon() => __pbn__clubIcon != null;
        public void ResetclubIcon() => __pbn__clubIcon = null;
        private string __pbn__clubIcon;

        [global::ProtoBuf.ProtoMember(35)]
        public bool showAllHands
        {
            get { return __pbn__showAllHands.GetValueOrDefault(); }
            set { __pbn__showAllHands = value; }
        }
        public bool ShouldSerializeshowAllHands() => __pbn__showAllHands != null;
        public void ResetshowAllHands() => __pbn__showAllHands = null;
        private bool? __pbn__showAllHands;

        [global::ProtoBuf.ProtoMember(36)]
        [global::System.ComponentModel.DefaultValue("")]
        public string creatorIcon
        {
            get { return __pbn__creatorIcon ?? ""; }
            set { __pbn__creatorIcon = value; }
        }
        public bool ShouldSerializecreatorIcon() => __pbn__creatorIcon != null;
        public void ResetcreatorIcon() => __pbn__creatorIcon = null;
        private string __pbn__creatorIcon;

        [global::ProtoBuf.ProtoMember(37)]
        [global::System.ComponentModel.DefaultValue("")]
        public string creatorName
        {
            get { return __pbn__creatorName ?? ""; }
            set { __pbn__creatorName = value; }
        }
        public bool ShouldSerializecreatorName() => __pbn__creatorName != null;
        public void ResetcreatorName() => __pbn__creatorName = null;
        private string __pbn__creatorName;

        [global::ProtoBuf.ProtoMember(38)]
        public bool friendLimit
        {
            get { return __pbn__friendLimit.GetValueOrDefault(); }
            set { __pbn__friendLimit = value; }
        }
        public bool ShouldSerializefriendLimit() => __pbn__friendLimit != null;
        public void ResetfriendLimit() => __pbn__friendLimit = null;
        private bool? __pbn__friendLimit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBSNGMatchInfo
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint maxSeats { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint inUseSeats { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public ulong registerFee { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        public ulong serviceFee
        {
            get { return __pbn__serviceFee.GetValueOrDefault(); }
            set { __pbn__serviceFee = value; }
        }
        public bool ShouldSerializeserviceFee() => __pbn__serviceFee != null;
        public void ResetserviceFee() => __pbn__serviceFee = null;
        private ulong? __pbn__serviceFee;

        [global::ProtoBuf.ProtoMember(8)]
        public bool needPassword
        {
            get { return __pbn__needPassword.GetValueOrDefault(); }
            set { __pbn__needPassword = value; }
        }
        public bool ShouldSerializeneedPassword() => __pbn__needPassword != null;
        public void ResetneedPassword() => __pbn__needPassword = null;
        private bool? __pbn__needPassword;

        [global::ProtoBuf.ProtoMember(9)]
        public uint password
        {
            get { return __pbn__password.GetValueOrDefault(); }
            set { __pbn__password = value; }
        }
        public bool ShouldSerializepassword() => __pbn__password != null;
        public void Resetpassword() => __pbn__password = null;
        private uint? __pbn__password;

        [global::ProtoBuf.ProtoMember(10)]
        public uint creatorUID
        {
            get { return __pbn__creatorUID.GetValueOrDefault(); }
            set { __pbn__creatorUID = value; }
        }
        public bool ShouldSerializecreatorUID() => __pbn__creatorUID != null;
        public void ResetcreatorUID() => __pbn__creatorUID = null;
        private uint? __pbn__creatorUID;

        [global::ProtoBuf.ProtoMember(11)]
        public uint cid
        {
            get { return __pbn__cid.GetValueOrDefault(); }
            set { __pbn__cid = value; }
        }
        public bool ShouldSerializecid() => __pbn__cid != null;
        public void Resetcid() => __pbn__cid = null;
        private uint? __pbn__cid;

        [global::ProtoBuf.ProtoMember(12)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clubName
        {
            get { return __pbn__clubName ?? ""; }
            set { __pbn__clubName = value; }
        }
        public bool ShouldSerializeclubName() => __pbn__clubName != null;
        public void ResetclubName() => __pbn__clubName = null;
        private string __pbn__clubName;

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string chatGroupID
        {
            get { return __pbn__chatGroupID ?? ""; }
            set { __pbn__chatGroupID = value; }
        }
        public bool ShouldSerializechatGroupID() => __pbn__chatGroupID != null;
        public void ResetchatGroupID() => __pbn__chatGroupID = null;
        private string __pbn__chatGroupID;

        [global::ProtoBuf.ProtoMember(14)]
        public uint startTime
        {
            get { return __pbn__startTime.GetValueOrDefault(); }
            set { __pbn__startTime = value; }
        }
        public bool ShouldSerializestartTime() => __pbn__startTime != null;
        public void ResetstartTime() => __pbn__startTime = null;
        private uint? __pbn__startTime;

        [global::ProtoBuf.ProtoMember(15)]
        public uint createTime
        {
            get { return __pbn__createTime.GetValueOrDefault(); }
            set { __pbn__createTime = value; }
        }
        public bool ShouldSerializecreateTime() => __pbn__createTime != null;
        public void ResetcreateTime() => __pbn__createTime = null;
        private uint? __pbn__createTime;

        [global::ProtoBuf.ProtoMember(16)]
        public uint dbIndex
        {
            get { return __pbn__dbIndex.GetValueOrDefault(); }
            set { __pbn__dbIndex = value; }
        }
        public bool ShouldSerializedbIndex() => __pbn__dbIndex != null;
        public void ResetdbIndex() => __pbn__dbIndex = null;
        private uint? __pbn__dbIndex;

        [global::ProtoBuf.ProtoMember(17, TypeName = "pbcmd.PBMatchPrize")]
        public global::System.Collections.Generic.List<PBMatchPrize> prizeList { get; } = new global::System.Collections.Generic.List<PBMatchPrize>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqClubMatchList
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint cid { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespMatchList
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "pbcmd.PBMatchInfo")]
        public global::System.Collections.Generic.List<PBMatchInfo> list { get; } = new global::System.Collections.Generic.List<PBMatchInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqOfficialMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong sb { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong bb { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint totalLimitTime { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public ulong minBuyin { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public ulong maxBuyin { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public uint maxSeats { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public int type { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool hasInsurance
        {
            get { return __pbn__hasInsurance.GetValueOrDefault(); }
            set { __pbn__hasInsurance = value; }
        }
        public bool ShouldSerializehasInsurance() => __pbn__hasInsurance != null;
        public void ResethasInsurance() => __pbn__hasInsurance = null;
        private bool? __pbn__hasInsurance;

        [global::ProtoBuf.ProtoMember(10)]
        public bool gpsLimit
        {
            get { return __pbn__gpsLimit.GetValueOrDefault(); }
            set { __pbn__gpsLimit = value; }
        }
        public bool ShouldSerializegpsLimit() => __pbn__gpsLimit != null;
        public void ResetgpsLimit() => __pbn__gpsLimit = null;
        private bool? __pbn__gpsLimit;

        [global::ProtoBuf.ProtoMember(11)]
        public bool ipLimit
        {
            get { return __pbn__ipLimit.GetValueOrDefault(); }
            set { __pbn__ipLimit = value; }
        }
        public bool ShouldSerializeipLimit() => __pbn__ipLimit != null;
        public void ResetipLimit() => __pbn__ipLimit = null;
        private bool? __pbn__ipLimit;

        [global::ProtoBuf.ProtoMember(12)]
        public ulong ante
        {
            get { return __pbn__ante.GetValueOrDefault(); }
            set { __pbn__ante = value; }
        }
        public bool ShouldSerializeante() => __pbn__ante != null;
        public void Resetante() => __pbn__ante = null;
        private ulong? __pbn__ante;

        [global::ProtoBuf.ProtoMember(13)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

        [global::ProtoBuf.ProtoMember(14)]
        public int matchType
        {
            get { return __pbn__matchType.GetValueOrDefault(); }
            set { __pbn__matchType = value; }
        }
        public bool ShouldSerializematchType() => __pbn__matchType != null;
        public void ResetmatchType() => __pbn__matchType = null;
        private int? __pbn__matchType;

        [global::ProtoBuf.ProtoMember(15)]
        public bool straddle
        {
            get { return __pbn__straddle.GetValueOrDefault(); }
            set { __pbn__straddle = value; }
        }
        public bool ShouldSerializestraddle() => __pbn__straddle != null;
        public void Resetstraddle() => __pbn__straddle = null;
        private bool? __pbn__straddle;

        [global::ProtoBuf.ProtoMember(16)]
        public bool showAllHands
        {
            get { return __pbn__showAllHands.GetValueOrDefault(); }
            set { __pbn__showAllHands = value; }
        }
        public bool ShouldSerializeshowAllHands() => __pbn__showAllHands != null;
        public void ResetshowAllHands() => __pbn__showAllHands = null;
        private bool? __pbn__showAllHands;

        [global::ProtoBuf.ProtoMember(17)]
        public bool friendLimit
        {
            get { return __pbn__friendLimit.GetValueOrDefault(); }
            set { __pbn__friendLimit = value; }
        }
        public bool ShouldSerializefriendLimit() => __pbn__friendLimit != null;
        public void ResetfriendLimit() => __pbn__friendLimit = null;
        private bool? __pbn__friendLimit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqCreateMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong sb { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong bb { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public uint totalLimitTime { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public ulong ante
        {
            get { return __pbn__ante.GetValueOrDefault(); }
            set { __pbn__ante = value; }
        }
        public bool ShouldSerializeante() => __pbn__ante != null;
        public void Resetante() => __pbn__ante = null;
        private ulong? __pbn__ante;

        [global::ProtoBuf.ProtoMember(6)]
        public bool hasInsurance
        {
            get { return __pbn__hasInsurance.GetValueOrDefault(); }
            set { __pbn__hasInsurance = value; }
        }
        public bool ShouldSerializehasInsurance() => __pbn__hasInsurance != null;
        public void ResethasInsurance() => __pbn__hasInsurance = null;
        private bool? __pbn__hasInsurance;

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public uint maxSeats { get; set; }

        [global::ProtoBuf.ProtoMember(8, IsRequired = true)]
        public ulong minBuyin { get; set; }

        [global::ProtoBuf.ProtoMember(9, IsRequired = true)]
        public ulong maxBuyin { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public bool gpsLimit
        {
            get { return __pbn__gpsLimit.GetValueOrDefault(); }
            set { __pbn__gpsLimit = value; }
        }
        public bool ShouldSerializegpsLimit() => __pbn__gpsLimit != null;
        public void ResetgpsLimit() => __pbn__gpsLimit = null;
        private bool? __pbn__gpsLimit;

        [global::ProtoBuf.ProtoMember(11)]
        public bool ipLimit
        {
            get { return __pbn__ipLimit.GetValueOrDefault(); }
            set { __pbn__ipLimit = value; }
        }
        public bool ShouldSerializeipLimit() => __pbn__ipLimit != null;
        public void ResetipLimit() => __pbn__ipLimit = null;
        private bool? __pbn__ipLimit;

        [global::ProtoBuf.ProtoMember(12)]
        public bool buyinAuthorize
        {
            get { return __pbn__buyinAuthorize.GetValueOrDefault(); }
            set { __pbn__buyinAuthorize = value; }
        }
        public bool ShouldSerializebuyinAuthorize() => __pbn__buyinAuthorize != null;
        public void ResetbuyinAuthorize() => __pbn__buyinAuthorize = null;
        private bool? __pbn__buyinAuthorize;

        [global::ProtoBuf.ProtoMember(13)]
        public uint feeNumerator
        {
            get { return __pbn__feeNumerator.GetValueOrDefault(); }
            set { __pbn__feeNumerator = value; }
        }
        public bool ShouldSerializefeeNumerator() => __pbn__feeNumerator != null;
        public void ResetfeeNumerator() => __pbn__feeNumerator = null;
        private uint? __pbn__feeNumerator;

        [global::ProtoBuf.ProtoMember(14)]
        public uint feeDenominator
        {
            get { return __pbn__feeDenominator.GetValueOrDefault(); }
            set { __pbn__feeDenominator = value; }
        }
        public bool ShouldSerializefeeDenominator() => __pbn__feeDenominator != null;
        public void ResetfeeDenominator() => __pbn__feeDenominator = null;
        private uint? __pbn__feeDenominator;

        [global::ProtoBuf.ProtoMember(15)]
        public ulong deposit
        {
            get { return __pbn__deposit.GetValueOrDefault(); }
            set { __pbn__deposit = value; }
        }
        public bool ShouldSerializedeposit() => __pbn__deposit != null;
        public void Resetdeposit() => __pbn__deposit = null;
        private ulong? __pbn__deposit;

        [global::ProtoBuf.ProtoMember(16)]
        public bool straddle
        {
            get { return __pbn__straddle.GetValueOrDefault(); }
            set { __pbn__straddle = value; }
        }
        public bool ShouldSerializestraddle() => __pbn__straddle != null;
        public void Resetstraddle() => __pbn__straddle = null;
        private bool? __pbn__straddle;

        [global::ProtoBuf.ProtoMember(17)]
        public bool jackpot
        {
            get { return __pbn__jackpot.GetValueOrDefault(); }
            set { __pbn__jackpot = value; }
        }
        public bool ShouldSerializejackpot() => __pbn__jackpot != null;
        public void Resetjackpot() => __pbn__jackpot = null;
        private bool? __pbn__jackpot;

        [global::ProtoBuf.ProtoMember(18)]
        public bool dealerDouble
        {
            get { return __pbn__dealerDouble.GetValueOrDefault(); }
            set { __pbn__dealerDouble = value; }
        }
        public bool ShouldSerializedealerDouble() => __pbn__dealerDouble != null;
        public void ResetdealerDouble() => __pbn__dealerDouble = null;
        private bool? __pbn__dealerDouble;

        [global::ProtoBuf.ProtoMember(19)]
        public uint minRetain
        {
            get { return __pbn__minRetain.GetValueOrDefault(); }
            set { __pbn__minRetain = value; }
        }
        public bool ShouldSerializeminRetain() => __pbn__minRetain != null;
        public void ResetminRetain() => __pbn__minRetain = null;
        private uint? __pbn__minRetain;

        [global::ProtoBuf.ProtoMember(20)]
        public uint minCashOut
        {
            get { return __pbn__minCashOut.GetValueOrDefault(); }
            set { __pbn__minCashOut = value; }
        }
        public bool ShouldSerializeminCashOut() => __pbn__minCashOut != null;
        public void ResetminCashOut() => __pbn__minCashOut = null;
        private uint? __pbn__minCashOut;

        [global::ProtoBuf.ProtoMember(21)]
        public uint kind
        {
            get { return __pbn__kind.GetValueOrDefault(); }
            set { __pbn__kind = value; }
        }
        public bool ShouldSerializekind() => __pbn__kind != null;
        public void Resetkind() => __pbn__kind = null;
        private uint? __pbn__kind;

        [global::ProtoBuf.ProtoMember(22)]
        public int matchType
        {
            get { return __pbn__matchType.GetValueOrDefault(); }
            set { __pbn__matchType = value; }
        }
        public bool ShouldSerializematchType() => __pbn__matchType != null;
        public void ResetmatchType() => __pbn__matchType = null;
        private int? __pbn__matchType;

        [global::ProtoBuf.ProtoMember(23)]
        public uint thinkingTime
        {
            get { return __pbn__thinkingTime.GetValueOrDefault(); }
            set { __pbn__thinkingTime = value; }
        }
        public bool ShouldSerializethinkingTime() => __pbn__thinkingTime != null;
        public void ResetthinkingTime() => __pbn__thinkingTime = null;
        private uint? __pbn__thinkingTime;

        [global::ProtoBuf.ProtoMember(24)]
        public bool showAllHands
        {
            get { return __pbn__showAllHands.GetValueOrDefault(); }
            set { __pbn__showAllHands = value; }
        }
        public bool ShouldSerializeshowAllHands() => __pbn__showAllHands != null;
        public void ResetshowAllHands() => __pbn__showAllHands = null;
        private bool? __pbn__showAllHands;

        [global::ProtoBuf.ProtoMember(25)]
        public PBRecordFee recordFee { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        public bool friendLimit
        {
            get { return __pbn__friendLimit.GetValueOrDefault(); }
            set { __pbn__friendLimit = value; }
        }
        public bool ShouldSerializefriendLimit() => __pbn__friendLimit != null;
        public void ResetfriendLimit() => __pbn__friendLimit = null;
        private bool? __pbn__friendLimit;

        [global::ProtoBuf.ProtoMember(27)]
        public bool closeChat
        {
            get { return __pbn__closeChat.GetValueOrDefault(); }
            set { __pbn__closeChat = value; }
        }
        public bool ShouldSerializecloseChat() => __pbn__closeChat != null;
        public void ResetcloseChat() => __pbn__closeChat = null;
        private bool? __pbn__closeChat;

        [global::ProtoBuf.ProtoMember(28)]
        public bool luckyCard
        {
            get { return __pbn__luckyCard.GetValueOrDefault(); }
            set { __pbn__luckyCard = value; }
        }
        public bool ShouldSerializeluckyCard() => __pbn__luckyCard != null;
        public void ResetluckyCard() => __pbn__luckyCard = null;
        private bool? __pbn__luckyCard;

        [global::ProtoBuf.ProtoMember(29)]
        public VpipConf vpipConf { get; set; }

        [global::ProtoBuf.ProtoMember(30)]
        public uint unloadTimes
        {
            get { return __pbn__unloadTimes.GetValueOrDefault(); }
            set { __pbn__unloadTimes = value; }
        }
        public bool ShouldSerializeunloadTimes() => __pbn__unloadTimes != null;
        public void ResetunloadTimes() => __pbn__unloadTimes = null;
        private uint? __pbn__unloadTimes;

        [global::ProtoBuf.ProtoMember(31)]
        public bool faceVip
        {
            get { return __pbn__faceVip.GetValueOrDefault(); }
            set { __pbn__faceVip = value; }
        }
        public bool ShouldSerializefaceVip() => __pbn__faceVip != null;
        public void ResetfaceVip() => __pbn__faceVip = null;
        private bool? __pbn__faceVip;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespCreateShort
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommResult result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint password
        {
            get { return __pbn__password.GetValueOrDefault(); }
            set { __pbn__password = value; }
        }
        public bool ShouldSerializepassword() => __pbn__password != null;
        public void Resetpassword() => __pbn__password = null;
        private uint? __pbn__password;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespCreateMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommResult result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint password
        {
            get { return __pbn__password.GetValueOrDefault(); }
            set { __pbn__password = value; }
        }
        public bool ShouldSerializepassword() => __pbn__password != null;
        public void Resetpassword() => __pbn__password = null;
        private uint? __pbn__password;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqMatchIndex
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint password { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespMatchIndex
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommResult result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PBMatchIndex idx { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqQuickJoinMatch
    {
        [global::ProtoBuf.ProtoMember(1)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint matchType
        {
            get { return __pbn__matchType.GetValueOrDefault(); }
            set { __pbn__matchType = value; }
        }
        public bool ShouldSerializematchType() => __pbn__matchType != null;
        public void ResetmatchType() => __pbn__matchType = null;
        private uint? __pbn__matchType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespQuickJoinMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommResult result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PBMatchIndex idx { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqMatchListByGroup
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public int matchType { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint matchLevel
        {
            get { return __pbn__matchLevel.GetValueOrDefault(); }
            set { __pbn__matchLevel = value; }
        }
        public bool ShouldSerializematchLevel() => __pbn__matchLevel != null;
        public void ResetmatchLevel() => __pbn__matchLevel = null;
        private uint? __pbn__matchLevel;

        [global::ProtoBuf.ProtoMember(3)]
        public uint sngLevel
        {
            get { return __pbn__sngLevel.GetValueOrDefault(); }
            set { __pbn__sngLevel = value; }
        }
        public bool ShouldSerializesngLevel() => __pbn__sngLevel != null;
        public void ResetsngLevel() => __pbn__sngLevel = null;
        private uint? __pbn__sngLevel;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBMatchListGroup
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string key { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong sb { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong bb { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ulong ante { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public bool hasInsurance { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public ulong minBuyin { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public uint players { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBMatchListSNGGroup
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string key { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong registerFee
        {
            get { return __pbn__registerFee.GetValueOrDefault(); }
            set { __pbn__registerFee = value; }
        }
        public bool ShouldSerializeregisterFee() => __pbn__registerFee != null;
        public void ResetregisterFee() => __pbn__registerFee = null;
        private ulong? __pbn__registerFee;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong serviceFee
        {
            get { return __pbn__serviceFee.GetValueOrDefault(); }
            set { __pbn__serviceFee = value; }
        }
        public bool ShouldSerializeserviceFee() => __pbn__serviceFee != null;
        public void ResetserviceFee() => __pbn__serviceFee = null;
        private ulong? __pbn__serviceFee;

        [global::ProtoBuf.ProtoMember(4)]
        public uint players
        {
            get { return __pbn__players.GetValueOrDefault(); }
            set { __pbn__players = value; }
        }
        public bool ShouldSerializeplayers() => __pbn__players != null;
        public void Resetplayers() => __pbn__players = null;
        private uint? __pbn__players;

        [global::ProtoBuf.ProtoMember(5)]
        public uint dbIndex
        {
            get { return __pbn__dbIndex.GetValueOrDefault(); }
            set { __pbn__dbIndex = value; }
        }
        public bool ShouldSerializedbIndex() => __pbn__dbIndex != null;
        public void ResetdbIndex() => __pbn__dbIndex = null;
        private uint? __pbn__dbIndex;

        [global::ProtoBuf.ProtoMember(6, TypeName = "pbcmd.PBMatchPrize")]
        public global::System.Collections.Generic.List<PBMatchPrize> prizeList { get; } = new global::System.Collections.Generic.List<PBMatchPrize>();

        [global::ProtoBuf.ProtoMember(7)]
        public uint maxSeats
        {
            get { return __pbn__maxSeats.GetValueOrDefault(); }
            set { __pbn__maxSeats = value; }
        }
        public bool ShouldSerializemaxSeats() => __pbn__maxSeats != null;
        public void ResetmaxSeats() => __pbn__maxSeats = null;
        private uint? __pbn__maxSeats;

        [global::ProtoBuf.ProtoMember(8)]
        public uint matchCount
        {
            get { return __pbn__matchCount.GetValueOrDefault(); }
            set { __pbn__matchCount = value; }
        }
        public bool ShouldSerializematchCount() => __pbn__matchCount != null;
        public void ResetmatchCount() => __pbn__matchCount = null;
        private uint? __pbn__matchCount;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespMatchListByGroup
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "pbcmd.PBMatchListGroup")]
        public global::System.Collections.Generic.List<PBMatchListGroup> groups { get; } = new global::System.Collections.Generic.List<PBMatchListGroup>();

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.PBMatchListSNGGroup")]
        public global::System.Collections.Generic.List<PBMatchListSNGGroup> sngGroups { get; } = new global::System.Collections.Generic.List<PBMatchListSNGGroup>();

        [global::ProtoBuf.ProtoMember(3)]
        public int matchType
        {
            get { return __pbn__matchType.GetValueOrDefault(); }
            set { __pbn__matchType = value; }
        }
        public bool ShouldSerializematchType() => __pbn__matchType != null;
        public void ResetmatchType() => __pbn__matchType = null;
        private int? __pbn__matchType;

        [global::ProtoBuf.ProtoMember(4)]
        public uint matchLevel
        {
            get { return __pbn__matchLevel.GetValueOrDefault(); }
            set { __pbn__matchLevel = value; }
        }
        public bool ShouldSerializematchLevel() => __pbn__matchLevel != null;
        public void ResetmatchLevel() => __pbn__matchLevel = null;
        private uint? __pbn__matchLevel;

        [global::ProtoBuf.ProtoMember(5)]
        public uint sngLevel
        {
            get { return __pbn__sngLevel.GetValueOrDefault(); }
            set { __pbn__sngLevel = value; }
        }
        public bool ShouldSerializesngLevel() => __pbn__sngLevel != null;
        public void ResetsngLevel() => __pbn__sngLevel = null;
        private uint? __pbn__sngLevel;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqJoinGroupMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string key { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint matchType
        {
            get { return __pbn__matchType.GetValueOrDefault(); }
            set { __pbn__matchType = value; }
        }
        public bool ShouldSerializematchType() => __pbn__matchType != null;
        public void ResetmatchType() => __pbn__matchType = null;
        private uint? __pbn__matchType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespJoinGroupMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommResult result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string key
        {
            get { return __pbn__key ?? ""; }
            set { __pbn__key = value; }
        }
        public bool ShouldSerializekey() => __pbn__key != null;
        public void Resetkey() => __pbn__key = null;
        private string __pbn__key;

        [global::ProtoBuf.ProtoMember(4)]
        public uint matchType
        {
            get { return __pbn__matchType.GetValueOrDefault(); }
            set { __pbn__matchType = value; }
        }
        public bool ShouldSerializematchType() => __pbn__matchType != null;
        public void ResetmatchType() => __pbn__matchType = null;
        private uint? __pbn__matchType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqGetCreateMatchConfig
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private uint? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBCreateShortAntes
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong antes { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint feeNumerator
        {
            get { return __pbn__feeNumerator.GetValueOrDefault(); }
            set { __pbn__feeNumerator = value; }
        }
        public bool ShouldSerializefeeNumerator() => __pbn__feeNumerator != null;
        public void ResetfeeNumerator() => __pbn__feeNumerator = null;
        private uint? __pbn__feeNumerator;

        [global::ProtoBuf.ProtoMember(3)]
        public uint feeDenominator
        {
            get { return __pbn__feeDenominator.GetValueOrDefault(); }
            set { __pbn__feeDenominator = value; }
        }
        public bool ShouldSerializefeeDenominator() => __pbn__feeDenominator != null;
        public void ResetfeeDenominator() => __pbn__feeDenominator = null;
        private uint? __pbn__feeDenominator;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong[] handLimits { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBCreateMatchBlinds
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong sb { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] antes { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint feeNumerator
        {
            get { return __pbn__feeNumerator.GetValueOrDefault(); }
            set { __pbn__feeNumerator = value; }
        }
        public bool ShouldSerializefeeNumerator() => __pbn__feeNumerator != null;
        public void ResetfeeNumerator() => __pbn__feeNumerator = null;
        private uint? __pbn__feeNumerator;

        [global::ProtoBuf.ProtoMember(4)]
        public uint feeDenominator
        {
            get { return __pbn__feeDenominator.GetValueOrDefault(); }
            set { __pbn__feeDenominator = value; }
        }
        public bool ShouldSerializefeeDenominator() => __pbn__feeDenominator != null;
        public void ResetfeeDenominator() => __pbn__feeDenominator = null;
        private uint? __pbn__feeDenominator;

        [global::ProtoBuf.ProtoMember(5)]
        public long[] handLimits { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespGetCreateMatchConfig
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint[] times { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] buyins { get; set; }

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.PBCreateMatchBlinds")]
        public global::System.Collections.Generic.List<PBCreateMatchBlinds> blinds { get; } = new global::System.Collections.Generic.List<PBCreateMatchBlinds>();

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.PBCreateShortAntes")]
        public global::System.Collections.Generic.List<PBCreateShortAntes> antes { get; } = new global::System.Collections.Generic.List<PBCreateShortAntes>();

        [global::ProtoBuf.ProtoMember(5)]
        public PBCreateSNGMatchConfig sngConfig { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public ulong defaultMinBuyin
        {
            get { return __pbn__defaultMinBuyin.GetValueOrDefault(); }
            set { __pbn__defaultMinBuyin = value; }
        }
        public bool ShouldSerializedefaultMinBuyin() => __pbn__defaultMinBuyin != null;
        public void ResetdefaultMinBuyin() => __pbn__defaultMinBuyin = null;
        private ulong? __pbn__defaultMinBuyin;

        [global::ProtoBuf.ProtoMember(7)]
        public ulong defaultMaxBuyin
        {
            get { return __pbn__defaultMaxBuyin.GetValueOrDefault(); }
            set { __pbn__defaultMaxBuyin = value; }
        }
        public bool ShouldSerializedefaultMaxBuyin() => __pbn__defaultMaxBuyin != null;
        public void ResetdefaultMaxBuyin() => __pbn__defaultMaxBuyin = null;
        private ulong? __pbn__defaultMaxBuyin;

        [global::ProtoBuf.ProtoMember(8)]
        public uint[] thinkTimes { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public uint[] buyFees { get; set; }

        [global::ProtoBuf.ProtoMember(10)]
        public uint[] profitFees { get; set; }

        [global::ProtoBuf.ProtoMember(11)]
        public uint[] potFees { get; set; }

        [global::ProtoBuf.ProtoMember(12)]
        public uint defaultBuyFee
        {
            get { return __pbn__defaultBuyFee.GetValueOrDefault(); }
            set { __pbn__defaultBuyFee = value; }
        }
        public bool ShouldSerializedefaultBuyFee() => __pbn__defaultBuyFee != null;
        public void ResetdefaultBuyFee() => __pbn__defaultBuyFee = null;
        private uint? __pbn__defaultBuyFee;

        [global::ProtoBuf.ProtoMember(13)]
        public uint defaultProfitFee
        {
            get { return __pbn__defaultProfitFee.GetValueOrDefault(); }
            set { __pbn__defaultProfitFee = value; }
        }
        public bool ShouldSerializedefaultProfitFee() => __pbn__defaultProfitFee != null;
        public void ResetdefaultProfitFee() => __pbn__defaultProfitFee = null;
        private uint? __pbn__defaultProfitFee;

        [global::ProtoBuf.ProtoMember(14)]
        public uint defaultPotFee
        {
            get { return __pbn__defaultPotFee.GetValueOrDefault(); }
            set { __pbn__defaultPotFee = value; }
        }
        public bool ShouldSerializedefaultPotFee() => __pbn__defaultPotFee != null;
        public void ResetdefaultPotFee() => __pbn__defaultPotFee = null;
        private uint? __pbn__defaultPotFee;

        [global::ProtoBuf.ProtoMember(15)]
        public uint privatePumpProportion
        {
            get { return __pbn__privatePumpProportion.GetValueOrDefault(); }
            set { __pbn__privatePumpProportion = value; }
        }
        public bool ShouldSerializeprivatePumpProportion() => __pbn__privatePumpProportion != null;
        public void ResetprivatePumpProportion() => __pbn__privatePumpProportion = null;
        private uint? __pbn__privatePumpProportion;

        [global::ProtoBuf.ProtoMember(16)]
        public uint clubPumpProportion
        {
            get { return __pbn__clubPumpProportion.GetValueOrDefault(); }
            set { __pbn__clubPumpProportion = value; }
        }
        public bool ShouldSerializeclubPumpProportion() => __pbn__clubPumpProportion != null;
        public void ResetclubPumpProportion() => __pbn__clubPumpProportion = null;
        private uint? __pbn__clubPumpProportion;

        [global::ProtoBuf.ProtoMember(17)]
        public uint[] userNums { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public uint[] shortUserNums { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBCreateSNGRegisterConfig
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public ulong registerFee { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong serviceFee { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBSNGBlindsTableItem
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint level { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong sb { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public ulong bb { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ulong ante { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBSNGBlindsTable
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public uint id { get; set; }

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.PBSNGBlindsTableItem")]
        public global::System.Collections.Generic.List<PBSNGBlindsTableItem> blindsItem { get; } = new global::System.Collections.Generic.List<PBSNGBlindsTableItem>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBCreateSNGMatchConfig
    {
        [global::ProtoBuf.ProtoMember(1, TypeName = "pbcmd.PBCreateSNGRegisterConfig")]
        public global::System.Collections.Generic.List<PBCreateSNGRegisterConfig> register { get; } = new global::System.Collections.Generic.List<PBCreateSNGRegisterConfig>();

        [global::ProtoBuf.ProtoMember(2)]
        public ulong[] startChips { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint[] raiseBlindGap { get; set; }

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.PBSNGBlindsTable")]
        public global::System.Collections.Generic.List<PBSNGBlindsTable> blindsTable { get; } = new global::System.Collections.Generic.List<PBSNGBlindsTable>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqCreateSNGMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public string name { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public ulong registerFee { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public ulong serviceFee
        {
            get { return __pbn__serviceFee.GetValueOrDefault(); }
            set { __pbn__serviceFee = value; }
        }
        public bool ShouldSerializeserviceFee() => __pbn__serviceFee != null;
        public void ResetserviceFee() => __pbn__serviceFee = null;
        private ulong? __pbn__serviceFee;

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public ulong startChips { get; set; }

        [global::ProtoBuf.ProtoMember(5, IsRequired = true)]
        public uint raiseBlindGap { get; set; }

        [global::ProtoBuf.ProtoMember(6, IsRequired = true)]
        public uint blindTableId { get; set; }

        [global::ProtoBuf.ProtoMember(7, IsRequired = true)]
        public uint maxSeats { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        public bool gpsLimit
        {
            get { return __pbn__gpsLimit.GetValueOrDefault(); }
            set { __pbn__gpsLimit = value; }
        }
        public bool ShouldSerializegpsLimit() => __pbn__gpsLimit != null;
        public void ResetgpsLimit() => __pbn__gpsLimit = null;
        private bool? __pbn__gpsLimit;

        [global::ProtoBuf.ProtoMember(9)]
        public bool ipLimit
        {
            get { return __pbn__ipLimit.GetValueOrDefault(); }
            set { __pbn__ipLimit = value; }
        }
        public bool ShouldSerializeipLimit() => __pbn__ipLimit != null;
        public void ResetipLimit() => __pbn__ipLimit = null;
        private bool? __pbn__ipLimit;

        [global::ProtoBuf.ProtoMember(10)]
        public bool buyinAuthorize
        {
            get { return __pbn__buyinAuthorize.GetValueOrDefault(); }
            set { __pbn__buyinAuthorize = value; }
        }
        public bool ShouldSerializebuyinAuthorize() => __pbn__buyinAuthorize != null;
        public void ResetbuyinAuthorize() => __pbn__buyinAuthorize = null;
        private bool? __pbn__buyinAuthorize;

        [global::ProtoBuf.ProtoMember(11)]
        public uint prizeType
        {
            get { return __pbn__prizeType.GetValueOrDefault(); }
            set { __pbn__prizeType = value; }
        }
        public bool ShouldSerializeprizeType() => __pbn__prizeType != null;
        public void ResetprizeType() => __pbn__prizeType = null;
        private uint? __pbn__prizeType;

        [global::ProtoBuf.ProtoMember(12)]
        public uint dbIndex
        {
            get { return __pbn__dbIndex.GetValueOrDefault(); }
            set { __pbn__dbIndex = value; }
        }
        public bool ShouldSerializedbIndex() => __pbn__dbIndex != null;
        public void ResetdbIndex() => __pbn__dbIndex = null;
        private uint? __pbn__dbIndex;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespCreateSNGMatch
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommResult result { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public PBMatchIndex idx { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint password
        {
            get { return __pbn__password.GetValueOrDefault(); }
            set { __pbn__password = value; }
        }
        public bool ShouldSerializepassword() => __pbn__password != null;
        public void Resetpassword() => __pbn__password = null;
        private uint? __pbn__password;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBPotFee
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint rate
        {
            get { return __pbn__rate.GetValueOrDefault(); }
            set { __pbn__rate = value; }
        }
        public bool ShouldSerializerate() => __pbn__rate != null;
        public void Resetrate() => __pbn__rate = null;
        private uint? __pbn__rate;

        [global::ProtoBuf.ProtoMember(2)]
        public long handsLimit
        {
            get { return __pbn__handsLimit.GetValueOrDefault(); }
            set { __pbn__handsLimit = value; }
        }
        public bool ShouldSerializehandsLimit() => __pbn__handsLimit != null;
        public void ResethandsLimit() => __pbn__handsLimit = null;
        private long? __pbn__handsLimit;

        [global::ProtoBuf.ProtoMember(3)]
        public long totalLimit
        {
            get { return __pbn__totalLimit.GetValueOrDefault(); }
            set { __pbn__totalLimit = value; }
        }
        public bool ShouldSerializetotalLimit() => __pbn__totalLimit != null;
        public void ResettotalLimit() => __pbn__totalLimit = null;
        private long? __pbn__totalLimit;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRecordFee
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint buyinFee
        {
            get { return __pbn__buyinFee.GetValueOrDefault(); }
            set { __pbn__buyinFee = value; }
        }
        public bool ShouldSerializebuyinFee() => __pbn__buyinFee != null;
        public void ResetbuyinFee() => __pbn__buyinFee = null;
        private uint? __pbn__buyinFee;

        [global::ProtoBuf.ProtoMember(2)]
        public uint profitFee
        {
            get { return __pbn__profitFee.GetValueOrDefault(); }
            set { __pbn__profitFee = value; }
        }
        public bool ShouldSerializeprofitFee() => __pbn__profitFee != null;
        public void ResetprofitFee() => __pbn__profitFee = null;
        private uint? __pbn__profitFee;

        [global::ProtoBuf.ProtoMember(3)]
        public PBPotFee potFee { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum PBCashLevel
    {
        TableLevelNewbie = 1,
        TableLevelBeginner = 2,
        TableLevelSenior = 3,
        TableLevelMaster = 4,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
