// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: promoActivity.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBReqGetFoundOnlineList
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommParam comm { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBFoundOnlineList
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string title
        {
            get { return __pbn__title ?? ""; }
            set { __pbn__title = value; }
        }
        public bool ShouldSerializetitle() => __pbn__title != null;
        public void Resettitle() => __pbn__title = null;
        private string __pbn__title;

        [global::ProtoBuf.ProtoMember(2)]
        public uint type
        {
            get { return __pbn__type.GetValueOrDefault(); }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private uint? __pbn__type;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string banner
        {
            get { return __pbn__banner ?? ""; }
            set { __pbn__banner = value; }
        }
        public bool ShouldSerializebanner() => __pbn__banner != null;
        public void Resetbanner() => __pbn__banner = null;
        private string __pbn__banner;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string content
        {
            get { return __pbn__content ?? ""; }
            set { __pbn__content = value; }
        }
        public bool ShouldSerializecontent() => __pbn__content != null;
        public void Resetcontent() => __pbn__content = null;
        private string __pbn__content;

        [global::ProtoBuf.ProtoMember(5)]
        [global::System.ComponentModel.DefaultValue("")]
        public string link
        {
            get { return __pbn__link ?? ""; }
            set { __pbn__link = value; }
        }
        public bool ShouldSerializelink() => __pbn__link != null;
        public void Resetlink() => __pbn__link = null;
        private string __pbn__link;

        [global::ProtoBuf.ProtoMember(6)]
        public uint onlinetime
        {
            get { return __pbn__onlinetime.GetValueOrDefault(); }
            set { __pbn__onlinetime = value; }
        }
        public bool ShouldSerializeonlinetime() => __pbn__onlinetime != null;
        public void Resetonlinetime() => __pbn__onlinetime = null;
        private uint? __pbn__onlinetime;

        [global::ProtoBuf.ProtoMember(7)]
        public uint offlinetime
        {
            get { return __pbn__offlinetime.GetValueOrDefault(); }
            set { __pbn__offlinetime = value; }
        }
        public bool ShouldSerializeofflinetime() => __pbn__offlinetime != null;
        public void Resetofflinetime() => __pbn__offlinetime = null;
        private uint? __pbn__offlinetime;

        [global::ProtoBuf.ProtoMember(8)]
        public uint status
        {
            get { return __pbn__status.GetValueOrDefault(); }
            set { __pbn__status = value; }
        }
        public bool ShouldSerializestatus() => __pbn__status != null;
        public void Resetstatus() => __pbn__status = null;
        private uint? __pbn__status;

        [global::ProtoBuf.ProtoMember(9)]
        public uint order
        {
            get { return __pbn__order.GetValueOrDefault(); }
            set { __pbn__order = value; }
        }
        public bool ShouldSerializeorder() => __pbn__order != null;
        public void Resetorder() => __pbn__order = null;
        private uint? __pbn__order;

        [global::ProtoBuf.ProtoMember(10)]
        public uint updatedat
        {
            get { return __pbn__updatedat.GetValueOrDefault(); }
            set { __pbn__updatedat = value; }
        }
        public bool ShouldSerializeupdatedat() => __pbn__updatedat != null;
        public void Resetupdatedat() => __pbn__updatedat = null;
        private uint? __pbn__updatedat;

        [global::ProtoBuf.ProtoMember(11)]
        public uint createdat
        {
            get { return __pbn__createdat.GetValueOrDefault(); }
            set { __pbn__createdat = value; }
        }
        public bool ShouldSerializecreatedat() => __pbn__createdat != null;
        public void Resetcreatedat() => __pbn__createdat = null;
        private uint? __pbn__createdat;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class PBRespGetFoundOnlineList
    {
        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public PBCommResult ret { get; set; }

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.PBFoundOnlineList")]
        public global::System.Collections.Generic.List<PBFoundOnlineList> list { get; } = new global::System.Collections.Generic.List<PBFoundOnlineList>();

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.PBFoundOnlineList")]
        public global::System.Collections.Generic.List<PBFoundOnlineList> match { get; } = new global::System.Collections.Generic.List<PBFoundOnlineList>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
