// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: fish.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishLoginReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint uid
        {
            get { return __pbn__uid.GetValueOrDefault(); }
            set { __pbn__uid = value; }
        }
        public bool ShouldSerializeuid() => __pbn__uid != null;
        public void Resetuid() => __pbn__uid = null;
        private uint? __pbn__uid;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientDefined
        {
            get { return __pbn__clientDefined ?? ""; }
            set { __pbn__clientDefined = value; }
        }
        public bool ShouldSerializeclientDefined() => __pbn__clientDefined != null;
        public void ResetclientDefined() => __pbn__clientDefined = null;
        private string __pbn__clientDefined;

        [global::ProtoBuf.ProtoMember(4)]
        public bool lite
        {
            get { return __pbn__lite.GetValueOrDefault(); }
            set { __pbn__lite = value; }
        }
        public bool ShouldSerializelite() => __pbn__lite != null;
        public void Resetlite() => __pbn__lite = null;
        private bool? __pbn__lite;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishLoginResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(3)]
        public bool lite
        {
            get { return __pbn__lite.GetValueOrDefault(); }
            set { __pbn__lite = value; }
        }
        public bool ShouldSerializelite() => __pbn__lite != null;
        public void Resetlite() => __pbn__lite = null;
        private bool? __pbn__lite;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishLoginPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint uid
        {
            get { return __pbn__uid.GetValueOrDefault(); }
            set { __pbn__uid = value; }
        }
        public bool ShouldSerializeuid() => __pbn__uid != null;
        public void Resetuid() => __pbn__uid = null;
        private uint? __pbn__uid;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientDefined
        {
            get { return __pbn__clientDefined ?? ""; }
            set { __pbn__clientDefined = value; }
        }
        public bool ShouldSerializeclientDefined() => __pbn__clientDefined != null;
        public void ResetclientDefined() => __pbn__clientDefined = null;
        private string __pbn__clientDefined;

        [global::ProtoBuf.ProtoMember(4)]
        public bool lite
        {
            get { return __pbn__lite.GetValueOrDefault(); }
            set { __pbn__lite = value; }
        }
        public bool ShouldSerializelite() => __pbn__lite != null;
        public void Resetlite() => __pbn__lite = null;
        private bool? __pbn__lite;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishLogoutReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishLogoutResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(3)]
        public bool lite
        {
            get { return __pbn__lite.GetValueOrDefault(); }
            set { __pbn__lite = value; }
        }
        public bool ShouldSerializelite() => __pbn__lite != null;
        public void Resetlite() => __pbn__lite = null;
        private bool? __pbn__lite;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishLogoutPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint uid
        {
            get { return __pbn__uid.GetValueOrDefault(); }
            set { __pbn__uid = value; }
        }
        public bool ShouldSerializeuid() => __pbn__uid != null;
        public void Resetuid() => __pbn__uid = null;
        private uint? __pbn__uid;

        [global::ProtoBuf.ProtoMember(3)]
        public uint reason
        {
            get { return __pbn__reason.GetValueOrDefault(); }
            set { __pbn__reason = value; }
        }
        public bool ShouldSerializereason() => __pbn__reason != null;
        public void Resetreason() => __pbn__reason = null;
        private uint? __pbn__reason;

        [global::ProtoBuf.ProtoMember(4)]
        public bool lite
        {
            get { return __pbn__lite.GetValueOrDefault(); }
            set { __pbn__lite = value; }
        }
        public bool ShouldSerializelite() => __pbn__lite != null;
        public void Resetlite() => __pbn__lite = null;
        private bool? __pbn__lite;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishPlayInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishPlayInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(3)]
        public uint state
        {
            get { return __pbn__state.GetValueOrDefault(); }
            set { __pbn__state = value; }
        }
        public bool ShouldSerializestate() => __pbn__state != null;
        public void Resetstate() => __pbn__state = null;
        private uint? __pbn__state;

        [global::ProtoBuf.ProtoMember(4)]
        public uint[] publicCards { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint[] sharkCards { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint[] fisherCards { get; set; }

        [global::ProtoBuf.ProtoMember(7, TypeName = "pbcmd.FishPot")]
        public global::System.Collections.Generic.List<FishPot> pots { get; } = new global::System.Collections.Generic.List<FishPot>();

        [global::ProtoBuf.ProtoMember(8)]
        public uint countdown
        {
            get { return __pbn__countdown.GetValueOrDefault(); }
            set { __pbn__countdown = value; }
        }
        public bool ShouldSerializecountdown() => __pbn__countdown != null;
        public void Resetcountdown() => __pbn__countdown = null;
        private uint? __pbn__countdown;

        [global::ProtoBuf.ProtoMember(9, TypeName = "pbcmd.FishPotBead")]
        public global::System.Collections.Generic.List<FishPotBead> beads { get; } = new global::System.Collections.Generic.List<FishPotBead>();

        [global::ProtoBuf.ProtoMember(10)]
        public uint winner
        {
            get { return __pbn__winner.GetValueOrDefault(); }
            set { __pbn__winner = value; }
        }
        public bool ShouldSerializewinner() => __pbn__winner != null;
        public void Resetwinner() => __pbn__winner = null;
        private uint? __pbn__winner;

        [global::ProtoBuf.ProtoMember(11)]
        public uint cardType
        {
            get { return __pbn__cardType.GetValueOrDefault(); }
            set { __pbn__cardType = value; }
        }
        public bool ShouldSerializecardType() => __pbn__cardType != null;
        public void ResetcardType() => __pbn__cardType = null;
        private uint? __pbn__cardType;

        [global::ProtoBuf.ProtoMember(12)]
        public uint[] handType { get; set; }

        [global::ProtoBuf.ProtoMember(13)]
        public uint[] bestFive { get; set; }

        [global::ProtoBuf.ProtoMember(14)]
        public uint handId
        {
            get { return __pbn__handId.GetValueOrDefault(); }
            set { __pbn__handId = value; }
        }
        public bool ShouldSerializehandId() => __pbn__handId != null;
        public void ResethandId() => __pbn__handId = null;
        private uint? __pbn__handId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishPotBead
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint[] showStat { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishActionReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint potId
        {
            get { return __pbn__potId.GetValueOrDefault(); }
            set { __pbn__potId = value; }
        }
        public bool ShouldSerializepotId() => __pbn__potId != null;
        public void ResetpotId() => __pbn__potId = null;
        private uint? __pbn__potId;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong chips
        {
            get { return __pbn__chips.GetValueOrDefault(); }
            set { __pbn__chips = value; }
        }
        public bool ShouldSerializechips() => __pbn__chips != null;
        public void Resetchips() => __pbn__chips = null;
        private ulong? __pbn__chips;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishActionResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong pkcBalance
        {
            get { return __pbn__pkcBalance.GetValueOrDefault(); }
            set { __pbn__pkcBalance = value; }
        }
        public bool ShouldSerializepkcBalance() => __pbn__pkcBalance != null;
        public void ResetpkcBalance() => __pbn__pkcBalance = null;
        private ulong? __pbn__pkcBalance;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishRepeatedActionReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.FishUserAction")]
        public global::System.Collections.Generic.List<FishUserAction> actions { get; } = new global::System.Collections.Generic.List<FishUserAction>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishRepeatedActionResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong pkcBalance
        {
            get { return __pbn__pkcBalance.GetValueOrDefault(); }
            set { __pbn__pkcBalance = value; }
        }
        public bool ShouldSerializepkcBalance() => __pbn__pkcBalance != null;
        public void ResetpkcBalance() => __pbn__pkcBalance = null;
        private ulong? __pbn__pkcBalance;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishActionPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint uid
        {
            get { return __pbn__uid.GetValueOrDefault(); }
            set { __pbn__uid = value; }
        }
        public bool ShouldSerializeuid() => __pbn__uid != null;
        public void Resetuid() => __pbn__uid = null;
        private uint? __pbn__uid;

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.FishUserAction")]
        public global::System.Collections.Generic.List<FishUserAction> actions { get; } = new global::System.Collections.Generic.List<FishUserAction>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishUserAction
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint uid
        {
            get { return __pbn__uid.GetValueOrDefault(); }
            set { __pbn__uid = value; }
        }
        public bool ShouldSerializeuid() => __pbn__uid != null;
        public void Resetuid() => __pbn__uid = null;
        private uint? __pbn__uid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint potId
        {
            get { return __pbn__potId.GetValueOrDefault(); }
            set { __pbn__potId = value; }
        }
        public bool ShouldSerializepotId() => __pbn__potId != null;
        public void ResetpotId() => __pbn__potId = null;
        private uint? __pbn__potId;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong[] chips { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clientDefined
        {
            get { return __pbn__clientDefined ?? ""; }
            set { __pbn__clientDefined = value; }
        }
        public bool ShouldSerializeclientDefined() => __pbn__clientDefined != null;
        public void ResetclientDefined() => __pbn__clientDefined = null;
        private string __pbn__clientDefined;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishHandHistoryReq
    {
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishHandHistoryResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.FishHandHistory")]
        public global::System.Collections.Generic.List<FishHandHistory> history { get; } = new global::System.Collections.Generic.List<FishHandHistory>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishHandHistory
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint[] publicCards { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint[] sharkCards { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint[] fisherCards { get; set; }

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.FishPot")]
        public global::System.Collections.Generic.List<FishPot> pots { get; } = new global::System.Collections.Generic.List<FishPot>();

        [global::ProtoBuf.ProtoMember(5)]
        public uint handNum
        {
            get { return __pbn__handNum.GetValueOrDefault(); }
            set { __pbn__handNum = value; }
        }
        public bool ShouldSerializehandNum() => __pbn__handNum != null;
        public void ResethandNum() => __pbn__handNum = null;
        private uint? __pbn__handNum;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishPot
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint id
        {
            get { return __pbn__id.GetValueOrDefault(); }
            set { __pbn__id = value; }
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private uint? __pbn__id;

        [global::ProtoBuf.ProtoMember(2)]
        public ulong totalBet
        {
            get { return __pbn__totalBet.GetValueOrDefault(); }
            set { __pbn__totalBet = value; }
        }
        public bool ShouldSerializetotalBet() => __pbn__totalBet != null;
        public void ResettotalBet() => __pbn__totalBet = null;
        private ulong? __pbn__totalBet;

        [global::ProtoBuf.ProtoMember(3)]
        public uint odds
        {
            get { return __pbn__odds.GetValueOrDefault(); }
            set { __pbn__odds = value; }
        }
        public bool ShouldSerializeodds() => __pbn__odds != null;
        public void Resetodds() => __pbn__odds = null;
        private uint? __pbn__odds;

        [global::ProtoBuf.ProtoMember(4)]
        public ulong userBet
        {
            get { return __pbn__userBet.GetValueOrDefault(); }
            set { __pbn__userBet = value; }
        }
        public bool ShouldSerializeuserBet() => __pbn__userBet != null;
        public void ResetuserBet() => __pbn__userBet = null;
        private ulong? __pbn__userBet;

        [global::ProtoBuf.ProtoMember(5)]
        public ulong userPay
        {
            get { return __pbn__userPay.GetValueOrDefault(); }
            set { __pbn__userPay = value; }
        }
        public bool ShouldSerializeuserPay() => __pbn__userPay != null;
        public void ResetuserPay() => __pbn__userPay = null;
        private ulong? __pbn__userPay;

        [global::ProtoBuf.ProtoMember(6)]
        public uint disappear
        {
            get { return __pbn__disappear.GetValueOrDefault(); }
            set { __pbn__disappear = value; }
        }
        public bool ShouldSerializedisappear() => __pbn__disappear != null;
        public void Resetdisappear() => __pbn__disappear = null;
        private uint? __pbn__disappear;

        [global::ProtoBuf.ProtoMember(7)]
        public bool show
        {
            get { return __pbn__show.GetValueOrDefault(); }
            set { __pbn__show = value; }
        }
        public bool ShouldSerializeshow() => __pbn__show != null;
        public void Resetshow() => __pbn__show = null;
        private bool? __pbn__show;

        [global::ProtoBuf.ProtoMember(8)]
        public ulong maxTotalBet
        {
            get { return __pbn__maxTotalBet.GetValueOrDefault(); }
            set { __pbn__maxTotalBet = value; }
        }
        public bool ShouldSerializemaxTotalBet() => __pbn__maxTotalBet != null;
        public void ResetmaxTotalBet() => __pbn__maxTotalBet = null;
        private ulong? __pbn__maxTotalBet;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue("")]
        public string disappearTxt
        {
            get { return __pbn__disappearTxt ?? ""; }
            set { __pbn__disappearTxt = value; }
        }
        public bool ShouldSerializedisappearTxt() => __pbn__disappearTxt != null;
        public void ResetdisappearTxt() => __pbn__disappearTxt = null;
        private string __pbn__disappearTxt;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishPreparePush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint state
        {
            get { return __pbn__state.GetValueOrDefault(); }
            set { __pbn__state = value; }
        }
        public bool ShouldSerializestate() => __pbn__state != null;
        public void Resetstate() => __pbn__state = null;
        private uint? __pbn__state;

        [global::ProtoBuf.ProtoMember(3)]
        public uint countdown
        {
            get { return __pbn__countdown.GetValueOrDefault(); }
            set { __pbn__countdown = value; }
        }
        public bool ShouldSerializecountdown() => __pbn__countdown != null;
        public void Resetcountdown() => __pbn__countdown = null;
        private uint? __pbn__countdown;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishHandStartPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint handId
        {
            get { return __pbn__handId.GetValueOrDefault(); }
            set { __pbn__handId = value; }
        }
        public bool ShouldSerializehandId() => __pbn__handId != null;
        public void ResethandId() => __pbn__handId = null;
        private uint? __pbn__handId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishActionStartPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint state
        {
            get { return __pbn__state.GetValueOrDefault(); }
            set { __pbn__state = value; }
        }
        public bool ShouldSerializestate() => __pbn__state != null;
        public void Resetstate() => __pbn__state = null;
        private uint? __pbn__state;

        [global::ProtoBuf.ProtoMember(3)]
        public uint countdown
        {
            get { return __pbn__countdown.GetValueOrDefault(); }
            set { __pbn__countdown = value; }
        }
        public bool ShouldSerializecountdown() => __pbn__countdown != null;
        public void Resetcountdown() => __pbn__countdown = null;
        private uint? __pbn__countdown;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishActionEndPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.FishPot")]
        public global::System.Collections.Generic.List<FishPot> pots { get; } = new global::System.Collections.Generic.List<FishPot>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishShowHandsPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2)]
        public uint state
        {
            get { return __pbn__state.GetValueOrDefault(); }
            set { __pbn__state = value; }
        }
        public bool ShouldSerializestate() => __pbn__state != null;
        public void Resetstate() => __pbn__state = null;
        private uint? __pbn__state;

        [global::ProtoBuf.ProtoMember(3)]
        public uint[] publicCards { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint[] sharkCards { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public uint[] fisherCards { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public uint winner
        {
            get { return __pbn__winner.GetValueOrDefault(); }
            set { __pbn__winner = value; }
        }
        public bool ShouldSerializewinner() => __pbn__winner != null;
        public void Resetwinner() => __pbn__winner = null;
        private uint? __pbn__winner;

        [global::ProtoBuf.ProtoMember(7)]
        public uint cardType
        {
            get { return __pbn__cardType.GetValueOrDefault(); }
            set { __pbn__cardType = value; }
        }
        public bool ShouldSerializecardType() => __pbn__cardType != null;
        public void ResetcardType() => __pbn__cardType = null;
        private uint? __pbn__cardType;

        [global::ProtoBuf.ProtoMember(8)]
        public uint[] handType { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public uint[] bestFive { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishHandEndPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint tid
        {
            get { return __pbn__tid.GetValueOrDefault(); }
            set { __pbn__tid = value; }
        }
        public bool ShouldSerializetid() => __pbn__tid != null;
        public void Resettid() => __pbn__tid = null;
        private uint? __pbn__tid;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.FishPot")]
        public global::System.Collections.Generic.List<FishPot> pots { get; } = new global::System.Collections.Generic.List<FishPot>();

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.FishPotBead")]
        public global::System.Collections.Generic.List<FishPotBead> beads { get; } = new global::System.Collections.Generic.List<FishPotBead>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishRichListReq
    {
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishRichListResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.FishRich")]
        public global::System.Collections.Generic.List<FishRich> riches { get; } = new global::System.Collections.Generic.List<FishRich>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class FishRich
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint uid
        {
            get { return __pbn__uid.GetValueOrDefault(); }
            set { __pbn__uid = value; }
        }
        public bool ShouldSerializeuid() => __pbn__uid != null;
        public void Resetuid() => __pbn__uid = null;
        private uint? __pbn__uid;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(3)]
        public ulong pkcBalance
        {
            get { return __pbn__pkcBalance.GetValueOrDefault(); }
            set { __pbn__pkcBalance = value; }
        }
        public bool ShouldSerializepkcBalance() => __pbn__pkcBalance != null;
        public void ResetpkcBalance() => __pbn__pkcBalance = null;
        private ulong? __pbn__pkcBalance;

        [global::ProtoBuf.ProtoMember(4)]
        public uint richType
        {
            get { return __pbn__richType.GetValueOrDefault(); }
            set { __pbn__richType = value; }
        }
        public bool ShouldSerializerichType() => __pbn__richType != null;
        public void ResetrichType() => __pbn__richType = null;
        private uint? __pbn__richType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum Fish
    {
        fishLoginReq = 1,
        fishLoginResp = 2,
        fishLogoutReq = 3,
        fishLogoutResp = 4,
        fishPlayInfoReq = 5,
        fishPlayInfoResp = 6,
        fishActionReq = 7,
        fishActionResp = 8,
        fishHandHistoryReq = 9,
        fishHandHistoryResp = 10,
        fishRepeatedActionReq = 11,
        fishRepeatedActionResp = 12,
        fishRichListReq = 13,
        fishRichListResp = 14,
        fishLoginPush = 1001,
        fishLogoutPush = 1002,
        fishPreparePush = 1003,
        fishHandStartPush = 1004,
        fishActionStartPush = 1005,
        fishActionPush = 1006,
        fishActionEndPush = 1007,
        fishShowHandsPush = 1008,
        fishHandEndPush = 1009,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
