// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: luckyCard.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyCardInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        public int gameKind
        {
            get { return __pbn__gameKind.GetValueOrDefault(); }
            set { __pbn__gameKind = value; }
        }
        public bool ShouldSerializegameKind() => __pbn__gameKind != null;
        public void ResetgameKind() => __pbn__gameKind = null;
        private int? __pbn__gameKind;

        [global::ProtoBuf.ProtoMember(3)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(4)]
        public int matchId
        {
            get { return __pbn__matchId.GetValueOrDefault(); }
            set { __pbn__matchId = value; }
        }
        public bool ShouldSerializematchId() => __pbn__matchId != null;
        public void ResetmatchId() => __pbn__matchId = null;
        private int? __pbn__matchId;

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyCardInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(3)]
        public int gameKind
        {
            get { return __pbn__gameKind.GetValueOrDefault(); }
            set { __pbn__gameKind = value; }
        }
        public bool ShouldSerializegameKind() => __pbn__gameKind != null;
        public void ResetgameKind() => __pbn__gameKind = null;
        private int? __pbn__gameKind;

        [global::ProtoBuf.ProtoMember(4)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(5)]
        public int matchId
        {
            get { return __pbn__matchId.GetValueOrDefault(); }
            set { __pbn__matchId = value; }
        }
        public bool ShouldSerializematchId() => __pbn__matchId != null;
        public void ResetmatchId() => __pbn__matchId = null;
        private int? __pbn__matchId;

        [global::ProtoBuf.ProtoMember(6)]
        public long pot
        {
            get { return __pbn__pot.GetValueOrDefault(); }
            set { __pbn__pot = value; }
        }
        public bool ShouldSerializepot() => __pbn__pot != null;
        public void Resetpot() => __pbn__pot = null;
        private long? __pbn__pot;

        [global::ProtoBuf.ProtoMember(7)]
        public int[] cards { get; set; }

        [global::ProtoBuf.ProtoMember(8, TypeName = "pbcmd.LuckyCardWinningRules")]
        public global::System.Collections.Generic.List<LuckyCardWinningRules> rules { get; } = new global::System.Collections.Generic.List<LuckyCardWinningRules>();

        [global::ProtoBuf.ProtoMember(9)]
        public int hits
        {
            get { return __pbn__hits.GetValueOrDefault(); }
            set { __pbn__hits = value; }
        }
        public bool ShouldSerializehits() => __pbn__hits != null;
        public void Resethits() => __pbn__hits = null;
        private int? __pbn__hits;

        [global::ProtoBuf.ProtoMember(10)]
        public long refreshAt
        {
            get { return __pbn__refreshAt.GetValueOrDefault(); }
            set { __pbn__refreshAt = value; }
        }
        public bool ShouldSerializerefreshAt() => __pbn__refreshAt != null;
        public void ResetrefreshAt() => __pbn__refreshAt = null;
        private long? __pbn__refreshAt;

        [global::ProtoBuf.ProtoMember(11)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

        [global::ProtoBuf.ProtoMember(12, TypeName = "pbcmd.LuckyCardWinningRules")]
        public global::System.Collections.Generic.List<LuckyCardWinningRules> vipRules { get; } = new global::System.Collections.Generic.List<LuckyCardWinningRules>();

        [global::ProtoBuf.ProtoMember(13)]
        [global::System.ComponentModel.DefaultValue("")]
        public string vipRatio
        {
            get { return __pbn__vipRatio ?? ""; }
            set { __pbn__vipRatio = value; }
        }
        public bool ShouldSerializevipRatio() => __pbn__vipRatio != null;
        public void ResetvipRatio() => __pbn__vipRatio = null;
        private string __pbn__vipRatio;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyCardWinningRules
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int hits
        {
            get { return __pbn__hits.GetValueOrDefault(); }
            set { __pbn__hits = value; }
        }
        public bool ShouldSerializehits() => __pbn__hits != null;
        public void Resethits() => __pbn__hits = null;
        private int? __pbn__hits;

        [global::ProtoBuf.ProtoMember(2)]
        public LuckyCardReward rewards { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyCardReward
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int value
        {
            get { return __pbn__value.GetValueOrDefault(); }
            set { __pbn__value = value; }
        }
        public bool ShouldSerializevalue() => __pbn__value != null;
        public void Resetvalue() => __pbn__value = null;
        private int? __pbn__value;

        [global::ProtoBuf.ProtoMember(2)]
        public int rewardType
        {
            get { return __pbn__rewardType.GetValueOrDefault(); }
            set { __pbn__rewardType = value; }
        }
        public bool ShouldSerializerewardType() => __pbn__rewardType != null;
        public void ResetrewardType() => __pbn__rewardType = null;
        private int? __pbn__rewardType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyCardWinningRecordsReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        public int gameKind
        {
            get { return __pbn__gameKind.GetValueOrDefault(); }
            set { __pbn__gameKind = value; }
        }
        public bool ShouldSerializegameKind() => __pbn__gameKind != null;
        public void ResetgameKind() => __pbn__gameKind = null;
        private int? __pbn__gameKind;

        [global::ProtoBuf.ProtoMember(3)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(4)]
        public int page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private int? __pbn__page;

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyCardWinningRecordsResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        public int totalRewardAmount
        {
            get { return __pbn__totalRewardAmount.GetValueOrDefault(); }
            set { __pbn__totalRewardAmount = value; }
        }
        public bool ShouldSerializetotalRewardAmount() => __pbn__totalRewardAmount != null;
        public void ResettotalRewardAmount() => __pbn__totalRewardAmount = null;
        private int? __pbn__totalRewardAmount;

        [global::ProtoBuf.ProtoMember(3)]
        public int gameKind
        {
            get { return __pbn__gameKind.GetValueOrDefault(); }
            set { __pbn__gameKind = value; }
        }
        public bool ShouldSerializegameKind() => __pbn__gameKind != null;
        public void ResetgameKind() => __pbn__gameKind = null;
        private int? __pbn__gameKind;

        [global::ProtoBuf.ProtoMember(4)]
        public LuckyCardWinningRecord highest { get; set; }

        [global::ProtoBuf.ProtoMember(5, TypeName = "pbcmd.LuckyCardWinningRecord")]
        public global::System.Collections.Generic.List<LuckyCardWinningRecord> records { get; } = new global::System.Collections.Generic.List<LuckyCardWinningRecord>();

        [global::ProtoBuf.ProtoMember(6)]
        public int total
        {
            get { return __pbn__total.GetValueOrDefault(); }
            set { __pbn__total = value; }
        }
        public bool ShouldSerializetotal() => __pbn__total != null;
        public void Resettotal() => __pbn__total = null;
        private int? __pbn__total;

        [global::ProtoBuf.ProtoMember(7)]
        public int page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private int? __pbn__page;

        [global::ProtoBuf.ProtoMember(8)]
        public int pagesize
        {
            get { return __pbn__pagesize.GetValueOrDefault(); }
            set { __pbn__pagesize = value; }
        }
        public bool ShouldSerializepagesize() => __pbn__pagesize != null;
        public void Resetpagesize() => __pbn__pagesize = null;
        private int? __pbn__pagesize;

        [global::ProtoBuf.ProtoMember(9)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(10)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyCardWinningRecord
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string clubName
        {
            get { return __pbn__clubName ?? ""; }
            set { __pbn__clubName = value; }
        }
        public bool ShouldSerializeclubName() => __pbn__clubName != null;
        public void ResetclubName() => __pbn__clubName = null;
        private string __pbn__clubName;

        [global::ProtoBuf.ProtoMember(3)]
        public int level
        {
            get { return __pbn__level.GetValueOrDefault(); }
            set { __pbn__level = value; }
        }
        public bool ShouldSerializelevel() => __pbn__level != null;
        public void Resetlevel() => __pbn__level = null;
        private int? __pbn__level;

        [global::ProtoBuf.ProtoMember(4)]
        public int hits
        {
            get { return __pbn__hits.GetValueOrDefault(); }
            set { __pbn__hits = value; }
        }
        public bool ShouldSerializehits() => __pbn__hits != null;
        public void Resethits() => __pbn__hits = null;
        private int? __pbn__hits;

        [global::ProtoBuf.ProtoMember(5)]
        public uint rewardAmount
        {
            get { return __pbn__rewardAmount.GetValueOrDefault(); }
            set { __pbn__rewardAmount = value; }
        }
        public bool ShouldSerializerewardAmount() => __pbn__rewardAmount != null;
        public void ResetrewardAmount() => __pbn__rewardAmount = null;
        private uint? __pbn__rewardAmount;

        [global::ProtoBuf.ProtoMember(6)]
        public long timestamp
        {
            get { return __pbn__timestamp.GetValueOrDefault(); }
            set { __pbn__timestamp = value; }
        }
        public bool ShouldSerializetimestamp() => __pbn__timestamp != null;
        public void Resettimestamp() => __pbn__timestamp = null;
        private long? __pbn__timestamp;

        [global::ProtoBuf.ProtoMember(7)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(8)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class LuckyHitPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int hits
        {
            get { return __pbn__hits.GetValueOrDefault(); }
            set { __pbn__hits = value; }
        }
        public bool ShouldSerializehits() => __pbn__hits != null;
        public void Resethits() => __pbn__hits = null;
        private int? __pbn__hits;

        [global::ProtoBuf.ProtoMember(2)]
        public int rewardAmount
        {
            get { return __pbn__rewardAmount.GetValueOrDefault(); }
            set { __pbn__rewardAmount = value; }
        }
        public bool ShouldSerializerewardAmount() => __pbn__rewardAmount != null;
        public void ResetrewardAmount() => __pbn__rewardAmount = null;
        private int? __pbn__rewardAmount;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum LuckyCard
    {
        luckyCardInfoReq = 1,
        luckyCardInfoResp = 2,
        luckyCardWinningRecordsReq = 3,
        luckyCardWinningRecordsResp = 4,
        luckyHitPush = 5,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
