// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: profile.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileGetMoneyReq
    {
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileGetMoneyResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public PBCommResult ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long timeCoin
        {
            get { return __pbn__timeCoin.GetValueOrDefault(); }
            set { __pbn__timeCoin = value; }
        }
        public bool ShouldSerializetimeCoin() => __pbn__timeCoin != null;
        public void ResettimeCoin() => __pbn__timeCoin = null;
        private long? __pbn__timeCoin;

        [global::ProtoBuf.ProtoMember(3)]
        public long pktCoin
        {
            get { return __pbn__pktCoin.GetValueOrDefault(); }
            set { __pbn__pktCoin = value; }
        }
        public bool ShouldSerializepktCoin() => __pbn__pktCoin != null;
        public void ResetpktCoin() => __pbn__pktCoin = null;
        private long? __pbn__pktCoin;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileMoneyExchangeReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(global::pbcmd.MoneyExchangeType.TC2PKC)]
        public MoneyExchangeType exchangeType
        {
            get { return __pbn__exchangeType ?? global::pbcmd.MoneyExchangeType.TC2PKC; }
            set { __pbn__exchangeType = value; }
        }
        public bool ShouldSerializeexchangeType() => __pbn__exchangeType != null;
        public void ResetexchangeType() => __pbn__exchangeType = null;
        private MoneyExchangeType? __pbn__exchangeType;

        [global::ProtoBuf.ProtoMember(2)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileMoneyExchangeResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public PBCommResult ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public long timeCoin
        {
            get { return __pbn__timeCoin.GetValueOrDefault(); }
            set { __pbn__timeCoin = value; }
        }
        public bool ShouldSerializetimeCoin() => __pbn__timeCoin != null;
        public void ResettimeCoin() => __pbn__timeCoin = null;
        private long? __pbn__timeCoin;

        [global::ProtoBuf.ProtoMember(3)]
        public long pktCoin
        {
            get { return __pbn__pktCoin.GetValueOrDefault(); }
            set { __pbn__pktCoin = value; }
        }
        public bool ShouldSerializepktCoin() => __pbn__pktCoin != null;
        public void ResetpktCoin() => __pbn__pktCoin = null;
        private long? __pbn__pktCoin;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileMoneyExchangeRecordReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(global::pbcmd.MoneyExchangeType.TC2PKC)]
        public MoneyExchangeType exchangeType
        {
            get { return __pbn__exchangeType ?? global::pbcmd.MoneyExchangeType.TC2PKC; }
            set { __pbn__exchangeType = value; }
        }
        public bool ShouldSerializeexchangeType() => __pbn__exchangeType != null;
        public void ResetexchangeType() => __pbn__exchangeType = null;
        private MoneyExchangeType? __pbn__exchangeType;

        [global::ProtoBuf.ProtoMember(2)]
        public uint page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private uint? __pbn__page;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileMoneyExchangeRecordResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public PBCommResult ret { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public uint total
        {
            get { return __pbn__total.GetValueOrDefault(); }
            set { __pbn__total = value; }
        }
        public bool ShouldSerializetotal() => __pbn__total != null;
        public void Resettotal() => __pbn__total = null;
        private uint? __pbn__total;

        [global::ProtoBuf.ProtoMember(3)]
        public uint page
        {
            get { return __pbn__page.GetValueOrDefault(); }
            set { __pbn__page = value; }
        }
        public bool ShouldSerializepage() => __pbn__page != null;
        public void Resetpage() => __pbn__page = null;
        private uint? __pbn__page;

        [global::ProtoBuf.ProtoMember(4)]
        public uint pagesize
        {
            get { return __pbn__pagesize.GetValueOrDefault(); }
            set { __pbn__pagesize = value; }
        }
        public bool ShouldSerializepagesize() => __pbn__pagesize != null;
        public void Resetpagesize() => __pbn__pagesize = null;
        private uint? __pbn__pagesize;

        [global::ProtoBuf.ProtoMember(5, TypeName = "pbcmd.ProfileMoneyExchangeRecordInfo")]
        public global::System.Collections.Generic.List<ProfileMoneyExchangeRecordInfo> recordList { get; } = new global::System.Collections.Generic.List<ProfileMoneyExchangeRecordInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileMoneyExchangeRecordInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint id
        {
            get { return __pbn__id.GetValueOrDefault(); }
            set { __pbn__id = value; }
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private uint? __pbn__id;

        [global::ProtoBuf.ProtoMember(2)]
        public uint status
        {
            get { return __pbn__status.GetValueOrDefault(); }
            set { __pbn__status = value; }
        }
        public bool ShouldSerializestatus() => __pbn__status != null;
        public void Resetstatus() => __pbn__status = null;
        private uint? __pbn__status;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(global::pbcmd.MoneyExchangeType.TC2PKC)]
        public MoneyExchangeType exchangeType
        {
            get { return __pbn__exchangeType ?? global::pbcmd.MoneyExchangeType.TC2PKC; }
            set { __pbn__exchangeType = value; }
        }
        public bool ShouldSerializeexchangeType() => __pbn__exchangeType != null;
        public void ResetexchangeType() => __pbn__exchangeType = null;
        private MoneyExchangeType? __pbn__exchangeType;

        [global::ProtoBuf.ProtoMember(4)]
        public long fromAmount
        {
            get { return __pbn__fromAmount.GetValueOrDefault(); }
            set { __pbn__fromAmount = value; }
        }
        public bool ShouldSerializefromAmount() => __pbn__fromAmount != null;
        public void ResetfromAmount() => __pbn__fromAmount = null;
        private long? __pbn__fromAmount;

        [global::ProtoBuf.ProtoMember(5)]
        public long toAmount
        {
            get { return __pbn__toAmount.GetValueOrDefault(); }
            set { __pbn__toAmount = value; }
        }
        public bool ShouldSerializetoAmount() => __pbn__toAmount != null;
        public void ResettoAmount() => __pbn__toAmount = null;
        private long? __pbn__toAmount;

        [global::ProtoBuf.ProtoMember(6)]
        public long createdAt
        {
            get { return __pbn__createdAt.GetValueOrDefault(); }
            set { __pbn__createdAt = value; }
        }
        public bool ShouldSerializecreatedAt() => __pbn__createdAt != null;
        public void ResetcreatedAt() => __pbn__createdAt = null;
        private long? __pbn__createdAt;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileActivityInfoReq
    {
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileActivityInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.ProfileActivityInfo")]
        public global::System.Collections.Generic.List<ProfileActivityInfo> activityInfos { get; } = new global::System.Collections.Generic.List<ProfileActivityInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileActivityInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint id
        {
            get { return __pbn__id.GetValueOrDefault(); }
            set { __pbn__id = value; }
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private uint? __pbn__id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string imgUrlCn
        {
            get { return __pbn__imgUrlCn ?? ""; }
            set { __pbn__imgUrlCn = value; }
        }
        public bool ShouldSerializeimgUrlCn() => __pbn__imgUrlCn != null;
        public void ResetimgUrlCn() => __pbn__imgUrlCn = null;
        private string __pbn__imgUrlCn;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue("")]
        public string imgUrlEng
        {
            get { return __pbn__imgUrlEng ?? ""; }
            set { __pbn__imgUrlEng = value; }
        }
        public bool ShouldSerializeimgUrlEng() => __pbn__imgUrlEng != null;
        public void ResetimgUrlEng() => __pbn__imgUrlEng = null;
        private string __pbn__imgUrlEng;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string url
        {
            get { return __pbn__url ?? ""; }
            set { __pbn__url = value; }
        }
        public bool ShouldSerializeurl() => __pbn__url != null;
        public void Reseturl() => __pbn__url = null;
        private string __pbn__url;

        [global::ProtoBuf.ProtoMember(5)]
        public uint activityType
        {
            get { return __pbn__activityType.GetValueOrDefault(); }
            set { __pbn__activityType = value; }
        }
        public bool ShouldSerializeactivityType() => __pbn__activityType != null;
        public void ResetactivityType() => __pbn__activityType = null;
        private uint? __pbn__activityType;

        [global::ProtoBuf.ProtoMember(6)]
        public ProfileDrawActivityInfo drawActivityInfo { get; set; }

        [global::ProtoBuf.ProtoMember(7)]
        [global::System.ComponentModel.DefaultValue("")]
        public string startTime
        {
            get { return __pbn__startTime ?? ""; }
            set { __pbn__startTime = value; }
        }
        public bool ShouldSerializestartTime() => __pbn__startTime != null;
        public void ResetstartTime() => __pbn__startTime = null;
        private string __pbn__startTime;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string endTime
        {
            get { return __pbn__endTime ?? ""; }
            set { __pbn__endTime = value; }
        }
        public bool ShouldSerializeendTime() => __pbn__endTime != null;
        public void ResetendTime() => __pbn__endTime = null;
        private string __pbn__endTime;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileDrawActivityInfo
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint handsNum
        {
            get { return __pbn__handsNum.GetValueOrDefault(); }
            set { __pbn__handsNum = value; }
        }
        public bool ShouldSerializehandsNum() => __pbn__handsNum != null;
        public void ResethandsNum() => __pbn__handsNum = null;
        private uint? __pbn__handsNum;

        [global::ProtoBuf.ProtoMember(2)]
        public bool canDraw
        {
            get { return __pbn__canDraw.GetValueOrDefault(); }
            set { __pbn__canDraw = value; }
        }
        public bool ShouldSerializecanDraw() => __pbn__canDraw != null;
        public void ResetcanDraw() => __pbn__canDraw = null;
        private bool? __pbn__canDraw;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileActivityHandsProgressReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint id
        {
            get { return __pbn__id.GetValueOrDefault(); }
            set { __pbn__id = value; }
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private uint? __pbn__id;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileActivityHandsProgressResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint playedHandsNum
        {
            get { return __pbn__playedHandsNum.GetValueOrDefault(); }
            set { __pbn__playedHandsNum = value; }
        }
        public bool ShouldSerializeplayedHandsNum() => __pbn__playedHandsNum != null;
        public void ResetplayedHandsNum() => __pbn__playedHandsNum = null;
        private uint? __pbn__playedHandsNum;

        [global::ProtoBuf.ProtoMember(2)]
        public uint drawHandsNum
        {
            get { return __pbn__drawHandsNum.GetValueOrDefault(); }
            set { __pbn__drawHandsNum = value; }
        }
        public bool ShouldSerializedrawHandsNum() => __pbn__drawHandsNum != null;
        public void ResetdrawHandsNum() => __pbn__drawHandsNum = null;
        private uint? __pbn__drawHandsNum;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileDangerPackageListReq
    {
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileDangerPackageListResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<string> packageList { get; } = new global::System.Collections.Generic.List<string>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileUseDangerPackageReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<string> packageList { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(2, TypeName = "pbcmd.ProfileUseDangerPackageReq.PkgInfo")]
        public global::System.Collections.Generic.List<PkgInfo> pkgInfoList { get; } = new global::System.Collections.Generic.List<PkgInfo>();

        [System.Serializable]
        [global::ProtoBuf.ProtoContract()]
        public partial class PkgInfo
        {
            [global::ProtoBuf.ProtoMember(1)]
            [global::System.ComponentModel.DefaultValue("")]
            public string name
            {
                get { return __pbn__name ?? ""; }
                set { __pbn__name = value; }
            }
            public bool ShouldSerializename() => __pbn__name != null;
            public void Resetname() => __pbn__name = null;
            private string __pbn__name;

            [global::ProtoBuf.ProtoMember(2)]
            public uint status
            {
                get { return __pbn__status.GetValueOrDefault(); }
                set { __pbn__status = value; }
            }
            public bool ShouldSerializestatus() => __pbn__status != null;
            public void Resetstatus() => __pbn__status = null;
            private uint? __pbn__status;

        }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileUseDangerPackageResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileSnapshotInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string imgUrl
        {
            get { return __pbn__imgUrl ?? ""; }
            set { __pbn__imgUrl = value; }
        }
        public bool ShouldSerializeimgUrl() => __pbn__imgUrl != null;
        public void ResetimgUrl() => __pbn__imgUrl = null;
        private string __pbn__imgUrl;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string errorMsg
        {
            get { return __pbn__errorMsg ?? ""; }
            set { __pbn__errorMsg = value; }
        }
        public bool ShouldSerializeerrorMsg() => __pbn__errorMsg != null;
        public void ReseterrorMsg() => __pbn__errorMsg = null;
        private string __pbn__errorMsg;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProfileSnapshotInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SkipUserGuideMarkReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public global::System.Collections.Generic.List<UserGuideMark> skipInfo { get; } = new global::System.Collections.Generic.List<UserGuideMark>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SkipUserGuideMarkResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public uint code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private uint? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum Profile
    {
        getMoneyReq = 1,
        getMoneyResp = 2,
        moneyExchangeReq = 3,
        moneyExchangeResp = 4,
        moneyExchangeRecordReq = 5,
        moneyExchangeRecordResp = 6,
        activityInfoReq = 7,
        activityInfoResp = 8,
        activityHandsProgressReq = 9,
        activityHandsProgressResp = 10,
        dangerPackageListReq = 11,
        dangerPackageListResp = 12,
        useDangerPackageReq = 13,
        useDangerPackageResp = 14,
        snapshotInfoReq = 15,
        snapshotInfoResp = 16,
        skipUserGuideMarkReq = 17,
        skipUserGuideMarkResp = 18,
    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum MoneyExchangeType
    {
        TC2PKC = 1,
        PKC2TC = 2,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
