// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: union.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace pbcmd
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(2)]
        public int displayId
        {
            get { return __pbn__displayId.GetValueOrDefault(); }
            set { __pbn__displayId = value; }
        }
        public bool ShouldSerializedisplayId() => __pbn__displayId != null;
        public void ResetdisplayId() => __pbn__displayId = null;
        private int? __pbn__displayId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public UnionInfo info { get; set; }

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.UnionUserInfo")]
        public global::System.Collections.Generic.List<UnionUserInfo> admins { get; } = new global::System.Collections.Generic.List<UnionUserInfo>();

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.ClubInfo")]
        public global::System.Collections.Generic.List<ClubInfo> clubInfos { get; } = new global::System.Collections.Generic.List<ClubInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class EditUnionInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string desc
        {
            get { return __pbn__desc ?? ""; }
            set { __pbn__desc = value; }
        }
        public bool ShouldSerializedesc() => __pbn__desc != null;
        public void Resetdesc() => __pbn__desc = null;
        private string __pbn__desc;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class EditUnionInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public UnionInfo info { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveUnionBalanceReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(2)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class SaveUnionBalanceResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(4)]
        public long unionIdBalance
        {
            get { return __pbn__unionIdBalance.GetValueOrDefault(); }
            set { __pbn__unionIdBalance = value; }
        }
        public bool ShouldSerializeunionIdBalance() => __pbn__unionIdBalance != null;
        public void ResetunionIdBalance() => __pbn__unionIdBalance = null;
        private long? __pbn__unionIdBalance;

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class WithdrawUnionBalanceReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(2)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(3)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class WithdrawUnionBalanceResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public long amount
        {
            get { return __pbn__amount.GetValueOrDefault(); }
            set { __pbn__amount = value; }
        }
        public bool ShouldSerializeamount() => __pbn__amount != null;
        public void Resetamount() => __pbn__amount = null;
        private long? __pbn__amount;

        [global::ProtoBuf.ProtoMember(4)]
        public long unionBalance
        {
            get { return __pbn__unionBalance.GetValueOrDefault(); }
            set { __pbn__unionBalance = value; }
        }
        public bool ShouldSerializeunionBalance() => __pbn__unionBalance != null;
        public void ResetunionBalance() => __pbn__unionBalance = null;
        private long? __pbn__unionBalance;

        [global::ProtoBuf.ProtoMember(5)]
        public uint coinType
        {
            get { return __pbn__coinType.GetValueOrDefault(); }
            set { __pbn__coinType = value; }
        }
        public bool ShouldSerializecoinType() => __pbn__coinType != null;
        public void ResetcoinType() => __pbn__coinType = null;
        private uint? __pbn__coinType;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionAdminsReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int UnionId
        {
            get { return __pbn__UnionId.GetValueOrDefault(); }
            set { __pbn__UnionId = value; }
        }
        public bool ShouldSerializeUnionId() => __pbn__UnionId != null;
        public void ResetUnionId() => __pbn__UnionId = null;
        private int? __pbn__UnionId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionAdminsResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3, TypeName = "pbcmd.UserInfo")]
        public global::System.Collections.Generic.List<UserInfo> admins { get; } = new global::System.Collections.Generic.List<UserInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class AddUnionAdminReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class AddUnionAdminResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(3)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.UnionUserInfo")]
        public global::System.Collections.Generic.List<UnionUserInfo> admins { get; } = new global::System.Collections.Generic.List<UnionUserInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveUnionAdminReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveUnionAdminResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

        [global::ProtoBuf.ProtoMember(3)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.UnionUserInfo")]
        public global::System.Collections.Generic.List<UnionUserInfo> admins { get; } = new global::System.Collections.Generic.List<UnionUserInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UserInfoReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int userId
        {
            get { return __pbn__userId.GetValueOrDefault(); }
            set { __pbn__userId = value; }
        }
        public bool ShouldSerializeuserId() => __pbn__userId != null;
        public void ResetuserId() => __pbn__userId = null;
        private int? __pbn__userId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UserInfoResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public UserInfo info { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessClubJoinReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(3)]
        public int option
        {
            get { return __pbn__option.GetValueOrDefault(); }
            set { __pbn__option = value; }
        }
        public bool ShouldSerializeoption() => __pbn__option != null;
        public void Resetoption() => __pbn__option = null;
        private int? __pbn__option;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class ProcessClubJoinResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveUnionClubReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(2)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class RemoveUnionClubResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

        [global::ProtoBuf.ProtoMember(3)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(4, TypeName = "pbcmd.ClubInfo")]
        public global::System.Collections.Generic.List<ClubInfo> infos { get; } = new global::System.Collections.Generic.List<ClubInfo>();

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class QuitUnionReq
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int clubId
        {
            get { return __pbn__clubId.GetValueOrDefault(); }
            set { __pbn__clubId = value; }
        }
        public bool ShouldSerializeclubId() => __pbn__clubId != null;
        public void ResetclubId() => __pbn__clubId = null;
        private int? __pbn__clubId;

        [global::ProtoBuf.ProtoMember(2)]
        public int unionId
        {
            get { return __pbn__unionId.GetValueOrDefault(); }
            set { __pbn__unionId = value; }
        }
        public bool ShouldSerializeunionId() => __pbn__unionId != null;
        public void ResetunionId() => __pbn__unionId = null;
        private int? __pbn__unionId;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class QuitUnionResp
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class UnionAdminLevelPush
    {
        [global::ProtoBuf.ProtoMember(1)]
        public int code
        {
            get { return __pbn__code.GetValueOrDefault(); }
            set { __pbn__code = value; }
        }
        public bool ShouldSerializecode() => __pbn__code != null;
        public void Resetcode() => __pbn__code = null;
        private int? __pbn__code;

        [global::ProtoBuf.ProtoMember(2)]
        public UnionAdminLevel level { get; set; }

    }

    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public enum Union
    {
        Cmd_UnionInfoReq = 1,
        Cmd_UnionInfoResp = 2,
        Cmd_EditUnionInfoReq = 3,
        Cmd_EditUnionInfoResp = 4,
        Cmd_SaveUnionBalanceReq = 5,
        Cmd_SaveUnionBalanceResp = 6,
        Cmd_WithdrawUnionBalanceReq = 7,
        Cmd_WithdrawUnionBalanceResp = 8,
        Cmd_AddUnionAdminReq = 9,
        Cmd_AddUnionAdminResp = 10,
        Cmd_RemoveUnionAdminReq = 11,
        Cmd_RemoveUnionAdminResp = 12,
        Cmd_UserInfoReq = 13,
        Cmd_UserInfoResp = 14,
        Cmd_ProcessClubJoinReq = 15,
        Cmd_ProcessClubJoinResp = 16,
        Cmd_RemoveUnionClubReq = 17,
        Cmd_RemoveUnionClubResp = 18,
        Cmd_QuitUnionReq = 19,
        Cmd_QuitUnionResp = 20,
    }

}

#pragma warning restore CS1591, CS0612, CS3021
